### ISSUE TITLE
JSON Schema validation with external sub-schema

### ISSUE THREAD

**Issue by bergeroy** [vlucas/frisby#100]
Hi,

I’m using Frisby to test my REST API.  Frisby is using jsonschema to validate the JSONs returned by a URL.

The JSON schema I use to validate my JSON is referencing an external schema via $ref.  In that situation, it seems that the jsonschema validation is always failing with a message similar to:

```
SchemaError: no such schema http://api-portal.anypoint.mulesoft.com/telus/api/kinexchangeapi/schema_domaine.json
```

It seems that to make jsonschema working correctly, we must use addSchema or addSubSchema for every external schema.  Frisby retrieve the file for the main schema but does not retrieve every subschema with a recursive loop and add them to the schema validator.

This is the schema I use for validation in Frisby :

```
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Liste de domaines",
  "required":false,
  "properties": {
    "domaines": {
      "type":"array",
      "required":true,
      "items": {
        "$ref": "http://api-portal.anypoint.mulesoft.com/telus/api/kinexchangeapi/schema_domaine.json"
      }
    }
  }
}
```

Thank you for your help.

**Comment by igorkosta** [comment]
Hello @vlucas,

wouldn't it make sense to merge the PR 186 (https://github.com/vlucas/frisby/pull/186) done by @imranolas.

Cheers
Igor

**Comment by bergeroy** [comment]
+1
I've been waiting for that feature to be added to Frisby.  Currently, there is no way to validate JSON if the schemas contain external references.

Thanks

**Comment by vlucas** [comment]
I would prefer to solve this with a replacement JSON validation library that handles this on its own rather than expanding Frisby's APi footprint with something like #186.

**Comment by nickveenhof** [comment]
https://github.com/vlucas/frisby/pull/257 Added a new approach to this without needed the global scope. Please review. Tests were also added.

**Comment by vlucas** [comment]
Closing, as this applies to v0.x. I would like a way to do this in v2, but currently this is not supported.
