### ISSUE TITLE
Error: Expected 'undefined' to be type 'object' for comparison

### ISSUE THREAD

**Issue by Gaurang033** [vlucas/frisby#101]
Hi, 

I was trying a simple test case, however getting error while running it, the site sends the json response however it seems like frisby is not able to identify it. 

Following is the code i am using

var frisby = require('frisby');

frisby.create('Get host informations')
  .get('http://freegeoip.net/json/yahoo.com')
  .expectStatus(200)
  .expectHeaderContains('content-type', 'application/json')
  .inspectJSON()
  .expectJSON('0',{
        country_code: 'US',
        country_name: 'United States',
        region_code: 'CA',
        region_name: 'California',
        city: 'Sunnyvale'
        }
    )
 .toss();

**Comment by m0sk1t** [comment]
I have the same error, but i'm don't place '0' in expectJSON function.
My query:
frisby.create('GET '+method+' method test')
                .get('http://localhost:3000/search?ric=ric224&client=русь')
                .addHeader('Cookie', test_cookie)
                .expectStatus(200)
.expectJSON([{"Ид":4534,"КлассИд":534534,"Имя":"456456453","СостояниеОбслуживания":"453","Руководитель":[{"Ид":3123,"КлассИд":123132,"Фамилия":"123","Имя":"456","Отчество":"789","Должность":"321"}]}]).toss();

**Comment by Verkalets** [comment]
Agree with @Gaurang033 
@vlucas You made a really cool tool, but if you provide a bit more of documentation, it would awesome.

**Comment by michaelezehi** [comment]
I had the same issue and took off the first parameter and it worked ( .expectJSONTypes('args', { },). This was total fluke as it wasn't documented on the official frisby site.

**Comment by ctadeu** [comment]
Since this is a OS tool anyone can update the documentation and submit for review
