### ISSUE TITLE
Test Suite definition like Jasmine

### ISSUE THREAD

**Issue by ArkeologeN** [vlucas/frisby#103]
Hi,

I'm fan of `jasmine-node` and used it frequently. I came around to `frisby` to test my newly written REST API. I'm trying to figure out any `grouping` method like `jasmine`. We used to write something like this in `jasmine`:

``` javascript
describe("/users Endpoint Test Suite", function() {
   it("should login the user", function(done) {
               ....
   });
});
```

Here, we're using `describe` to group all `it`. Is it possible to do something similar with `frisby`?

**Comment by vlucas** [comment]
Frisby v2 does this since it doesn't call any of the Jasmine functions directly.
