### ISSUE TITLE
Auto generating api reference from source code comments

### ISSUE THREAD

**Issue by marcin-wosinek** [vlucas/frisby#105]
I've noticed that documentation page is missing few functions; while source code is quite nice documented in comments. How about generating some api summary from source code comments? If we replace current comments with **jsdoc** block we can use some standard tool to generate pretty nice api summary. Or even [this](https://github.com/oncletom/grunt-jsdoc-md) to generate md files for **frisby-site**.

**Comment by vlucas** [comment]
This is a good idea we should look into. Is there a way you can auto-generate some docs so I can see how they look first?

**Comment by vlucas** [comment]
Closing this due to age.
