### ISSUE TITLE
Creating tests in afterJSON mutes verbose

### ISSUE THREAD

**Issue by chrisjenx** [vlucas/frisby#11]
This is your code, but I am doing something similar (logging in then using the token etc for the rest of the logged in tests).

``` javascript

// 'afterJSON' automatically parses response body as JSON and passes it as an argument
  .afterJSON(function(user) {
    // You can use any normal jasmine-style assertions here
    expect(1+1).toEqual(2);

    // Use data from previous result in next test
    frisby.create('Update user')
      .put(URL_AUTH + '/users/' + user.id + '.json', {tags: ['jasmine', 'bdd']})
      .expectStatus(200)
    .toss();
  })
.toss();
```

This will execute the test correctly, but I only know the test has run because of the finished count.

Note sure why its not verbose once its called in the after command?

**Comment by deem0n** [comment]
As of March 2015 frisby still have problems with console titles for frisby.create('') calls nested in the after().
You will see top level title and all nested titles will be missed 
I use code like this:

```
 frisby.create('Login')
  .get('auth')
  .afterJSON(function(user) {
    frisby.create('Update user')
      .put(URL_AUTH + '/users/' + user.id + '.json', {tags: ['jasmine', 'bdd']})
      .expectStatus(200)
    .toss();
  })
.toss();
```
and see this when I run tests:
`jasmine-node --verbose 0100-datasets-spec.js` 
```
Frisby Test: Login - 267 ms
    
	[ POST ***URL*** ] - 267 ms
```
information for 'Update user' tests is missed in output. Any idea how to fix it ?

**Comment by ymkjp** [comment]
I have same problem to https://github.com/vlucas/frisby/issues/11#issuecomment-88393015, in nested `frisby.create` with `.after`.

Not only --verbose option, `inspectOnFailure` option also outputs blank.

```
POST http://example.com/foo has FAILED with the following response:
```
I wonder jasmine-node cause these problems, however it's nice if fixed within frisby implementation.

**Comment by wp-sobj** [comment]
So what's going on with this? I'm still experiencing the issue.

**Comment by vlucas** [comment]
All of this is fixed in v2. Please update to v2 to fix this. There is no way to fix this in any previous version of Frisby before v2.x. See #316 for more details on why.
