### ISSUE TITLE
File post does not work

### ISSUE THREAD

**Issue by gienec** [vlucas/frisby#112]
Hi,
it seems file post doesn't work anymore.
I'm talking about this example https://github.com/kreutter/frisby/blob/master/examples/httpbin_multipart_spec.js
I need to test file upload via REST POST call.
Could you help me with that?

**Comment by rdohms** [comment]
I am having issues with this, is there a known cause?

**Comment by vlucas** [comment]
Frisby v2 supports this via the fetch() API. A new example needs to be created, but it does work.
