### ISSUE TITLE
Keep Alive support

### ISSUE THREAD

**Issue by apmanol** [vlucas/frisby#113]
Hello all,
I would like to ask if the frisby js supports the keep alive feature. Meaning, if it is possible to keep the same tcp connection for execution of multiple tests.

thanks a lot!

**Comment by vlucas** [comment]
That would be an interesting feature to add. If you know how to achieve this with the `fetch()` API, I can pull it into v2.

Closing this issue due to the huge time gap, but feel free to re-open this for v2 if you are using it.
