### ISSUE TITLE
[TypeError: Cannot read property 'prototype' of undefined]

### ISSUE THREAD

**Issue by faizulhaque** [vlucas/frisby#114]
Error
[TypeError: Cannot read property 'prototype' of undefined]

Getting this error on line: 
jasmine.Matchers.prototype.toMatchOrBeNull = function(expected) {
......
};

Also 
## runs(function() {

});
waitsFor(function(){
});

is showing undefined. help i guess i missing some thing, 

already using jasmind-node@2 but in frisby.js file there is not reference of it.

these are the required in frisbyjs file

var qs = require('qs')
  ,  util = require('util')
  , request = require('request')
  , _ = require('underscore')
  , bignumJSON = require('json-bignum')
  , JSONSchemaValidator = require('jsonschema').Validator
  , stackTrace = require('stack-trace')
  , fs = require('fs')
  , fspath = require('path');

**Comment by dev-zero** [comment]
frisbyjs-0.8.5 is currently broken, is that correct?
When I try its own tests (with nodejs-0.10 or 0.12) I get:
```
/tmp $ npm install frisby
frisby@0.8.5 node_modules/frisby
├── stack-trace@0.0.9
├── mock-request@0.1.2
├── jsonschema@1.0.0
├── underscore@1.6.0
├── qs@1.2.2
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.6.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.9, http-signature@0.10.1, tough-cookie@0.12.1, bl@0.9.4, hawk@2.3.1)
└── nock@1.1.0 (propagate@0.3.1, debug@1.0.4, mkdirp@0.5.0, lodash@2.4.1, chai@1.10.0)
/tmp $ cd node_modules/frisby/
/tmp/node_modules/frisby $ npm install minijasminenode2
minijasminenode2@1.0.0 node_modules/minijasminenode2
└── jasmine-core@2.0.0
/tmp/node_modules/frisby $ node_modules/.bin/minijasminenode2 spec/frisby_global_spec.js 
F

Failures: 
1) Exception loading: /tmp/node_modules/frisby/spec/frisby_global_spec.js Error
1.1) TypeError: Cannot read property 'prototype' of undefined
    TypeError: Cannot read property 'prototype' of undefined
        at Object.<anonymous> (/tmp/node_modules/frisby/lib/frisby.js:1125:17)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/tmp/node_modules/frisby/spec/frisby_global_spec.js:1:76)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

1 spec, 1 failure
Finished in 0.011 seconds
```

**Comment by vlucas** [comment]
No, that is not correct. The current version still uses Jasmine 1.0 since 2.0 is still not out of beta.

**Comment by dev-zero** [comment]
ah, ok. I was hitting the `"Cannot call method 'replace' of null"` issue with 0.8.5 and then tried to run the specs with the minijasminenode2 specified in the devDeps.

**Comment by dev-zero** [comment]
What is the reason for not using [jasmine]( http://jasmine.github.io/2.1/node.html) directly?

**Comment by devourment77** [comment]
I was also having issues trying to get a gulp task using jasmine-npm + frisbyjs to work.  I am using jasmine 2.3.x (using some 2.x features on front end unit tests).  Is it possible to have have frisbyjs work with raw jasmine or is jasmine 1x / jasmine-node a requirement?

**Comment by Gbeschbacher** [comment]
Using frisby.js too and both (this version (@vlucas) and the version mentioned above (@m0x72)) isn't working. I either `[TypeError: Cannot read property 'prototype' of undefined]` or ``[TypeError: undefined is not a function]`.

At the moment i upgraded jasmine-node to jasmine-node#Jasmine2.0 version because i want some features out of there and frisby.js doesn't play with it nicely yet. Is there any way to release the Jasmine 2.0 support for frisby you mentioned above (@vlucas)?.

**Comment by dgreene1** [comment]
Any updates on this?

Our team is try to decide between Frisby and SuperTest and would rather use Frisby. But without jasmine 2.0, we would have to rewrite all of our unit tests.

**Comment by vlucas** [comment]
Frisby v2 will fix this. See #316 for more details.

**Comment by dgreene1** [comment]
Thank you so much for the quick response. I look forward to working with  Frisby v2. Good news is that I guess you can close this issues as "won't fix" right?

**Comment by vlucas** [comment]
Fixed in v2. Please update your tests to use it.
