### ISSUE TITLE
Basic access authentication in last version of frisby does not work

### ISSUE THREAD

**Issue by ApelSYN** [vlucas/frisby#117]
Hello, Vance!

I updated frisby to last release. I stopped working tests that use basic authentication on an POST query.

Temporarily all rolled back to version 7.xx. Everything works fine

Example of test:

```
frisby.create("Check user auth")
    .timeout(baseTimeout)
    .auth(baseAuth.user, baseAuth.passwd)
    .post(someUrl, somePamamsArray).expectStatus(200)
    .toss()
```

**Comment by udaykiranvv** [comment]
Hi.. 
We are also facing same issue. Can you please let us know how to rolled back to 7.xx.

**Comment by ApelSYN** [comment]
We rolled back to 0.6.9. All work fine

**Comment by vlucas** [comment]
Ugh. I wonder if this is due to another change in the underlying request library. The automated tests did not show any issues though...

**Comment by udaykiranvv** [comment]
Hi vlucas,

Even after updated to 0.8.5 I am getting same issue, getting 404 for .post while using globalsetup for headers. please find the code below. Please help me to resolve this issue.

/**
 * frisby.js: Facebook usage example
 * (C) 2012, Vance Lucas
 */
var token;
var frisby = require('../lib/frisby');

/*To get OAuth Token sending the below API*/

frisby.create('openapi')
.post('https://xxxxxxx/services/access_token/v2',{
grant_type: "client_credentials",
client_id: "fb15fd72a2be493d852da92c21d71d04", 
client_secret: "3234aac5cd47410fa13f7ddfc14bf088"
})
.expectStatus(200) 
.expectJSONTypes({
access_token: String
})
.inspectBody()
.afterJSON(function(user) /*capturing the value in access_token from the above call reponse and sending in to the below headers*/
	{
frisby.globalSetup(
	{
  request: {
    headers:{'Accept':'application/json','Content-Type': 'application/json','Authorization': 'OAuth '+user.access_token}
    
           }
    }
)


 frisby.create('RealPickup For Posters')
.post('http://xxxxxx/retail/v1/realPickupTime',
{
   "project_id":"123",
   "cart_id":"555",
   "skus":[
      {
         "sku":"CommerceProduct_9018",
         "qty":"10"
      }
   ],
   "store_id":"1000013_03940",
   "retailer":"DUMMY"
},{json: true})
.inspectJSON()
.expectStatus(200)
.expectHeaderContains('Content-Type', 'application/json')
.expectJSONTypes('stores.?',
	   {
   storeId:String,
   timeZone:String,
   pickupDetails:Array,
	   phoneNumbers:Array,
	   addr:Object,


   }) 
.afterJSON(function(StoreObject)
	{
   expect(StoreObject.storesCount).toBeGreaterThan(0)
   }
     )
		 
.toss();

})
.toss();

Exception trace : 

 Message:
   Expected 404 to equal 200.
 Stacktrace:
   Error: Expected 404 to equal 200.
  at null.<anonymous> (C:\Users\vkvudathala\AppData\Roaming\npm
  at null.<anonymous> (C:\Users\vkvudathala\AppData\Roaming\npm
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

Note : Same is mentioned in the below issue.
https://github.com/vlucas/frisby/issues/138

Thanks in advance,
Uday

**Comment by silentHoo** [comment]
Same problem here. I tried this with

    frisby.create('Authenticate user')
      .post(URL + '/frontend/session', {
        username: 'user1',
        password: 'user1'
      }, {
        json: false,
        headers: {
          'X-Session-Token': 'my-token'
      }
    })
    .auth('user', 'pass')
    .expectStatus(200)
    .afterJSON(function(json) {
      // extract session token from response
      frisby.globalSetup({ // globalSetup is for ALL requests
        request: {
          headers: {
            // ... setup headers
          }
        }
      });
    })
    .toss();

**Comment by vlucas** [comment]
Please try this in v2. This should no longer be an issue.
