### ISSUE TITLE
Add support for negative tests

### ISSUE THREAD

**Issue by cristim** [vlucas/frisby#118]
I need to add a `Cache-Control` header, which should contain `no-store` only for URLs matching `/api`.

On the same server I also serve some static files, and for those I would like to be able to check if that header is missing, imagine a test like:

```
frisby.create('CSS files should be cached')
.get("/style.css", {followRedirect: false})
.expectStatus(200)
.expectHeaderDoesNotContain('Cache-Control', 'no-store')
.toss();
```

**Comment by vlucas** [comment]
This works much better now in v2. Please update and use `expectNot` instead of `expect`.
