### ISSUE TITLE
Parallel test execution

### ISSUE THREAD

**Issue by FlxRobin** [vlucas/frisby#119]
Hi there,

I'm not entirely sure whether this is something frisby can cover, or whether this is more a jasmine issue.

Would it be possible to run async tests in parallel? In case this is more jasmine related, do you know how to resolve this?

**Comment by poohsen** [comment]
weird. came here to check if I can do tests _sequentially_, 'cause my scenario kept failing until I put my cleanup step into an `after()` instead of just at the end of the file. Does that mean you managed to build this into 0.8.5 or am I just confused?

**Comment by vlucas** [comment]
Jasmine does not run tests themselves in parallel. This means that the tests run one by one, which can take a long time if you have a large API or a lot of tests.

In your case, there is a difference between tests running synchronously, and tests running sequentially in the same order as your code. This is why you have to use the `after` and `afterJSON` methods.

**Comment by vlucas** [comment]
This is fixed in v2, and by using Jest as the test runner.
