### ISSUE TITLE
Deep cloning turns nulls into empty objects

### ISSUE THREAD

**Issue by dhavelin** [vlucas/frisby#121]
The cloneObject() function in frisby.js contains this test:

```
if (typeof(obj[i]) == "object")
```

Since `typeof(null)` is `'object'` in JavaScript, this causes nulls to be processed as nested objects and converted to `{}`.

The impact for me is that I can't unset the proxy in the global setup:

```
frisby.globalSetup({
    request: {
        proxy: null
    }
});
```

By the time the request module gets the parameter it has become `{}`.

(I note the dependency on underscore in frisby.js. You could drop in lodash as a replacement. That comes with a cloneDeep() function.)

**Comment by vlucas** [comment]
Fixed in v2, which uses lodash.
