### ISSUE TITLE
HTTP headers are made lower case

### ISSUE THREAD

**Issue by jpsav** [vlucas/frisby#122]
If custom headers are added to requests via globalSetup then they are converted to lower-case before being sent. This can result in servers not finding required headers.

**Comment by davidhopkins** [comment]
Been hit by this same issue. Frisby is clearly altering the headers here:
```javascript
144: var _gs = cloneObject(globalSetup());
145: // _gs may contain mixed-cased header names, the code expects lowercase however.
 ```

**Comment by slabko** [comment]
I'm also blocked by this issue. Any update on that?

**Comment by vlucas** [comment]
Same as #185. Closing duplicate.
