### ISSUE TITLE
{json:true} not respected for GET requests without data

### ISSUE THREAD

**Issue by singles** [vlucas/frisby#126]
It makes testing APIs which doesn't support `Content-Type: application/x-www-form-urlencoded` a little bit difficult.

Instead of:

``` javascript
get( 'http://api.example.com/resources/' )
```

you have to write 

``` javascript
.get( 'http://api.example.com/resources/', { 
    headers: { 
        "content-type": "application/json" 
    }
} )   
```

Reason for that is fact that `application/x-www-form-urlencoded` is default and before applying `{json: true}` changes, you're checking if [data is set](https://github.com/vlucas/frisby/blob/master/lib/frisby.js#L363) - while for GET request shouldn't be no data.

**Comment by vlucas** [comment]
This is fixed in v2. JSON is now always the default.
