### ISSUE TITLE
Running a frisby test from within a promise

### ISSUE THREAD

**Issue by dguerrier** [vlucas/frisby#127]
Is there anyway to get a frisby test to run if it's inside of a promise?  I'm using an API based on promises to make API calls to set up the data for tests.  If i were to use frisby's http calls it would pollute the test and require a ton of nested callbacks.  I would like to simply do something like this.

theAPIcall().then(function(data){
    frisby.create('Very useful for HTML, text, or raw output')
      .get('http://asciime.heroku.com/generate_ascii?s=Frisby.js')
        .inspectBody()
    .toss()
});

**Comment by bgdavidx** [comment]
I've created a fork that allows you to use Promises from within frisby. Check it out at https://github.com/bgdavidx/frisby

The API is the same; however you can use `.promisedToss()` to return a frisby promise. (Requires bluebird)

**Comment by oscartcy** [comment]
+1 for official support

**Comment by AndyWendt** [comment]
Here is a work around since it is based off of Jasmine and can use `done()`.

For example: 

```js
'use strict';

const frisby = require('frisby');
const api = require('./api-helpers');

// api.before returns a promise and is a local file which returns module exports
// describe() & it() are from Jasmine

describe('Products ', () => {
  it("retrieves the products collection", (done) => {
     api.before('Products', 'getCollection').then((seedData) => {
       frisby.create('Ensure products collection is correct ')
         .addHeaders(seedData.meta.headers)
         .get('http://yoursite.dev/api/products')
         .expectHeader('Content-Type', 'application/json')
         .expectStatus(200)
         .toss();
       done();
     });
  });
});

**Comment by vlucas** [comment]
Frisby v2.0 will fix this (see #316) since it uses promises internally. There is even a new API method that you can call to return the internal promise object from `fetch` called `promise()`.

**Comment by geolunalg** [comment]
any update on Frisby v2.0

**Comment by vlucas** [comment]
Frsiby v2.0 alpha is here and ready to use. It is now in the `master` branch, and can be installed and used via the instructions in the README.
