### ISSUE TITLE
handle Content-Disposition of multipart/form data

### ISSUE THREAD

**Issue by kareka** [vlucas/frisby#132]
am trying to test a service which does file upload .and below is the sample data captured by fiddler.how i can handle this in frisby

-----------------------------7de3c303c07ba
Content-Disposition: form-data; name="slow"

5000
-----------------------------7de3c303c07ba
Content-Disposition: form-data; name="file"; filename="short.csv"
Content-Type: application/vnd.ms-excel

user,password,post
xyz@xx.com,abcde,afdfd

-----------------------------7de3c303c07ba--

**Comment by vlucas** [comment]
Frisby v2 should handle file uploads much better now via the fetch() API.
