### ISSUE TITLE
I post JSON in private network ip and other port like 192.168.x.x:1234 or localhost:1234

### ISSUE THREAD

**Issue by ivanchiou** [vlucas/frisby#133]
HI, 
I post JSON to server in private network its ip and port like http://192.168.x.x:1234 or http://localhost:1234. The server return http status code 500 and get everythings except request content(JSON body) so I can't recognize what data the client sent to server. Otherwise server in public ip,  it works normally. Is some settings I miss in this case? Please help me to check below errors.

Frisby Test: xxxxxxxxxxxxxxxxxxxxxx
        [ POST http://xxx:xxxxxxxxxxxxx@localhost:1234/api/ ]
   Message:
     Expected 500 to equal 201.
   Stacktrace:
     Error: Expected 500 to equal 201.
    at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:485:42)
    at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:1066:43)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

**Comment by comscience15** [comment]
I too get the same error. The .inspectBody() produces the following

"Destination URL may be down or URL is invalid."



^ I got the same thing. So what is the solution for this. I think I need to change the port number from standard(8080) to be (8090). How to do it on Frisby???

**Comment by rdohms** [comment]
I'm getting this as well, what was the fix?

**Comment by vlucas** [comment]
Looks like it was a bad SSL cert. Can you try this with v2 and then re-open this issue if it still doesn't work? The fetch() API should be able to handle this.
