### ISSUE TITLE
Frisby fails to find valid node.js routes

### ISSUE THREAD

**Issue by velniukas** [vlucas/frisby#138]
I'm running a node.js server on localhost, and can access all the routes via curl or Postman, however Frisby (frisby@0.8.3) will intermittently fail to find any valid routes and fails immediately (I have set global timeout) with a 404 error
ie.

```
POST http://localhost:3000/api/oauth/token has FAILED with the following response:
{ json: false,
  uri: 'http://localhost:3000/api/oauth/token',
  body: 'grant_type=password&client_id=xxxxxx&client_secret=xxxxxxx&username=xxxxxxx&password=xxxxx',
  method: 'POST',
  headers:
   { 'cache-control': 'no-cache',
     'content-type': 'application/x-www-form-urlencoded' },
  inspectOnFailure: true,
  timeout: 30000 }

Frisby Test: OAuth2 login - 22 ms

    [ POST http://localhost:3000/api/oauth/token ] - 21 ms

Failures:

  1) Frisby Test: OAuth2 login
    [ POST http://localhost:3000/api/oauth/token ]
   Message:
     Expected 404 to equal 200.
   Stacktrace:
     Error: Expected 404 to equal 200.
    at null.<anonymous> (/dev/server/node_modules/frisby/lib/frisby.js:485:42)
    at null.<anonymous> (/dev/server/node_modules/frisby/lib/frisby.js:1066:43)
    at Timer.listOnTimeout (timers.js:133:15)
```

**Comment by udaykiranvv** [comment]
We are facing same issue. can some please help me to resolve this issue.

Failures:
1) Frisby Test: Storeavailability Call for 8x11 calendars(12 Months)walmart
      [ POST http://retail.sf-qa.com/retail/v1/supportedStores ]
 Message:
   Expected 404 to equal 200.
 Stacktrace:
   Error: Expected 404 to equal 200.
  at null.<anonymous> (C:\Users\vkvudathala\AppData\Roaming\npm\node_modules\frisby\lib\frisby.js:452:42)
  at null.<anonymous> (C:\Users\vkvudathala\AppData\Roaming\npm\node_modules\frisby\lib\frisby.js:1030:43)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by udaykiranvv** [comment]
It is working fine with .get and issue with .post only, can someone please help me to resolve this issue.

Thanks in advance,
Uday
