### ISSUE TITLE
Storing values in global variables

### ISSUE THREAD

**Issue by halluram** [vlucas/frisby#140]
I am a newbie to nodejs ,jasmine and frisby. I am trying to use this test our REST API's. I want to store the value of a response json element to a variable like below. 

var test;

frisby.create('Get Brightbit Facebook Page')
.get('https://graph.facebook.com/111848702235277')
.expectStatus(200)
.expectJSONTypes({
    id : String,
    likes : Number,
    is_published : Boolean
})
.expectJSONTypes('cover', {
    offset_x : Number,
    source : String
})
.expectJSON({
    id : "111848702235277",
    website : "http://brightb.it"
}).afterJSON(function (ret) {
    test = ret.founded;
    console.log(test);
})
.toss();
console.log(test);

It appears that the frisby test cases are executed after the second console.log is run and hence test variable is undefined. Any ideas on how to get this working?

Thanks
Naren

**Comment by Shafiul-Hasan-tareq** [comment]
Hi Lucas,
If i write some methods like frisby.global.setData('key',value) and frisby.global.getData('key') will you accept the pull request? Some time, i have seen that some guys needs this type of methods to share data across the test cases which is not in the same file or some other reasons.

**Comment by marcin-wosinek** [comment]
@Shafiul-Hasan-tareq it would be de facto global state. How about including some separate module that takes care of that?

**Comment by Shafiul-Hasan-tareq** [comment]
@marcin-wosinek , yeah it would be a good idea. Let me explore little bit more on that.

**Comment by jShelton1533** [comment]
@marcin-wosinek  @Shafiul-Hasan-tareq  @halluram  @cpanato  Did you all ever discover an answer for this problem?

**Comment by vlucas** [comment]
Frisby runs all HTTP requests async. This is core to the nature of how JavaScript itself works. What you are trying to do will never work, no matter how the variable gets set and then accessed.

You will only be able to access the variable in an `after` or `afterJSON` callback:

```javascript
var test;

frisby.create('Get Brightbit Facebook Page')
  .get('https://graph.facebook.com/111848702235277')
  .expectStatus(200)
  .expectJSONTypes({
    id : String,
    likes : Number,
    is_published : Boolean
  })
  .expectJSONTypes('cover', {
    offset_x : Number,
    source : String
  })
  .expectJSON({
    id : "111848702235277",
    website : "http://brightb.it"
  })
  .afterJSON(function (ret) {
    test = ret.founded;
    console.log(test);
  })
  .afterJSON(function (ret) {
    console.log(test);
  })
.toss();
```
