### ISSUE TITLE
Timeout does not report error properly

### ISSUE THREAD

**Issue by scheerer** [vlucas/frisby#141]
It seems when a timeout occurs Frisby creates a fake response object with a body, headers, and 500 response. It does not indicate this is the error during tests runs. Instead it throws the fake response to the asserts/expectations and therefore the reported errors are VERY misleading.

Example test:

``` javascript
        frisby.create('Do long POST that is slow and fires Frisby timeout')
            .post(someUrl, someJsonBody, {json: true})
            .expectStatus(200)
            .expectHeaderContains('content-type', 'application/json')
            .expectJSON('?', expected_json)
            .toss();
```

When this times out I get very misleading errors such as:

```
Expected 500 to equal 200.
```

and

```
Error: Header 'content-type' not present in HTTP response
```

Frisby should just report that a timeout occured, not a bogus 500 reponse object.

The problem seems to be in this section of code:

``` javascript
...
          waitsFor(function(){
            return self.currentRequestFinished;
          }, "HTTP Request timed out before completing", self._timeout);

          // Run Asserts
          runs(function() {
...
```

Why not just bail with a timeout error BEFORE running the assertions?

**Comment by ravirkkm** [comment]
Anyone solved the timeout issue ?

```JavaScript
   Stacktrace:
     Error: Expected 'undefined' to be type 'array' for comparison
    at _jsonContains (/usr/lib/node_modules/frisby/lib/frisby.js:1238:11)
    at jasmine.Matchers.toContainJson (/usr/lib/node_modules/frisby/lib/frisby.js:1186:12)
    at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:717:24)
    at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:1074:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by ddossot** [comment]
:+1:

**Comment by stefanmeschke** [comment]
:+1:

**Comment by rdohms** [comment]
:+1:

**Comment by snsparrish** [comment]
Was bit by this one today.  Spent a lot of time trying to find where my server was returning a 500 when the real issue was a simple timeout.  Please fix this.

**Comment by vlucas** [comment]
I think this has been fixed in v2. Please try it in v2 and re-open this issue if not.
