### ISSUE TITLE
How to pass variable in POST request

### ISSUE THREAD

**Issue by desaip01** [vlucas/frisby#143]
Hello,
var postJSON = [{'queryString': 'First String'},
                            {'queryString': 'Second String'}];

for(var i=0; i<postJSON.length; i++) {
            var obj = postJSON[i];
            frisby.create('Execute Query to verify the Query Results')
                .post(serverName + port + runQuery, {
--> How can I pass a variable --> obj.queryString
                })
                .expectStatus(200)
                .expectHeader('Content-Type', 'application/json')
                .inspectJSON()
                .toss();
        }

**Comment by bkhurshi** [comment]
Is this a work around or the official solution? I think #167 fixes this bug.

**Comment by dnascimento** [comment]
For sake of simplicity, we should create a .postJson(url, data) alias to

```javascript
.post(url, data, 
    {json: true} ,
   { headers: { 'Content-Type': 'application/json'}}
)
```

**Comment by andrepm06** [comment]
How i can pick an value of a json field and use it in a post?

for example:

    .inspectJSON()
			    .afterJSON(function (res) {
				    var id = res.ID;
				    frisby.create('Alarm')
					    .post('http://mid.dev.psafe.com/My.API/APIAdmin.svc/SendMessageToDevice',
						    {"action":"device_alarm",
						    "deviceID":res.ID,
						    "msg":null},
						    {json:true})
					    .expectStatus(200)
				    .toss();
			})
