### ISSUE TITLE
Reusing frisby test against multiple urls

### ISSUE THREAD

**Issue by bapti** [vlucas/frisby#144]
Hi,

I'm interested in using Frisby along with gulp in the following kind of fashion

```
var frisby, frisbyRunner;

frisby = require('frisby');

module.exports = frisbyRunner = (function() {
  function frisbyRunner(url) {
    frisby.create('Test the website').get("" + url + "/home").expectStatus(200).toss();
  }

  return frisbyRunner;

})();
```

```
gulp.task('smoketest', function (taskCallback) {

  var test = new frisbyRunner("http://smoketest.server1.com")
  ...
  ...
 // run all tests in parallel

});

```

I have 12 live servers that I want to run the test against before putting them live.  I'm not sure if I can use gulp-jasmine to execute the tests

Thanks for any help!
Neil

**Comment by adrianblynch** [comment]
Did you find a solution?

You could pull the URLs out into Gulp and run the tests fully on each server rather than each test on each server.

**Comment by vlucas** [comment]
You can do this now in v2 by returning the Frisby spec object from a function. Please try this in v2.
