### ISSUE TITLE
Document methods for working with headers

### ISSUE THREAD

**Issue by jwarkentin** [vlucas/frisby#146]
The documenation at [frisbyjs.com](http://frisbyjs.com/docs/api/) doesn't make any mention of the `addHeader`/`addHeaders` and `removeHeader` functions to modify headers per request. I ended up having to dig through the source to figure it out (I thought it was an oversight and I was going to have to find some hack or use [supertest](https://github.com/visionmedia/supertest) instead). Any mention of the existence of these functions is sufficient but there should be something.

**Comment by judges** [comment]
+1

**Comment by vlucas** [comment]
This is done and on the website now. Thanks!
