### ISSUE TITLE
Testing options request

### ISSUE THREAD

**Issue by hytvi** [vlucas/frisby#147]
Hi,

Since a short time I am using frisby for testing my API. It's a really cool tool to use, but I am missing tests for options, or I am looking wrong. When I try to run the test using .options, I get the following error:

[TypeError: Object #<Frisby> has no method 'options']

Is there any other way to run the HTTP OPTIONS method?

Thanks in advance

**Comment by adrianblynch** [comment]
There is mention of it in the code:

https://github.com/vlucas/frisby/blob/master/lib/frisby.js#L326

**Comment by hytvi** [comment]
Thanks, looks like it was created in December :)
