### ISSUE TITLE
Gzip / Chunked encoding problem

### ISSUE THREAD

**Issue by marcelinhov2** [vlucas/frisby#150]
I'm trying to generate tests in a API that returns me the data Gziped and with the transfer-encoding: chunked.

The problem is, that the response never come as a JSON:
l�Kn� ��=���� ��U���.����*k��

���z�.z�\��`U�"V|�0?�B"c��&"O$z{�'ԣ1�E?��!�q@_�y_�_6:q<�+�%�����[�Nq�?A
�Q��2�r%o�U{�,���E��1��&^�y7�`v��h2'��F��G��                          ��|�G_mF�\�"dE�~�Oϔ�(}Ӑ��i��Lp��+\h@��:��$
                                           ��zЪٜӁ0�d����HJ�*�j��it�Z��?_�U�ѪJ�{������4������G(H�CK=C��b%���
                                                                                                          WACB�17�(39Q?81?> �4'_  �����OŃ�((�w
R����C����

Does anyone had the same trouble already?

Thanks ;)

**Comment by djangosdk** [comment]
https://github.com/vlucas/frisby/issues/304

**Comment by vlucas** [comment]
Duplicate.
