### ISSUE TITLE
How repeat a same request

### ISSUE THREAD

**Issue by cpanato** [vlucas/frisby#153]
Hello

I need test one service which is a upload process and one request is to get the progress, how I can repeat one request based on a response.

like:
I upload a file and send a request to /progress and it return to me: "running", and I need wait until get "done" there is a way to re-run the same request until we get the done?

thanks!

**Comment by vlucas** [comment]
With v2, you can put the spec in a function, then just call the function again.

**Comment by pramodmaurya** [comment]
Thanks a lot...!
