### ISSUE TITLE
Running async code before a frisby test 

### ISSUE THREAD

**Issue by surjikal** [vlucas/frisby#154]
I want to run some async cleanup code before running a particular frisby test. I tried a bunch of things but nothing really works.

Does anyone have any ideas?

I'm trying to do something like this:

``` javascript
db.delete('user-12345', function() {
  frisby.create('Should not find user that doesnt exist.')
  .get('/users/12345')
  .expectStatus(404)
  .toss();
});
```

**Comment by vlucas** [comment]
Now that you can use straight Jasmine code, you can use `beforeEach`, `afterEach`, with a "done" callback argument etc. to do this.
