### ISSUE TITLE
Path does not support keys with dots `.`

### ISSUE THREAD

**Issue by taktran** [vlucas/frisby#156]
Using `.` in `expectJSONTypes` doesn't work if `.` is in the key (https://github.com/vlucas/frisby/blob/master/lib%2Ffrisby.js#L58)

Maybe there could be a config object that uses another character to split by

**Comment by vlucas** [comment]
The dot character is assumed to be a path in Frisby, just like with lodash, etc. Allowing keys to have dots would likely require some special case coding, and a good bit of effort. I am open to adding it into v2 if you want to put in the effort to submit a PR for it, but I can't put forth the effort to make it happen right now.
