### ISSUE TITLE
Send JSON or raw body

### ISSUE THREAD

**Issue by cklckl48** [vlucas/frisby#166]
I'm trying to test a POST where the body type as follow:
{ "params":
{ "params1": 1,
"params2": 2}}

Can you give me any idea how to test it?  thank you

**Comment by bkhurshi** [comment]
#171 seems to be a similar issue. #167 seems to have the fix, but the issue was closed.

**Comment by vlucas** [comment]
This should be fixed in v0.8.5. Please update to v2 though and see if you still have this issue.
