### ISSUE TITLE
How retry the same request while waiting for some status change ?

### ISSUE THREAD

**Issue by cpanato** [vlucas/frisby#169]
Hello

I have a endpoint to check some progress and I would like to wait for a request change from running to complete.
I can use wait for some seconds, but what happen if for some reason it take more time than expected?
There is a way to retry the request until it change the state?

thanks

**Comment by vlucas** [comment]
There is no way to do this in v1, but there might be a way in v2.

**Comment by pramodmaurya** [comment]
Thanks!
