### ISSUE TITLE
Need to store value in global variable from ".afterJSON({ })" and want to pass this value as condition to the while loop

### ISSUE THREAD

**Issue by pramodmaurya** [vlucas/frisby#170]
Hello,
I am stuck in Frisby Scripting, Please look into .afterJSON({}):
while (useState=='PENDING') {
frisby.create('Validate data')
                                            .get(http://id:8080/get)
                                            .addHeader('Content-Type', 'application/json')
 .expectStatus(200)
 .afterJSON(function(res) {
                                                useState = res.query.results.state;
console.log("Run while loop till status is PENDING and terminate loop when got status as COMPLETE:"+useState);
})
.toss();
}
Here I have initialized the variable 'useState' on the top of the frisby file, and I am doing some work in while loop, and in .afterJSON I am picking the some current status of my response, on the basis of this response I would like to continue/terminate the while loop... but the variable 'useState' is not passing the value to the while loop so while loop not receiving any current condition and it is running till infinite.
I need help on this kindly tell me the suitable solution so that I can start my scripting......
Thanks.

**Comment by guy16510** [comment]
I ended up creating a 2nd js app called (tokenGenerator.js), that uses the "request" library. From there I used module.exports, and exported the values I needed. 

On my testRunner app using Frisby I used the required(tokenGenerator.js), and pulled them in that way.

**Comment by pramodmaurya** [comment]
Thanks a lot..!
