### ISSUE TITLE
Posting json as raw body not as string

### ISSUE THREAD

**Issue by AnirudhaAgashe** [vlucas/frisby#171]
I am using the code listed under "Send Raw JSON or POST Body" of docs to send json to my web services. 
The body dump of what the service expects

' { \"email\":\"user@u.com\", \"pass\":\"user\" } '

What I get

' "{\"email\":\"user@u.com\",\"pass\":\"user\"}" '
I have set { json:true } in the post request.

**Comment by bkhurshi** [comment]
#167 may be the solution to this.
