### ISSUE TITLE
POST JSON with extra (") at start and end

### ISSUE THREAD

**Issue by HugoSousa** [vlucas/frisby#172]
So, I'm trying to test a POST request like this:

```
frisby.create('POST login details')
  .post(TEST + '/login',
  {
    username: "aaa",
    password: "9834876dcfb05cb167a5c24953eba58c4ac89b1adf57f28f2f9d09af107ee8f0"
  },
  { json: true },
  { headers: { 'Content-Type': 'application/json' }})
  .inspectJSON()
.toss();
```
But, instead of a response 200, I'm getting a 401, because JSON isn't parsed correctly. I tried on Postman and it behaves correctly, returning 200, and after printing the body on the server it is like this (just an example, not the full body):

    { "username": "aaa" }

But with frisby it is: 

    "{ \"username\": \"aaa\" }"

I think the quotation marks at the start and the end of the body are the problem, and server can't parse the JSON correctly. Am I doing something wrong?

**Comment by vlucas** [comment]
Update to Frisby v0.8.5 - this is resolved.

**Comment by vimukthi101** [comment]
getting the same issue with "version": "2.0.16" when sending the post request. Request is assigned to a variable and the variable is set in the frisby post command.

get the request : 

var contents = fs.readFileSync(conf.tempFile, 'utf8').split('\n');
  for(var i=0; i < contents.length - 1; i++){
    var records = contents[i].split('|');
    run_test(records[0],records[1],records.slice(2),i+1);
  }

send the request : 

var response = frisby
        .post(conf.url,requestToFire)
        .catch(err => {
          logger.error(err);
        })
        .expect('status', 200)
        .expect('header', 'Content-Type', 'application/json')
        .done();

sending request taken from pcap : 

"{\"applicationId\":\"APP_000409\",\"password\":\"eca5f1be454dc6744524b89010b40b5b\",\"message\":\"hello world\",\"destinationAddresses\":[\"tel:AZ1101HXstW4OYuw4QQfODWKWPzL7dqtj49mywemJ6F5Mw+Np3WrFV6euLMjSgGx4hsQX6LQ0irL74IR673S0cNWWJA==\"],\"deliveryStatusRequest\":\"0\"}"

**Comment by H1Gdev** [comment]
@vimukthi101 

I think requestToFire is string.

How about this ?
```js
.post(conf.url,JSON.parse(requestToFire))
```

**Comment by vimukthi101** [comment]
yes I got the issue resolved by using the above (Y)
