### ISSUE TITLE
Would you accept helper methods for testing redirects?

### ISSUE THREAD

**Issue by tim-massey** [vlucas/frisby#178]
Heya,

I am using frisby for some functional testing of a site and want to add some helper methods for testing redirects. Would you be interested in accepting a PR with that?

Methods like `expectUrlPath(path)` or `expectUrlPathContains(pattern)` would be added.

**Comment by vlucas** [comment]
I would accept them, but you may consider a rename, something like:

`expectRedirectUrl(path)` or `expectRedirectUrlContains(pattern)`

**Comment by tim-massey** [comment]
Thanks for getting back to me, I'll use those names when I get to it.
