### ISSUE TITLE
Ability to inspect request

### ISSUE THREAD

**Issue by adrianblynch** [vlucas/frisby#182]
I'm looking to debug a request but I can't see a native way to do it in frisby.

Is there a way or a work around?

**Comment by JoyShafer** [comment]
If I understand what you're looking for, this may work for you. 
I used Charles proxy and simply added this at the top of my code:

var globalTunnel = require('global-tunnel'); //for proxy

 // This runs all requests through your proxy for debugging. 
 globalTunnel.initialize({
 host: '127.0.0.1',
 port: 8888
 });

**Comment by MarkHerhold** [comment]
Frisby has `inspectRequest` and `inspectResponse` methods. Take a look at the source and `Ctrl + F "Debugging helper"`.

**Comment by vlucas** [comment]
Methods for this are already present in frisby.
