### ISSUE TITLE
Frisby API references non-existing expectJSONContains

### ISSUE THREAD

**Issue by bkhurshi** [vlucas/frisby#183]
On http://frisbyjs.com/docs/api/, under "Using Paths with expectJSON and expectJSONTypes" under "Testing Arrays of Objects", expectJSONContains is mentioned which is not recognized by frisby currently.

**Comment by testtolearn1** [comment]
Able to accees only expectJSON

**Comment by vlucas** [comment]
This was fixed a while ago in v1.
