### ISSUE TITLE
expectJSON containing unordered list

### ISSUE THREAD

**Issue by bkhurshi** [vlucas/frisby#184]
Suppose the following JSON is expected as part of a Frisby test:

```
{
    array: ["1", "2", "3"]
}
```

The array of strings may return in any order, say `["3", "1", "2"]`.

How can I expect the above defined array without expecting an order?

I have tried

```
.expectJSON('array.?', "1")
.expectJSON('array.?', "2")
.expectJSON('array.?', "3")
```

but this is not valid syntax and the following error occurs:

```
 TypeError: Expected valid JavaScript object to be given, got undefined
```

**Comment by adrianblynch** [comment]
Could you drop back to using Jasmine for the check?

**Comment by bkhurshi** [comment]
How would that work? inspectJSON() and assert on it?

**Comment by vlucas** [comment]
You should be able to do this in v2. v0.x did not support basic scalar types (it should have).

`.expect('json', 'array.?', 3)`
