### ISSUE TITLE
How to test following POST request with Frisby.js

### ISSUE THREAD

**Issue by nirjashah** [vlucas/frisby#190]
POST request: 
https://qa.qbo.intuit.com/qbo1/rest/login/v2

BODY: 
![screen shot 2015-01-24 at 11 13 34 pm](https://cloud.githubusercontent.com/assets/4770323/5890731/a84120c0-a41e-11e4-93e2-37bb5542a5ce.png)

HEADERS:
content-type: application/xml

![screen shot 2015-01-22 at 2 53 08 pm](https://cloud.githubusercontent.com/assets/4770323/5890699/4a89cc62-a41d-11e4-9ae3-266dd76a21fe.png)

**Comment by ctadeu** [comment]
your server returned 500 :)

and this is not a REST standard

**Comment by sharadJay** [comment]
Hi,
were you able to post xml ? Any work around that you used ?

**Comment by vlucas** [comment]
You can use `expect('bodyContains', '<whatever>')`, but Frisby was not really designed for XML based APIs.
