### ISSUE TITLE
Frisby - POST- Error parsing JSON + Error: DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by abcdefghigk** [vlucas/frisby#194]
/***************  code *******************************/
var frisby = require('frisby');
var  endpoint = https://xxxxx.com/yyy';
var post_data = {
       "name":"test1",
};
frisby.create('Create one domain: test1')
    .post(endpoint,
           post_data,
           { json: true })
    .inspectJSON()
    .expectStatus(200)
.toss();

/************ Error message *****************/
Error: Error parsing JSON string: Unexpected token D
  Given: Destination URL may be down or URL is invalid,  
              Error: DEPTH_ZERO_SELF_SIGNED_CERT

/****************** More information *************/
frisby version is 0.8.5

/******************* Question/Help ****************/
Who can help me? Thanks in advance

**Comment by adrianblynch** [comment]
Have a read through this issue:

https://github.com/request/request/issues/418

**Comment by abcdefghigk** [comment]
Great! It works for me (process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" ). Thank you very much.
