### ISSUE TITLE
Test POST with Content-Type: multipart/form-data

### ISSUE THREAD

**Issue by Dharmoslap** [vlucas/frisby#195]
Would be good, if we could test uploading files with frisby.
Eg. sending POST with image file.

**Comment by yong362** [comment]
var path = require('path');
var FormData = require('form-data');
var logoPath = path.resolve(__dirname, '../spec/test.png');
var form = new FormData();
form.append('file_1', fs.createReadStream(logoPath), {
    knownLength: fs.statSync(logoPath).size // we need to set the knownLength so we can call  form.getLengthSync()
});
 frisby.create('Title')
        .post(URL" , form, {
            json: false,
            headers: {
                'content-type': 'multipart/form-data; boundary=' + form.getBoundary(),
                'content-length': form.getLengthSync()
            }
        })
        .expectStatus(200)
        .toss()
Hope that helps :)

**Comment by kannach** [comment]
this sstill send the content type as application/x-www-form-urlencoded

**Comment by SirNexus** [comment]
FYI for v2 I'm using this snippet which works: 

```
var imagePath = path.resolve(__dirname, 'logo.jpg');
var form = frisby.formData();

form.append('image', fs.createReadStream(imagePath), {
    knownLength: fs.statSync(imagePath).size
});

// send a post request to create the image
frisby // Post image
    .setup({
        request: {
            headers: {
                'content-type': 'multipart/form-data; boundary=' + form.getBoundary(),
                'content-length': form.getLengthSync()
            }
        }
    })
    .post('https://localhost/image', {
        body: form
    })
    .expect('status', 200)
```
