### ISSUE TITLE
Frisby - GET - verify one of the returned data

### ISSUE THREAD

**Issue by abcdefghigk** [vlucas/frisby#198]
/****************** JSON rawData *****************/
{
"status": "200 OK",
"list" :[{"user": "Jack:}, {"user": "Tom"}, {"user": "Tim"}]
}

/***************** Question ************************/
After get, I want to verify {"user": "Tim"} is included in the returned data. 
How to do that? Thanks in advance

**Comment by vlucas** [comment]
You can use the question mark path syntax to achieve this - it tests for the presence of a single item in an array:

```javascript
frisby.create('test toss')
  .get('http://someurl.com/my.json')
  .expectJSON('list.?', {"user": "Tim"})
.toss();
```
