### ISSUE TITLE
Code coverage using Frisby

### ISSUE THREAD

**Issue by nirjashah** [vlucas/frisby#201]
Is it possible to generate code coverage using Frisby?
I tried to generate code coverage for my Frisby tests using Istanbul but it does not generate any code coverage against the source files.

I tried to generate coverage using $istanbul cover tests/dtx/qa/fi_search_qa_spec.js.
However no coverage is generated against source files. Even no instrumentation seems to happen. 

![screen shot 2015-02-20 at 11 29 59 am](https://cloud.githubusercontent.com/assets/4770323/6307816/e22c6788-b8f3-11e4-8a49-9fdfaa0e1ec2.png)

**Comment by adrianblynch** [comment]
Aren't the instrumented files needed first. Are you setting Istanbul up correctly? Make sure your Istanbul usage is correct before pointing it towards your Frisby tests.

**Comment by b1rd** [comment]
With jasmine-node istanbul works perfectly, but not with frisby. It doesn't generate any reports at all.  I've found similar issues on stackoverflow, but no solutions to this problem. 
Would be nice to hear from everyone, who encountered this issue and already solved it

**Comment by fatmatto** [comment]
Any development regarding istanbul and frisby?

**Comment by vlucas** [comment]
I think Istanbul works based on actual method calls, and since Frisby hits the external API, I am not sure how the code coverage would be tracked.

**Comment by vlucas** [comment]
I am not sure how this is going to ever work with Frisby, and is currently not a focus. I would however welcome and encourage any contributions towards this goal for v2.
