### ISSUE TITLE
Limit default Content-Type to PUT & POST requests

### ISSUE THREAD

**Issue by marcin-wosinek** [vlucas/frisby#204]
default **Content-Type** header at request should be only set for PUT & POST. It doesn't make sense for other requests, and some oversensitive REST apis fails with that header.

**Comment by pasindud** [comment]
HTTP spec rfc2626 'Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".' 

There may by be many interpretations of this.
I think default Content-Type can be in any request that has a entity-body

**Comment by marcin-wosinek** [comment]
Thanks for the input; this will make more sense:
```
if (hasBody & lackContentType) {
  setsDefaultContentType();
}
```

**Comment by pasindud** [comment]
:+1:
