### ISSUE TITLE
setting authorization header in request

### ISSUE THREAD

**Issue by jamescarlyle** [vlucas/frisby#205]
There seems to be a difference in behaviour when setting request headers via 2 different ways

frisby.create('Test with explicit addHeader call')
    .delete('http://httpbin.org/delete')
    .addHeader('Authorization', 'Basic YWJjZEBzcGFtLmNvbTphYmNk')
    .inspectJSON()
    .toss();
frisby.create('Test with implicit headers')
    .delete('http://httpbin.org/delete', { headers: { 'Authorization': 'Basic YWJjZEBzcGFtLmNvbTphYmNk' } })
    .inspectJSON()
    .toss();

The first way provides the header in the request, while the second does not appear to. 

{ args: {},
  data: '',
  files: {},
  form: {},
  headers: 
   { Authorization: 'Basic YWJjZEBzcGFtLmNvbTphYmNk',
     'Content-Length': '0',
     'Content-Type': 'application/x-www-form-urlencoded',
     Host: 'httpbin.org' },
  json: null,
  origin: '89.243.41.39',
  url: 'http://httpbin.org/delete' }
.{ args: {},
  data: '',
  files: {},
  form: { 'headers[Authorization]': 'Basic YWJjZEBzcGFtLmNvbTphYmNk' },
  headers: 
   { 'Content-Length': '59',
     'Content-Type': 'application/x-www-form-urlencoded',
     Host: 'httpbin.org' },
  json: null,
  origin: '89.243.41.39',
  url: 'http://httpbin.org/delete' }

I'll take a closer look at this over the next couple of days. It's not a show-stopper

**Comment by jamescarlyle** [comment]
Apologies, it looks like I had picked up an incorrect method for specifying headers on the request by looking at the blog post here and copying the approach

http://bazscott.com/blog/2014/11/25/API-Testing-With-Frisby/

but I can't see from the documentation that this is actually a valid method.

Oddly, both methods do set the header correctly for HTTP GET, i.e.

frisby.create('Test with explicit addHeader call')
	.get('http://httpbin.org/get')
	.addHeader('Authorization', 'Basic YWJjZEBzcGFtLmNvbTphYmNk')
	.inspectJSON()
	.toss();
frisby.create('Test with implicit headers')
	.get('http://httpbin.org/get', { headers: { 'Authorization': 'Basic YWJjZEBzcGFtLmNvbTphYmNk'	} })
	.inspectJSON()
	.toss();

{ args: {},
  headers: 
   { Authorization: 'Basic YWJjZEBzcGFtLmNvbTphYmNk',
     'Content-Type': 'application/x-www-form-urlencoded',
     Host: 'httpbin.org' },
  origin: '89.243.41.39',
  url: 'http://httpbin.org/get' }
.{ args: {},
  headers: 
   { Authorization: 'Basic YWJjZEBzcGFtLmNvbTphYmNk',
     'Content-Type': 'application/x-www-form-urlencoded',
     Host: 'httpbin.org' },
  origin: '89.243.41.39',
  url: 'http://httpbin.org/get' }

**Comment by vlucas** [comment]
Please try this in v2 and see if it is still an issue for DELETE requests.
