### ISSUE TITLE
Multiple afterJSON calls to the same test case?

### ISSUE THREAD

**Issue by ctindel** [vlucas/frisby#206]
Hi-

I have a bunch of tests where I need to hit a REST endpoint and then after that do 3 different test using the response from the first one.  Is it valid to just have a bunch of afterJSON blocks in sequence?

frisby.create().get()
    .afterJSON(foo1(res)) {
        frisby.create.get().toss()
    })
    .afterJSON(foo2(res)) {
        frisby.create.get().toss()
    })
    .afterJSON(foo3(res)) {
        frisby.create.get().toss()
    })
    .toss()

**Comment by vlucas** [comment]
If the order doesn't matter, then it is perfectly fine to do that. :+1:

**Comment by ctindel** [comment]
OK great!  Yes I've used multiple nested layers of .afterJSON to control the order before, just wasn't sure about this one.

**Comment by KusumaScriptbees** [comment]
Hi

I have a case where i'll use REST Services and receive the response. I'm good with this case.

But i have a doubt may i use the same JSON response in 2 different cases ????

frisby.create('Register User').post(URL + "auth/register", {
	name : "Lisa Roy",
	password : "lisaroy",
	email : "lisaroy@gmail.com"

}).expectStatus(200).expectHeaderContains('content-type', 'application/json').afterJSON(autoActivationAction).toss();

here afterJSON method call autoactivatioaction function i'm good till this. Where the problem arrives is i want to use the same JSON response for other function too.How do i wirte/use it????? Please let me know.
