### ISSUE TITLE
Frisby - GET - get and store one of the returned value

### ISSUE THREAD

**Issue by abcdefghigk** [vlucas/frisby#208]
/*****************\* JSON raw Data *****************/
 {
 "status": "200 OK",
 "list" :[{"userid": 1, "user": "Jack:}, {"userid" :2, "user": "Tom"}, {"userid": 3, "user": "Tim"}]
 }

/****************\* Question ************************/
 After get, I want to get and store the "userid" number of "user": "Tim" (That is, I want to store value 3 for user Tim so that I can use it later)
 How to do that? Thanks in advance

**Comment by abcdefghigk** [comment]
Anyone can help me? Thanks.

**Comment by adrianblynch** [comment]
What have you tried so far?

**Comment by vlucas** [comment]
All you have to do is declare a variable, store it in an `.after` or `.afterJSON` method, and then make further API calls inside there.

```javascript
var userId;

frisby.create('First test')
  .get('http://example.com/some.json')
  afterJSON(function(json) {
    userId = json.user.id;

    frisby.create('Second test, run after first is completed')
      .get('http://example.com/some/user/' + userId + '.json')
    .toss()
  });
.toss()
```

**Comment by concordion2k** [comment]
This is very useful. Thank you =]

**Comment by gmarokov** [comment]
Hello, @vlucas. Will userId in you example above be available outside the scope it's value is assigned, for example another test without nesting cases? Thanks.

**Comment by vlucas** [comment]
@gmarokov It might, but it also depends on the order in which the tests are run, which you should not depend on. So really, I would only count on the variable being set in the `afterJSON` scope or lower.

In v2, this would be:
```javascript
.then(function(res) {
  var userId = res.json.user.id;
  // etc...
})
