### ISSUE TITLE
Test not running correctly depending on the test runner

### ISSUE THREAD

**Issue by Liooo** [vlucas/frisby#209]
I was running the frisby test with `jasmine-node`, which was working well, and decided to start using gulp-jasmine.
Then faced the problem in #173, the solution suggested there was to install frisby from github repo, but still it's not working well.
It looks like some buggy things going on as the following.

| [test runner] \ [frisby version] | npm published frisby | github latest frisby |
| --- | --- | --- |
| gulp-jasmine | raises error in #173 | works, but `frisby.create` in afterJSON dosn't work |
| jasmine-node | works well | no error raised, but there's no output either |
### gulp-jasmine

Use the following gulp task

```
var gulp = require('gulp');
var jasmine = require('gulp-jasmine');

gulp.task('jasmine', function () {
    return gulp.src('test/server/api.spec.coffee')
        .pipe(jasmine());
});
```
### jasmine-node

run the following from the comamnd line 

```
jasmine-node --coffee test/server/api.spec.coffee
```
### used frisby test case

Essentially same as the sample in the official readme.

https://github.com/vlucas/frisby#creating-tests

**Comment by vilmysj** [comment]
`gulp-jasmine` uses Jasmine2, master branch also has Jasmine2 but in Jasmine2 version it is not possible nesting `describe` inside `it`.  
`after` and `afterJSON` methods are called inside `it` which creates new `describe - it` but does not execute `it` part.
```Javascript
describe("First test", function() {
  it("First test executed", function() {
    // Frisby after and afterJSON called, which creates new describe, it
    describe("Second test", function() {
      it("Second test not executed", function() {
        // not executed part
      });
    });
  });
});
```
I have tried this scenario with both `gulp-jasmine` and `jasmine-node@2.0.4-beta4` and getting same result - 1 test. With `jasmine-node@1.14.5` result is 2 tests.

**Comment by Liooo** [comment]
Thanks @vilmysj. So probably adding that description to the document is what should be done so far?

**Comment by vilmysj** [comment]
@Liooo If you still want to use gulp with frisby you can use this workaround:
```Javascript
var gulp = require('gulp'),
    argv = require('yargs').argv,
    child = require('child_process');

gulp.task('frisby', function() {
    var execCommand = '.\\node_modules\\.bin\\jasmine-node ';
    execCommand += argv.p ? argv.p : 'spec/'

    child.exec(execCommand, function(err, stdout, stderr) {
      console.log(stdout);
      console.log(stderr);
    });
});
```

Here I am using `jasmine-node@1.14.5` and `frisby@0.8.5`. 
`yagrs` to pass test path to jasmine.
Example `gulp frisby -p spec/example_spec.js`

**Comment by vlucas** [comment]
This is not an issue with v2 since it no longer outputs or calls the Jasmine functions directly.
