### ISSUE TITLE
_jsonParse leaks 'json' to the global scope

### ISSUE THREAD

**Issue by RobertHerhold** [vlucas/frisby#210]
The function _jsonParse leaks the variable `json` to the global scope because it is missing the `var` keyword.
## This

``` javascript
function _jsonParse(body) {
  json = "";
  try {/*...*/}
  /*...*/
}
```
## Should be

``` javascript
function _jsonParse(body) {
  var json = "";
  try {/*...*/}
  /*...*/
}
```

Thanks for all the excellent work on this project.
I would submit a pull request but I already have a fork of this project with other changes.

**Comment by vlucas** [comment]
This is not an issue in v2.
