### ISSUE TITLE
Expect JSON not erroring on missing key

### ISSUE THREAD

**Issue by JoyShafer** [vlucas/frisby#211]
I'm relatively new to programming, so it's possible I'm missing something basic. I'm using .expectJSON to verify data coming back from our service. My code is as follows:

frisby.create('Service V3 Response Correct')
		.get(Url + 'v3/' + field)
		.addHeader('x-user-id', userId)
		.addHeader('x-user-email', userEmail)
		.expectJSON({
			"request-id": function(val){
				expect(val).toMatch(/^\w{8}-\w{4}-\w{4}$/);
			},
			"key-events": [],
			"total-available-x": {
				lower: function (val) {
					expect(val).toMatch(/^\d{1,2}.{16,17}$/);
				},
etc.

The response coming back from the server is identical to the above except:

		"key-events": [],
			"field-name": "Adam - Corn",
			"total-available-n": {'

I would expect my test to fail with something along the lines of 'undefined expected to match "field-name": "Adam-Corn"', but my tests are all passing even though I'm not checking for this key (it was an update to the JSON that I missed when I updated my tests). 

Does .expectJSON ignore extra fields that are returned?

**Comment by RobertHerhold** [comment]
@JoyShafer `.expectJSON()` does indeed ignore extra fields. You can implement your own checks in `.after()` or `.afterJSON()`. Alternatively, I have a fork of this project called [IcedFrisby ](https://github.com/RobertHerhold/IcedFrisby) which has a more strict version of `.expectJSON()`. You can see an [overview of the differences here](https://github.com/RobertHerhold/IcedFrisby#what-makes-icedfrisby-different) if you are interested.

**Comment by sasikanthnimmagadda** [comment]
@JoyShafer  
Yes,  .expectJSON () will ignore extra fields. 
Not in every test case would you want to verify each and every field and its value.
If your test case objective is to validate only a certain part of the response. you could use .expectJSON
You might as well use .expectJSONLength to compliment to a certain extent, by asserting on number of fields that you would expect.
If your approach is to do a strict validation, you might have to consider the icedfrisby

below sample shows usage of expectJSON and expectJSONLength
```javascript
frisby.create('testcase')
  .get('http://httpbin.org/get')
  .expectJSON({
        args: {  },
        headers:
        {
           'Content-Type': 'application/x-www-form-urlencoded',
            Host: 'httpbin.org'
        },
        origin: '1.1.1.1',
        url: 'http://httpbin.org/get'
    })
 .expectJSONLength('args', 0) //you can give the path.
 .expectJSONLength('headers', 4) // you are interested in validating only 2 headers, but expecting 4 
.toss()
```

**Comment by vlucas** [comment]
This is the expected behavior for this method. Lots of people do like errors for missing keys, but that will likely be implemented with a different method down the road, like `expectJSONStrict`.
