### ISSUE TITLE
saving answer oft content-type 'application/pdf' in .after

### ISSUE THREAD

**Issue by level420** [vlucas/frisby#212]
I've tried the following code:

```
        .expectHeader('Content-Type','application/pdf; charset=utf-8')
        .after(
          function(err, res, body) {
            var wstream = fs.createWriteStream("test.pdf");
            wstream.write(body);
            wstream.end();
```

The resulting file starts with `%PDF-1.4` but acrobat is unable to open the file.

Is this supposed to work?

What am I doing wrong?

Thank you for your help.

**Comment by vlucas** [comment]
I am not sure what the issue is here. Try this with Frisby v2: `.then(res => { res._body // etc.`
