### ISSUE TITLE
Unable to capture HTTP status 204 

### ISSUE THREAD

**Issue by abhirep** [vlucas/frisby#213]
I am trying to capture HTTP status 204 no content but frisby always returns the status as 500. I have checked the same request in fiddler and using RestAssured within eclipse and in both cases I am able to intercept 204 status

**Comment by sasikanthnimmagadda** [comment]
works fine with below sample..   

````
var frisby=require('frisby');
frisby.create('status 204')
    .get('http://httpbin.org/status/204')
    .inspectStatus()
    .expectStatus(204)
    .toss();
````  

Output
```
204
.

Finished in 2.117 seconds
1 test, 1 assertion, 0 failures, 0 skipped
````  

What is the actual response you get ?   ```.inspectBody()``` ```.inspectResponse()```
Can you execute any other scenario (like 200, 403, etc) to confirm 500 is not because of proxy ?  

~ Sasi
