### ISSUE TITLE
Frisby - token variable doesn't work

### ISSUE THREAD

**Issue by abcdefghigk** [vlucas/frisby#214]
==================== Requirement =============================
To do any API actions, must get authentication.
And that means, at first get token, and then add the token in header to finish other actions

==================== Code ===================================

frisby.create('log in')
    .post(.........)
    .afterJSON(function(user_auth){
          frisby.globalSetup({
            request:{
                      headers:{'token':'9bc5ce215b9a3f9c907a16a05c360f8c'}   //Hard code
              OR   headers:{'token': user_auth.token}  //token variable
            }
        });
      //start the normal testing
     frisby.create(normal testing)
      .post ()
     })
.toss();
=================== Issue  ================
If use hard code token in header, the API testing is passed.
While use taken variable in header, testing is failed.

==================== Question =============
What's the root cause and solution? Thanks

**Comment by RobertHerhold** [comment]
There is absolutely no reason that you cannot pass in information to the headers via variables. The issue here is not with Frisby, but rather seems to be that your user_auth object is out of scope.
