### ISSUE TITLE
Unable to run frisby's tests correctly

### ISSUE THREAD

**Issue by dustyjewett** [vlucas/frisby#216]
I have a fix for an issue I've found, and I'm attempting to add a test for the specific case.  Alas, when I run the tests, they all pass in 0.15 seconds... it's obvious that no requests to httpbin are being made.  Further investigation shows that I can modify ANY of the frisby.toss() methods, and they always pass. I can make changes to the frisby_global tests to make the tests pass, so _some_ failures are being picked up.

Environment:
Node v0.10.33
NPM 1.4.28
Frisby: master / c266eeaf07c1e1cbac41623f64984e35355db5e4

STR: 
1. Clone to new repo
2. Run `npm install`
3. Run `npm test`

**Comment by tiagolpadua** [comment]
same problem here... Any progress?

**Comment by dustyjewett** [comment]
Nope, and I'm no longer working on the project that used frisby... I don't see the maintainers being very responsive, but who knows.  Unsubbing from this issue.

**Comment by vlucas** [comment]
Try v2. It is much more stable than v1 ever was.
