### ISSUE TITLE
Allow false-ish values for request body

### ISSUE THREAD

**Issue by fardelian** [vlucas/frisby#220]
Around line 354 in lib/frisby.js, the outgoing object for _request is built like so:

```
  outgoing = {
    json: params.json || (_frisbyGlobalSetup && _frisbyGlobalSetup.request && _frisbyGlobalSetup.request.json || false),
    uri: null,
    body: params.body || undefined,
    method: 'GET',
    headers: {}
  };
```

First, the || null is still in the npm repos. Second, please allow false-ish values for params.body like "null" and "0" (not as strings).

**Comment by vlucas** [comment]
This should work with v2, as it uses the `fetch` API.
