### ISSUE TITLE
Add Mocha support

### ISSUE THREAD

**Issue by motherwaym** [vlucas/frisby#221]
Looks like this is already under way (https://github.com/RobertHerhold/IcedFrisby), but I'd like to track it somehow.

**Comment by vlucas** [comment]
IcedFrisby looks like a great fork if you want to use Mocha. I have considered switching to Mocha for a Frisby.js 2.0, but I think I want to give Jasmine 2.0 a try first.

**Comment by mentrie** [comment]
I am still curious if we can run Frisby with Mocha as it seems it works only with Jasmine-node
