### ISSUE TITLE
When running with verbose and nested test via afterJSON, nested request is not output

### ISSUE THREAD

**Issue by danielwertheim** [vlucas/frisby#222]
When running with verbose and nested test via `afterJSON`, nested request is not output in console.

**Comment by filipszu** [comment]
+1

**Comment by 1upon0** [comment]
any way to fix this?

**Comment by filipszu** [comment]
Well the hackish way to make it work is to Edit the jasmine-node/lib/reporter.js and modify the TerminalVerboseReporter.reportSpecResults()

**Comment by nickveenhof** [comment]
Also running into this issue.

**Comment by jkwohlfahrt** [comment]
Having this issue as well

**Comment by vlucas** [comment]
This is fixed in Jasmine 2 (currently in master branch), but I am not sure how to fix this is the current v0.x releases.

**Comment by guy16510** [comment]
I'm sort of at a loss with this as well. I played around with the reporting, and this is a sticking point for me.

**Comment by stickshift** [comment]
I hacked lib/jasmine-node/reporter.js to a workable solution.

Find jasmineNode.TerminalVerboseReporter.reportSuiteResults and add the following lines to the bottom. This will add child suites to the reporting structure as they finish. Not the right way to implement it but it works!

        // HACK: Add child suites to top level reporting structure
        var found = false;
        for (var i = 0;i < this.suites_.length;i++) {
            if (this.suites_[i].id == suite.id) {
                found = true;
            }   
        }   

        if (!found) {
            this.suites_.push(this.summarize_(suite));
        }

**Comment by vlucas** [comment]
This will never work in 0.x due to the reasons outlined in #316. Please update to v2.
