### ISSUE TITLE
Frisby toss returns before a result is returned from the server.

### ISSUE THREAD

**Issue by pvanka** [vlucas/frisby#224]
I am writing the below code and I find sync issues. The debugger on my server still runs while the test returns on the command prompt. This is my first test in Frisby  .
var jsonlist =
[
{
name:'xyz',
},
{
name:'abc',
}
];
frisby.create('Test UserFlow')
  .post('http://localhost:8088/api/v1/login/user.json',{
"userName":"user",
"lastName":"last",
"emailAddress":"prin@gmail.com"
},{json:true},{headers: {'Content-Type':'application/json'}
})
  .expectStatus(200)
  .expectHeaderContains('content-type', 'application/json')
  .expectJSON({
      result: jsonlist,
      status: 'SUCCESS',
      sessionTicket: null,
  }) .expectJSONTypes( {
    jsonlist: Array,
    status: String,
      sessionTicket: String,
     })
  
.toss();

I get below error in commandprompt:
 Message:
   Expected 500 to equal 200.
 Stacktrace:
   Error: Expected 500 to equal 200.
  at null.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:493:42)
  at null.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:1074:43)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

2)
 Message:
   Error: Header 'content-type' not present in HTTP response
 Stacktrace:
   Error: Header 'content-type' not present in HTTP response
  at null.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:520:13)
  at null.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:1074:43)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Any idea if i am missing anything?

**Comment by RobertHerhold** [comment]
That is very hard to read. Can you put your code in proper markdown?
> \`\`\`javascript
> myCodeHere();
> // and lots more
>\`\`\`

**Comment by pvanka** [comment]
Hi Robert,

Does this markup look better?

var jsonlist = [
    {
        name: 'xyz',
},
    {
        name: 'abc',
}
];
frisby.create('Test UserFlow')
    .post('http://localhost:8088/api/v1/login/user.json', {
        "userName": "user",
        "lastName": "last",
        "emailAddress": "prin@gmail.com"
    }, {
        json: true
    }, {
        headers: {
            'Content-Type': 'application/json'
        }
    })
    .expectStatus(200)
    .expectHeaderContains('content-type', 'application/json')
    .expectJSON({
        result: jsonlist,
        status: 'SUCCESS',
        sessionTicket: null,
    }).expectJSONTypes({
        jsonlist: Array,
        status: String,
        sessionTicket: String,
    }).toss();

**Comment by pvanka** [comment]
Hi Robert,

 I am trying to beautity it in Brackets but the moment I paste here - all the indentation is gone, Is there a better way? Thanks for your help.

**Comment by RobertHerhold** [comment]
@pvanka 
Right, when you paste it without Markdown formatting, GitHub assumes it to be plain text.

You need to try what I wrote in my previous comment; put your code betwen three backticks '`' on top and three on the bottom. This will tell GitHub that it is a code block.

You may also want to learn more about markdown here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by marcin-wosinek** [comment]
@pvanka from what I can tell, your test code is doing it's job. In case 1 looks like you get status 500 (server error) instead of 200 (success) - you can see what server is returning by running `inspectBody()` in the frisby chain. In 2nd case you probably lack the headers - you can chekc them with `inspectBody()`

**Comment by pvanka** [comment]
Thanks for your inputs.I am running this test with jasmine- node.
jasmine-node e2e\frisby,spec.js . 9 out of 10 times I get the below error . Only one time it is a success.
The error with inspectJSON ()and inspectBody() added to the frisby chain is --
 Message:
   Error: Error parsing JSON string: Unexpected token D
      Given: Destination URL may be down or URL is invalid, Error: ETIMEDOUT
 Stacktrace:
   Error: Error parsing JSON string: Unexpected token D
      Given: Destination URL may be down or URL is invalid, Error: ETIMEDOUT
  at _jsonParse (C:\dev\login\node_modules\frisby\lib\frisby.js:1219:11)
  at Frisby.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:910:30)
  at Frisby.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:940:8)
  at null.<anonymous> (C:\dev\login\node_modules\frisby\lib\frisby.js:1112:18)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Does anybody have any idea why an error would only be intermittent with frisby and jasmine-node? Is it a bug in frisby?. Is there a latest version of frisby?

**Comment by pvanka** [comment]
```javascript

var jsonlist =
[
{
name:'xyz',
},
{
name:'abc',
}
];
frisby.create('Test UserFlow')
.post('http://localhost:8088/api/v1/login/user.json',{
"userName":"user",
"lastName":"last",
"emailAddress":"prin@gmail.com"
},{json:true},{headers: {'Content-Type':'application/json'}
})
.expectStatus(200)
.expectHeaderContains('content-type', 'application/json')
.expectJSON({
result: jsonlist,
status: 'SUCCESS',
sessionTicket: null,
}) .expectJSONTypes( {
jsonlist: Array,
status: String,
sessionTicket: String,
})

.toss();
```
// and lots more

**Comment by marcin-wosinek** [comment]
For headers I've meant `inspectHeaders`. 

`inspectJSON` fails with a message that suggest that body is not in json format. Try removing all expectations, and run test only with `inspectHeaders` & `inspectBody`. If now there will be any undeterministic differences those will be on your backend side.

**Comment by RobertHerhold** [comment]
Error parsing JSON string: Unexpected token D
    Given: **Destination URL may be down or URL is invalid, Error: ETIMEDOUT**

Your server is not returning the response in a reasonable amount of time or you have the wrong address/port. How long does it take when run manually?

I think this is probably correct because you also said:
>  9 out of 10 times I get the below error . Only one time it is a success.

The 500 error and accompanying message that results "Destination URL..." [is from Frisby itself](https://github.com/vlucas/frisby/blob/master/lib/frisby.js#L433), not your server. Frisby adds the error if the connection times out. Try increasing it to 10 seconds.

Run this and report back please:
```javascript
frisby.create('Test UserFlow')
    .post('http://localhost:8088/api/v1/login/user.json',
    {
        "userName": "user",
        "lastName": "last",
        "emailAddress": "prin@gmail.com"
    },
    {
        json: true
    },
    {
        headers:
        {
            'Content-Type': 'application/json'
        }
    })
    .timeout(10000) // 10 second timeout
    .expectStatus(200)
    .toss();
```

**Comment by pvanka** [comment]
Thanks for the help guys - I think increasing the timeout helps . Frisby tests all passedl when I ran this same tests  on my office LAN.

**Comment by RobertHerhold** [comment]
Good to hear!

If this solved your issue, please close this issue.

**Comment by bharathkbk** [comment]
I have the same issue as pvanka reported. I tried using .timeout(30000) but still didnot get resolved. Can anyone help me?
