### ISSUE TITLE
Global Setup Issues

### ISSUE THREAD

**Issue by RobertHerhold** [vlucas/frisby#226]
I recently found an issue with Frisby and as a result, [IcedFrisby](https://github.com/RobertHerhold/IcedFrisby) where a number of global setup operations are not handled correctly.

I took the liberty of fixing these issues on my fork of Frisby. You can see the issues detailed in the IcedFrisby changelog [here](https://github.com/RobertHerhold/IcedFrisby/blob/5769ee2ddef13a42c36065f173b22ee14d6c5494/CHANGELOG.md)

In a nutshell,
- `reset()` is not properly resetting all of the global setup options, leaving old options mixed in with new ones. This is fixed in [this commit](https://github.com/RobertHerhold/IcedFrisby/commit/edd8939552fed7a421a8991440ed3e495ace88bb).
- outgoing JSON and base URI flags are directly referencing the global instance of the global setup object rather than the "current" instance of the global setup stored when the test is started with `frisby.create()`. This is fixed in [this commit](https://github.com/RobertHerhold/IcedFrisby/commit/133de290dcbf4f2cba5c1bfbf8d006a51a9f1d1f).

I would create a pull request, but due to the number of changes I have made to my fork and how the fork has already partially diverged, it is just not practical for me to do so. I'd recommend someone cherry-pick/port the changes to Frisby or maybe someone can recommend a clever git solution.

Please note that these changes could possibly break users if they so happened to write tests that depended on a bad global setup state, so I'd recommend a 0.x.0 version bump.

Thanks!

**Comment by vlucas** [comment]
This is fixed in v2, which is much more stable than v1 ever was, even in alpha :)
