### ISSUE TITLE
Destination URL may be down or URL is invalid, Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by hasanyousuf** [vlucas/frisby#227]
Hi!
I am using frisby package in my protractor project. It works with example url mentioned in the code but I run the same command on my servers. I get "Destination URL may be down or URL is invalid, Error: self signed certificate in certificate chain". 

it("it should fetch data from couchdb",function(){
var frisby = require("frisby"),
//var restUrl='http://httpbin.org/get?param1=hello'; //example url
var restUrl='https://ourserver.me:443/couch/mydatabase/';
frisby.create('Access Couchdb')
.get(restUrl)
.after(function (err, res, body) {
console.log( body);
//expect(JSON.parse(body).args.param1).toMatch('hello')
})
.toss();
});

**Comment by marcin-wosinek** [comment]
You are connect to what looks like a internal host (ourserver.me) via https. Then node is checking your certificates, that are probably not set up. Try accessing via http, or search for way to disable certificate verification during tests.

**Comment by hasanyousuf** [comment]
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; 

Ugly fix but it works for the time being.
