### ISSUE TITLE
setTimeout doesnt work inside .after() ?

### ISSUE THREAD

**Issue by sasikanthnimmagadda** [vlucas/frisby#228]
Supporting the below feature in ".after" would be helpful
".after(func) " ==> immediately after api call
".after(func, n)" ==> n seconds after api call 

This is where something needs to be verified 'n' seconds after the api call is completed. 
```javascript
frisby.create(....)
.get(...)
.after(function(err,res,body){
   console.log("this should be done 5 seconds after api invocation is done");
   console.log("verify some log file here...");
   },5000)
.toss()
```
 i dont want the api call to wait - using waits() is not suitable here.

I tried the below using settimeout. However, when there is an error, frisby / jasmine cannot catch it. execution is already done and report is also shown on console.
```javascript
.after(function(err,res,body){
      settimeout(customAssertion, 5000);
   },5000)
.toss()

var customAssertion = function(){
   console.log("after 5 sec");
  throw new Error("err in custom assertion");
},
```

the above is not working. Frisby/Jasmine-node reports the spec as passed in the console. 
then prints the "after 5 sec"
The error is not reported.

Will Firsby be able to support .after( func, timeout) ? Does it already support in a different way ?
If not, can you suggest any alternative for the moment ?
Does wait.for integrate with frisby for this requirement ?

Thanks,
Sasi

**Comment by vlucas** [comment]
If you need to wait for something to complete, you can use standard async Jasmine expects:
http://www.htmlgoodies.com/beyond/javascript/test-asynchronous-methods-using-the-jasmine-runs-and-waitfor-methods.html

This is exactly what Frisby is doing for you in the background already. Jasmine 2.0 supports a simpler "done" callback that Frisby will have a version released for soon.
