### ISSUE TITLE
.expectJSONTypes should allow arrays of primitive types

### ISSUE THREAD

**Issue by frroliveira** [vlucas/frisby#232]
I need to test if my API returns an Array of Number. For now I'm mocking the response in order to use .expectJSONTypes by adding a 'id' field.

``` javascript
function(val) {
  if (expect(val).toBeType(Array)) {
    var newVal = val.map(function(value) {
      { id: value }
    })
    expect(newVal).toContainJsonTypes('*', {id: Number})
  } else {
    false
  }
}
```

**Comment by marcin-wosinek** [comment]
You could test it in the loop, or use some custom matchers.

**Comment by frroliveira** [comment]
The function above is a custom matcher implementation.
I'm suggesting the introduction of something like,
```javascript
...
.expectJSONTypes("*",
  _: Int
)
```
that would do the same.

**Comment by robthejedi** [comment]
Since the array is usually of the same type you could use
.expectJSONTypes('*.?", Number)

to validate the first item of the array.
