### ISSUE TITLE
How to send form data for POST request ?

### ISSUE THREAD

**Issue by saivamsilolla** [vlucas/frisby#233]
from the post man(rest client) preview the request looks like this

POST /test1/rest/login/v2 HTTP/1.1
Host: trunk.dev.test1.intuit.com
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

LoginName=vamsi.folio&Password=a123456

How to send this request thru frisby?
Should we use form data ,but not wokring 
var FormData = require('form-data');

form.append('LoginName', 'vamsi.folio');
form.append('Password', 'a123456');

**Comment by Shafiul-Hasan-tareq** [comment]
please see this method of frisby 
https://github.com/vlucas/frisby/blob/master/lib/frisby.js
line number 283
Frisby.prototype.auth = function(user, pass, digest) {

**Comment by vlucas** [comment]
Frisby sends form-urlencoded data by default. You don't need to use the `form-data` module.

```javascript```
frisby.create('Test Login')
  .post(/test1/rest/login/v2', {
    'LoginName': 'vamsi.folio',
    'Password': 'a123456'
  })
  .expectStatus(200)
  .expectJSON({
    somekey: 'somevalue'
  })
  .toss();
```
