### ISSUE TITLE
How to pass variable in POST request

### ISSUE THREAD

**Issue by andrepm06** [vlucas/frisby#239]
How i can pick an value of a json field and use it in a post?

for example:

    var frisby= require('frisby');

    frisby.create('Login')
	    .post('http://mid.dev.psafe.com/My.API/security/Authentication.svc/Login',
		    {"user":"115303640577606155760"},
		    {json:true},
		    { headers: { 'Content-Type': 'application/json' }})
	    .expectStatus(200)
	    //.inspectBody()
	    .after(function (err,res,body) {
		    var token = body;
		    frisby.globalSetup({
			    request: {
				    headers: { 'User-Token': token }
			    }
		    });

		    frisby.create('List associated devices')
			    .post('http://mid.dev.psafe.com/My.API/APIAdmin.svc/GetDevices',
				    {json:true})
			    .expectStatus(200)
			    .inspectJSON()
			    .afterJSON(function (res) {
				    var id = res[0].ID;
				    frisby.create('Alarm')
					    .post('http://mid.dev.psafe.com/My.API/APIAdmin.svc/SendMessageToDevice',
						    {"action":"device_alarm",
						    "deviceID":id,
						    "msg":null},
						    {json:true})
					    .expectStatus(200)
				    .toss();
		    .toss();
	    })

.toss();

I'm getting 500.

This is the Json wich i'm using to Alarm test:

    [ { AuthCode: '781262',
        Email: null,
        ID: 2015060000001341,
        IsNewDevice: true,
        IsOnline: false,
        IsOnlineLocate: false,
        LastOnlineTime: 
        { DateTime: '/Date(-62135589600000)/',
           OffsetMinutes: 0 },
        Location: null,
        Name: 'XT1097',
        UnLockCode: '412157' } ]

Should i add this question to https://github.com/vlucas/frisby/issues/143?

**Comment by marcin-wosinek** [comment]
if you have array in your json, then you probably need to access the value as: `var id = res[0].ID` .

**Comment by andrepm06** [comment]
I tried something similar before, but i got 400 just as i got now.

      1) Frisby Test: Disparar alarme 
	    [ POST http://mid.dev.psafe.com/My.API/APIAdmin.svc/SendMessageToDevice ]
       Message:
         Expected 400 to equal 200.
       Stacktrace:
         Error: Expected 400 to equal 200.
        at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:493:42)
        at null.<anonymous> (/usr/lib/node_modules/frisby/lib/frisby.js:1074:43)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by marcin-wosinek** [comment]
Try `console.log` on the *id*. If the value is as expected then the issue is in some other place.

**Comment by andrepm06** [comment]
Weird, the value is pretty much the same.

**Comment by andrepm06** [comment]
Got it, just sharing what it was:

    .afterJSON(function (res) {
				    var id = res[0].ID;
				    id.toString();
				    //console.log (id)
				    frisby.create('Disparar alarme')
					    .post('http://mid.dev.psafe.com/My.API/APIAdmin.svc/SendMessageToDevice',
						    {"action":"device_alarm",
						    "deviceID":[id],
						    "msg":null},
						    {json:true})
					    .expectStatus(200)
				    .toss();

**Comment by ctadeu** [comment]
if is working please close
