### ISSUE TITLE
How to wait for an async test setup to be done before executing Frisby test cases

### ISSUE THREAD

**Issue by pedgarcia** [vlucas/frisby#240]
Hi

I am setting up a test suite where the tests will call a GET api passing a value. For my test database, the key value changes (random) so my test suite would need to:

1> Request GET once and retrieve the new key value, and maybe put it in a global variable.

``` javascript
frisby.create('__Init')
  .get('http://127.0.0.1:3333/test_api')
  .expectHeaderContains('Content-Type','json')
  .afterJSON(function (body) {
    expect(Object.keys(body)[0]).not.toBe(undefined);
    //save key for future use
    global.id = Object.keys(body)[0];
    console.log('>>> Key used for test: ', global.id);
  })
.toss();
```

2> Call frisby tests using that global variable like:

``` javascript
frisby.create('T3 - Requesting GET:/test_api passing valid id -> ', global.id)
.get('http://127.0.0.1:3333/test_api/' + global.id)
.expectHeaderContains('Content-Type','json')
.toss()
```

My problem here is that the global.id is always undefined in (2) even if the value is properly printed in the console.log() in item (1).

Please, is there a way to workaround that? Is the problem the async nature of the tests, or am I making some basic scope mistake with the variable itself?

Thanks

Paulo

**Comment by marcin-wosinek** [comment]
In your code `global.id` is available after execution of afterJSON callback - which will for sure happen *later* then second block of code. The best approach for that would be to use some node library to force code to be run synchronously (e.g. [sync](https://github.com/ybogdanov/node-sync)).

**Comment by ctadeu** [comment]
any example please?

**Comment by pedgarcia** [comment]
Just to follow up. I am not experienced with the sync methods in node, so for this specific task what I did was make each test case self contained, with nested frisby calls. 

So each test case that needs that key will retrieve it first and then run the test using it. It caveat is the increased amount of code repeated.

```frisby.create('__Init')
  .get('http://127.0.0.1:3333/test_api')
  .expectHeaderContains('Content-Type','json')
  .afterJSON(function (body) {
    expect(Object.keys(body)[0]).not.toBe(undefined);
    frisby.create('T3 - Requesting GET:/test_api passing valid id -> ', Object.keys(body)[0])
         .get('http://127.0.0.1:3333/test_api/' + Object.keys(body)[0])
         .expectHeaderContains('Content-Type','json')
          .toss()
  })
.toss();```

Note: Code above cut/paste from my previous one - it might not run right away!

Thanks

Paulo

**Comment by ctadeu** [comment]
this is the expected flow for frisby :) i was talking about the sync. I tried but didnt work :/

**Comment by vlucas** [comment]
You have to nest the tests with Frisby as @pedgarcia showed in his comment. In v2, you would use a `.then()` since it has a promise based syntax.
