### ISSUE TITLE
Is there a task-runner plugin that works well with frisby?

### ISSUE THREAD

**Issue by andrepm06** [vlucas/frisby#242]
Today, i searched for a plugin in grunt who runs frisby tests. The only one project that uses jasmine 1.x is https://github.com/jasmine-contrib/grunt-jasmine-node and it is pretty much dead. 

Also, i looked in gulp, but no lucky. Is there any suggestions to setup these tests in a task runner?

**Comment by pierskarsenbarg** [comment]
I was looking at using onury/grunt-jasmine-nodejs but that requires jasmine 2.x so currently not much use. Once frisby uses v2 I'll be moving over to that.

**Comment by vlucas** [comment]
The recommended test runner with Frisby v2 is Jest.
