### ISSUE TITLE
Pending and disabled specs

### ISSUE THREAD

**Issue by mence** [vlucas/frisby#243]
[Jasmine](http://jasmine.github.io/2.3/introduction.html) allows for `xdescribe` and `xit` to disable or set to pending a spec, for example (from the Jasmine docs):

``` javascript
 xit("can be declared 'xit'", function() {
    expect(true).toBe(false);
  });
```

Can frisby pass these matchers down to Jasmine? Or can we just implement them as a Frisby matcher?

**Comment by vlucas** [comment]
This is not possible in a single test in v1 because of how Frisby controls the describe/it function calls. Please try this in v2.
