### ISSUE TITLE
should expectJSON work for JSON other than object & array

### ISSUE THREAD

**Issue by yangaobo** [vlucas/frisby#244]
I have a api return response with 'Content-type: application/json' in header and `"string"` as body.
According to http://json.org/, string, number, boolean and null are also JSON.
Since frisby uses node.js native JSON parser, the response body can be correctly parsed, but nothing I can put as the arguments of `expectJSON` to make it pass. Since the first string argument is regarded as the object path.

``` javascript
frisby.create('get json string').get('http://xxxx.xxx')
  .expectJSON('string') //I wish this to work
  .afterJSON(function(json){
    expect(json).toBe('string');
  }) //however, i can only do this
```

I think `expectJSON` should support the primitive types. Otherwise, it will be ambiguous to parse response without exceptions but not allowed to test the value.

I can make a pull request to let `expectJSON` test the identity for primitive types, but should I?
Because I understand `expectJSON` in frisby works more like `expectJSONContain`, it make sense that a string doesn't contain another string.
However, frisby seems don't have any more suitable methods, like `expectJSONEqual`, or `expectJSONStrict` to update

**Comment by vlucas** [comment]
Use `after` instead of `afterJSON` and you can do this.
