### ISSUE TITLE
Feature Request: Add Support for JSON Vulnerability Protection

### ISSUE THREAD

**Issue by blowsie** [vlucas/frisby#245]
Various APIs use Anti-XSS protection.
It would be great if we could specify this for a request, otherwise we get a JSON parsing error.

Here are some exmaples of Anti-XSS prefixes ;
- `)]}',\n`(Angular JS)
- `while(1);`
- `}];`

Frisby would have to strip these out to be able to parse the data correctly.

**Comment by marcin-wosinek** [comment]
This can be some how set in the config. I guess the prefixes/suffixes are different on different apis. PR will be welcome.

**Comment by blowsie** [comment]
I currently just hacked this into the source, I have't checked all of the usages of `_jsonParse` yet but this will give you an idea of roughly what is required here, what do you think?

```
function _jsonParse(body) {
  body = body.replace(/^\)]}',\n/, "");
  json = "";
  try {
    json = (typeof body === "object") ? body : JSON.parse(body);
  } catch(e) {
    throw new Error("Error parsing JSON string: " + e.message + "\n\tGiven: " + body);
  }
  return json;
}
```

**Comment by vlucas** [comment]
Please check out v2, and open a new issue or submit a PR if this is still an issue.
