### ISSUE TITLE
Using frisby with a proxy

### ISSUE THREAD

**Issue by blowsie** [vlucas/frisby#246]
When using frisby inside my corporate proxy, frisby returns `expected 500 to be 200`.

I tried to configure request to use a proxy with the following code but saw no resolution.

```
frisby.globalSetup({ // globalSetup is for ALL requests
  request: {
    proxy: 'http://127.0.0.1:43128'
  }
});
```

I have confirmed that frisby works as intended when I switch to a network that uses no proxy.

Am I doing something wrong here?

**Comment by sasikanthnimmagadda** [comment]
I have used proxy in frisby and it worked fine for me.

1. Check if proxy url/port is correct. Is your port 43128 or 3128 ?  

2. Check if your actual outgoing request contains proxy, by using ```.inspectRequest()```  

3. I think your proxy "http://127.0.0.1:43128" is by CNTLM.  If yes, is your cntlm started ?,
Are you able to see transactions on cntlm command window ?  

4. Will you be able to share output of ```.inspectBody()``` and ```.inspectResponse()```  ?   

~ Sasi

**Comment by blowsie** [comment]
@sasikanthnimmagadda 

Thanks for the response.

 1. Yes it is 43128
 2. -
 3. Yes it is CNTLM :+1: 
 4. I will aim to do this sometime this week

**Comment by vlucas** [comment]
Proxies work with v2 and the fetch() API.
