### ISSUE TITLE
Running frisby seems to require frisby module installed locally.

### ISSUE THREAD

**Issue by davezen1** [vlucas/frisby#25]
I received module not found errors when attempting to run frisby from the command like so:

jasmine-node spec/api/

I installed frisby globally like so:

npm install -g frisby

My node version is : v0.10.4 global only and frisby version 0.6.7 locally and globally

**Comment by benoror** [comment]
isn't expected to work globally out of the box, the same way jasmine-node does?

**Comment by yuankui** [comment]
I follow @vlucas advice, add a package.json file

```
{
	"name": "mytest",
	"version": "1.0",
	"dependencies": {
		"frisby": "*"
	}
}
```

and run `npm install` or `npm link`
then i finnaly can `require("frisby")` in my test script

**Comment by RobertHerhold** [comment]
Why not just do `npm install frisby --save-dev` and then require it later `var frisby = require('frisby')` ?

**Comment by yuankui** [comment]
@RobertHerhold that's cool

and I just find another way, `export NODE_PATH="'$(npm root -g)'"`

choose your like

**Comment by marcin-wosinek** [comment]
I'm sure frisby should be managed as a dev-dep. Api changes are likely, and users will be better of updating their test suites gradually.

I've PR change in documentation:
https://github.com/vlucas/frisby-site/pull/4
