### ISSUE TITLE
Is there a way to recall frisby.create()?

### ISSUE THREAD

**Issue by comscience15** [vlucas/frisby#252]
What i am doing is, I am trying to POST and DELETE for a couple times but I would like to reuse DELETE instead of retyping the same thing again and again which will be the code reduction. 

Ex.

frisby.create('adding a POST')
     .post(blah blah)
     .....
     .toss();

frisby.create('removing above POST')
    .delete(blah  blah)
    ....
    .toss();

.
.
.

it will help a lot if i can reuse "delete" one. Thank you in advance for your supports

**Comment by ctadeu** [comment]
asfaik is not possible and I would like to have this :+1:

**Comment by comscience15** [comment]
So what I did a work around is define .create() within the function and recall from other .creat() which work fine for me.

**Comment by vlucas** [comment]
All the tests you are writing are just JavaScript, so you can feel free to write helper methods or wrapper functions, etc. - it's what I do with Frisby to keep my sanity in larger codebases. I have JSON representations of all the types of responses I expect, and then store them in a config object that I use for tests and assertions, along with a bunch of other convenience methods, etc.

**Comment by tamilmani89** [comment]
can we use friby test with faker.js, control statements?

for Example : 

top : 
for(var i=0;i<2;i++){
   frisby.create(POST PAYMENT")
       .post(PAYMENT_URL_POST,
                  {
                      org_code : "code1",
                      bill_date : faker.date.between(new Date('2015-10-'), new Date('2015-10-31')),
                      total : faker.finance.amount
                   }
        .afterJSON( function (res){
                 if(res.meta.status == 409 ) {

**Comment by trevorhreed** [comment]
Example:

```
function deleteThing(id) {
  frisby.create('Delete thing by id: ' + id)
    .post('http://mysite.com/api/deleteThing?thingId=' + id)
    .expectStatus(200);
}

var ids = [1, 2, 3];

ids.forEach(function(id){
  deleteThing(id);
});

```
