### ISSUE TITLE
Posting plist as a body

### ISSUE THREAD

**Issue by sohira** [vlucas/frisby#254]
Is there any possibility to send .plist as body type?  Also, retrieve the request data (in .plist) and append it in the header for subsequent calls?   I am fairly new to frisby.js so any example(s) is greatly appreciated.   Basically, I am trying to automate the authentication calls of iOS application.  Thanks.

**Comment by vlucas** [comment]
You can certainly POST and check contents of .plist files with Frisby - you just won't be able to use any of the purpose-build JSON checking methods. Check some of the examples in the v2 README to get started.
