### ISSUE TITLE
Possible to run multiple multi-part post test?

### ISSUE THREAD

**Issue by yong362** [vlucas/frisby#255]
form.append('file_1', fs.createReadStream(logoPath), {
    knownLength: fs.statSync(logoPath).size // we need to set the knownLength so we can call  form.getLengthSync()
});
frisby.create('Title')
        .post(API1, form, {
            json: false,
            headers: {
                'content-type': 'multipart/form-data; boundary=' + form.getBoundary(),
                'content-length': form.getLengthSync()
            }

```
    })
    .expectStatus(200)
```

  .toss()
frisby.create('Title2')
        .post(API2, form, {
            json: false,
            headers: {
                'content-type': 'multipart/form-data; boundary=' + form.getBoundary(),
                'content-length': form.getLengthSync()
            }

```
    })
    .expectStatus(200)
```

  .toss()

I have no problem running test "title" but i having problem running test "title2" the error code is
"timeout: timed out after 5000 msec waiting for HTTP Request timed out before completing"

**Comment by ctadeu** [comment]
to solve that I create two "form"

**Comment by vlucas** [comment]
This is possible in Frisby v2 via the fetch() API.
