### ISSUE TITLE
frisby toss is throwing me error:Expected 500 to equal 200 and Header 'content-type' not present in HTTP response

### ISSUE THREAD

**Issue by bharathkbk** [vlucas/frisby#262]
var frisby = require('localpath/npm/node_modules/frisby');
frisby.create('Get Data From URL')
.get(url, { headers: { 'Authorization': 'myvalue' } })
.expectStatus(200)
.toss();    

  I used .timeout(30000) but still the error is thrown.  I have set the proxy through npm config also. Can someone help me in this?

**Comment by sasikanthnimmagadda** [comment]
hi bharath, 

did you try  ``.inspectBody()`` and ``.inspectResponse()``  ? 
will you be able to share the output.. 

Also use ``.inspectRequest()`` and confirm if your request is correct. 

Most of the time, its "Destination URL down or invalid..."  error.
Some people get a certificate error if URL is https..
Sometimes providing relevant proxy like this also works..
``.get(url, { proxy : "http://127.0.0.1:3128" })``  

    

~ Sasi

**Comment by testtolearn1** [comment]
still getting the error

**Comment by daveRanjan** [comment]
As ~Sasi said, please use inspectBody() and inspectResponse() and mention the output, so that we could help debug you.

**Comment by testtolearn1** [comment]
Its working now

**Comment by ctadeu** [comment]
can you close the issue?

**Comment by bharathkbk** [comment]
Thanks for the responses. Issue is resolved. :)
