### ISSUE TITLE
[ReferenceError: after is not defined]

### ISSUE THREAD

**Issue by nanotime** [vlucas/frisby#264]
Hey! I found this in one of my tests, im trying to generate a test that make a post request and after that, generate another post request to the same path making an intentional error... but i get this errorcode:

`Exception loading: /home/nano/Dev/erp-api/rest-tests/auth_register_spec.js
[ReferenceError: after is not defined`

Of course, i'm using the after() callback but nope... that callback was deleted in the api?

**Comment by vlucas** [comment]
I would have to see the code to help you. The method exists in Frisby, so it has to be your code.
