### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by octavianmiu** [vlucas/frisby#268]
I want to send email with the response of test. i create a sent email but i am not able to get the messages after i run the tests. how can i do that?

**Comment by marcin-wosinek** [comment]
it doesn't sound like an issue with frisby itself. What are you using to sent a mail? There can be issue with the tool; or with the machien configuration.

**Comment by octavianmiu** [comment]
frisby works just fine :) the idea is that when i run it in a console, it throws some messages. I want to get those messages and put them into an email

**Comment by marcin-wosinek** [comment]
To process error output you can use `2>` in stead of `>` to write error output to some file; or something like:

```
<frisby-command> 2>&1 | <mailing-command>
```

to collect all standard & error output & pipe it directly to some mailing utility.

**Comment by octavianmiu** [comment]
thx dude for helping me. i am js beginner. also i am using frisby in windows. this is a example of request:
function privacyPolicy() {
    var name = 'PrivacyPolicy';
    var url = 'http://www.worthpoint.com/worthpoint-privacy-policy';
    var expectedStatus = 200;
    var expectedType = 'application/json';
    var params = [['json', '1']];

    frisby.create(name)
        .post(url, {
            json: params[0][1]
        })
        .expectStatus(expectedStatus)
        .expectHeaderContains('content-type', expectedType)
        .expectJSONTypes({
            status: String,
            page: {
                id: Number,
                type: String,
                slug: String,
                url: String,
                status: String,
                title: String,
                title_plain: String,
                content: String,
            }
        })
        .after(function (err, res, body) {
            var statusCode = res.statusCode;


            if (statusCode != expectedStatus) {
                sendMessage(composeError(name, url, '', statusCodeError(expectedStatus, statusCode)));
            }
            else {
                //var bodyResponse = JSON.parse(body);
                //
                //var message = bodyResponse["response"]["message"];
                //
                //if (!(typeof message == 'string') && !(message instanceof String)) {
                //    sendMessage(composeError(name, url, '', JSON.stringify(bodyResponse)));
                //}
            }
        })
        .toss();

}


the idea is to know if request accomplished without or with errors, and if errors occurred  to catch them and put into an email. i will be grateful if u can show me an example of doing this

**Comment by marcin-wosinek** [comment]
With windows I have no idea. The lines I've posted above are for unix. It's reasonable to have the emailing utility outside your js code; but I have no idea about such utilities for windows. Win seems to be less piping-friendly any way.

Btw. there are CI programs that runs your tests & have options like email notification; statistics etc. The open source ones:
* https://jenkins-ci.org/ - runs on java, so maybe it's works on windows
* https://travis-ci.org/ - in the cloud. integrates nicely with github, free for open source projects
