### ISSUE TITLE
Test suite always passes

### ISSUE THREAD

**Issue by imranolas** [vlucas/frisby#272]
As I understand, frisby wraps jasmine's `it` function and handles the `done` callback for you. The result of this is that frisby's own test suite **always** passes as these async tests are nested within another `it` function without `done` being managed.

I would expect the following change to work but it seems jasmine gets confused with the nested `it` and throw a timeout. In fact the `after` callback is never called.

``` diff
  frisby-json-schema-spec.js

  it('should accept and validate JSONSchema file with jsonPath syntax', function(done) {
    frisby.create(this.description)
      .get('http://example.com/response2')
+     .after(function() { done(); })
      .expectStatus(200)
      .expectJSONSchema('response', 'fixtures/json_schema/response1.json')
    .toss();
  });
```

**Comment by vlucas** [comment]
This is fixed in v2 because Frisby no longer controls the describe/it functions.
