### ISSUE TITLE
how to use control statement in frisby test?

### ISSUE THREAD

**Issue by tamilmani89** [vlucas/frisby#273]
Here I have written the code for create post request with for loop;

In post request, org_code is unique; 

I'm beginner to frisby.js;
can you give me an example to skip the loop while occurring duplicate value on org_code; 

This is my code:

top : 
for(var i=0;i<2;i++){
   frisby.create(POST PAYMENT")
     .post(PAYMENT_URL_POST,
             {
                  org_code : "code1",
                    bill_date : faker.date.between(new Date('2015-10-'), new Date('2015-10-31')),
                         total : faker.finance.amount
}
.afterJSON( function (res){
if(res.meta.status == 409 ) {
continue top;
}
})
.inspectJSON()
.toss();
}

waiting for your suggestions...

thank you

**Comment by vlucas** [comment]
This is not possible in a single test in v1 because of how Frisby controls the describe/it function calls. Please try this in v2.
