### ISSUE TITLE
Unable to login and execute test cases

### ISSUE THREAD

**Issue by amiya-pattnaik** [vlucas/frisby#276]
Hi Vlucas,

I am new to Frisby. I am facing some issues while executing test cases. I think authentication is not happening.  In our application at the time of loging authentication code is generated which will be used afterwards .Below is the sample code.

```javascript
var frisby = require('frisby');

frisby.create('GET JSON data from an endpoint')
.post('https://abc.corp.xyg/application1',
    { username: 'user_test123', password: 'Mango#132' },
    { json: true },
    {headers:{'Content-Type': 'application/json'}})

.afterJSON(function (res) { 

//frisby.globalSetup({ request: { headers: { 'x-access-token': res.token } } });
frisby.globalSetup({ request: { headers: { 'token': 'fb79f12334578f0ee0f6db39043bf8174a1bdb96' } } });  

frisby.create('GET data requiring token authentication')
//after lading page of the app, i want to verify some data
.get('https://abc.corp.xyg/application1/?measure=Royalty&group=content_type')
.expectStatus(200)
.expectHeader('Content-Type', 'application/json')
.expectJSON({ /* whatever data you expect */ })
.toss();

}) //end of afterJSON
```

.toss();

Please help me, if I have made some mistake. 

Thanks,
Amiya

**Comment by amiya-pattnaik** [comment]
Sorry, forgot to mention that,
when I execute the test cases I get the  the entire HTML body out put in my console where I can trace out the authentication code etc.

**Comment by vlucas** [comment]
This did not work like this in v1, but it should work in v2. Please update to v2 and try again.
