### ISSUE TITLE
POST not working

### ISSUE THREAD

**Issue by kassimir** [vlucas/frisby#277]
I can GET with Frisby just fine, but I can't seem to POST with it. I've used Postman to ensure the POST is valid, but it always returns an error with Frisby. (The error is not helpful...the api only sends 404 errors for everything.) Here's the code I'm using:

frisby.create('test post')
.post('http://localhost/api', {
    "data": {
        "name": "Jackie L Smith",
        "birthdate": "2007-08-14",
        "relationship": "child",
        "boolVar": false
    }
}, {json: true}, 
{headers: { 'Content-Type': 'application/json' }})
.expectStatus(204)
.toss();

For the record, the api's success code is 204 for some reason.  What's the issue here?

**Comment by ctadeu** [comment]
hello

the first . should not be there
.frisby.create('test post')

and your 2nd and 3rd parameters was missing {

```
frisby.create('test post')
	.post('http://localhost/api',
	{"data": {"name": "Jackie L Smith","birthdate": "2007-08-14","relationship": "child","boolVar": false}},
	{json: true},
	{headers: { 'Content-Type': 'application/json' }})
.expectStatus(204)
.toss();

**Comment by kassimir** [comment]
The first period was accidental when posting the code here.  And the second and third parameters were tried the way you have them and still got the same problem.  I've edited the content in my initial post to reflect those changes, since they also do not work.

**Comment by ctadeu** [comment]
Authorization header? Or wrong url

I will take a lookagain in the format but looks ok

**Comment by kassimir** [comment]
As I said, everything works from Postman, so I know the url and headers are correct.

**Comment by ctadeu** [comment]
can you add .inspectRequest() and .inspectResponse() and post the results?

I tried a post in my app, using the lastes version of frisby and it works

Or just the .inspectRequest() and define in the global 

{code}
frisby.globalSetup({ // globalSetup is for ALL requests
  request: {
      inspectOnFailure: true
    },
    timeout: 20000
});

{code}
