### ISSUE TITLE
API to add new matchers

### ISSUE THREAD

**Issue by emilsedgh** [vlucas/frisby#278]
I would like to add new matchers to my frisby.
Its currently not possible because frisby hides the Frisby function so I cannot even add them using Frisby.prototype

I know that I can add jasmine style expects. That's not I want.
Frisby's style of matching is perfect and I'd like to embrace that.

**Comment by vlucas** [comment]
Frisby v2 solves this by allowing you to add your own expectations to Frisby itself:

```javascript
frisby.addExpectationHandler('name', function() {});
```
