### ISSUE TITLE
Add ability to "skip" tests

### ISSUE THREAD

**Issue by dougmartin17** [vlucas/frisby#279]
Would be nice to be able to add something to skip tests so we have a record of the tests being "run" but skipped.
f = frisby.create();
f.skipIf(x==true);
f.toss();

**Comment by ctadeu** [comment]
when I need skip a test I use the x
````
xdescribe("test1", function() {
	frisby.create('bla')
<....>

**Comment by dougmartin17** [comment]
That's a manual solution, not programatic though, right?

**Comment by ctadeu** [comment]
yes thats right :(

**Comment by vlucas** [comment]
This is no longer an issue in v2, because Frisby no longer controls the describe/it functions.
