### ISSUE TITLE
Custom Callbacks don't work.

### ISSUE THREAD

**Issue by dougmartin17** [vlucas/frisby#280]
f.expectJSON( '?', {
    id : function(val) { expect(val).toMatch(".+"); }
}

This test always passes even if I intentionally try to make it fail.

**Comment by AdnanMulic** [comment]
I had similar issue, try to add return in your function ( return expect(val).toMatch(".+"); ).
It worked for me.

**Comment by vlucas** [comment]
This appears to have been answered.
