### ISSUE TITLE
Best practice to define suits using frisby and jasmine

### ISSUE THREAD

**Issue by GiladShoham** [vlucas/frisby#283]
Hi,
im looking here: 
https://ian_lin.gitbooks.io/javascript-testing/content/chapter6.html
under Combine with Jasmine functions.
There is a way to define suites using the jasmine, then define test cases using the the jasmine - it.
But if i use this functions, i have nothing to define for the frisby.create which also define a suite. so if i use it, it will create suits -> test case -> suite, which is strange.
otherwise i can only use the frisby.create but then i can't use the jasmine it, so i have no place to define my test cases.

What is the best practice to define the suites and test cases using frisby and create.

Thanks.

**Comment by vlucas** [comment]
This is not possible in a single test in v1 because of how Frisby controls the describe/it function calls. Please try this in v2.
