### ISSUE TITLE
How can I test several requests with a short delay?

### ISSUE THREAD

**Issue by Ajaxy** [vlucas/frisby#285]
Hello.

I'm trying to imitate real traffic load and send requests with a little delay. But if I say
```
setTimeout(function () {
    test.create('My delayed test').get(url).expectStatus(200).toss();
}, 100);
```
Jasmine doesn't pick it up as a test and it's missing in results.

Thank you.

**Comment by vlucas** [comment]
Due to how Frisby wraps and creates Jasmine tests internally, I think something like this would have to be built-in to work properly.

**Comment by Ajaxy** [comment]
What do you mean? The example I provided is not working.

**Comment by Ajaxy** [comment]
Digging into source code showed that I can simply use `waits(timeout)` method, that will delay the request.
