### ISSUE TITLE
Run afterJSON synchronously 

### ISSUE THREAD

**Issue by GiladShoham** [vlucas/frisby#287]
Hi,
I have a test which add a user, then in the after json it will remove it (so the get test won't break).
Because the deletion is inside the afterJSON (because i need the new user's id), it run this deletion after the get test and the get fails.
Is there a way to run the aftetJSON synchronously or any best practice how to handle this situation to make sure i delete the user before the rest of the tests runs?

Thx.

**Comment by jtn-d** [comment]
I am facing the same problem. I thought that it could be solved with done callback:
```javascript
  it('', function(done) {
    frisby.create('')
      .get('https://api.github.com/users/octocat/repos')
      .addHeader('User-Agent', 'Awesome-Octocat-App')
      .expectStatus(200)
      .after(function(err, res, body) {
        done();
      })
      .toss();
  });
```
but the case always times out. Somehow frisby's internal functionality messes up the usage of done callback.
```shell
Failures:

  1) 
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 7.607 seconds
```

**Comment by GiladShoham** [comment]
@jtn-d Thx.
So have you find a way to do something with this?

**Comment by jtn-d** [comment]
Unfortunately no. I decided to change tools, went with jasmine,
sync-request and some helpers.

BR
-JTN

**Comment by kenmazhao** [comment]
I am not sure I understand you situation correctly.
I assume that your "get user test" only pass when the new created user is deleted.

Try following code:

```
frisby.create('Create user')
    .post(USER_API_BASE_URL + '/users', {
        "username": "test",
        "email": "test@localhost.com",
        "password": ""
    }, { json : true })
    .expectStatus(200)
    .afterJSON(function (json) {

        frisby.create('Delete user')
            .delete(USER_API_BASE_URL + '/users/' + json.id)
            .expectStatus(200)
            .toss();

        frisby.create('Check users')
            .get(USER_API_BASE_URL + '/users/')
            .expectStatus(200)
            .expectJSON({})
            .toss();
    })
    .toss();
```
Expected test order is 'Create user' -> 'Delete user' ->'Check users'

**Comment by vlucas** [comment]
This is not possible in a single test in v1 because of how Frisby controls the describe/it function calls. Please try this in v2.
