### ISSUE TITLE
How can I get a value as an input from response JSON in afterJSON()?

### ISSUE THREAD

**Issue by comscience15** [vlucas/frisby#289]
I need one of value in the response JSON object from a Frisby as an input data of another Frisby (using afterJSON()).

```
frisby.create('get data')
  . get(URL)
  .expectedStatus(200)

  .afterJSON(function(body) {
      frisby.create('using one of the above response value as input here')
         .put(URL + ......, testing(body.....), {json:true})
         .expectStatus(200)
         .inspectJSON()
         .toss()
  })
  .toss()
```

First section response JSON output is 

```
{ data: 
   { version: '5dd0e31a-c777',
     configurationVersions: 
      { current: 
         { version: '617e05de-f0bb3',
           modified: 1450222576696,
           whitelistModified: 1450222576696 } } },
  error: null }
```

I would like to get "data.configurationVersions.current.version" value  which is "617e05de-f0bb3"as the input to the second Frisby.  Anyone has any ideas how to do it? 

PS. testing() is a function

**Comment by comscience15** [comment]
I think i got it lol.  just use this

body.data.configurationVersions.current.version

**Comment by vlucas** [comment]
Closing this since it seems like you figured it out :)
