### ISSUE TITLE
Posting XML not working.

### ISSUE THREAD

**Issue by JeffML** [vlucas/frisby#290]
The response from httpbin.org shows that no data is sent on this request:

```javascript
var frisby = require('frisby');

var requestXml = '<?xml version="1.0" encoding="UTF-8"?>';
requestXml += '<body><foo>bar</foo></body>';

frisby.create('POST xml via frisby')
    .addHeaders(
            {
                "Accept": "*/*", 
                "Accept-Encoding": "gzip, deflate", 
                "Accept-Language": "en-US,en;q=0.8,fr;q=0.6,it;q=0.4", 
                "Content-Length": requestXml.length, 
                "Content-Type": "application/xml", 
                "Cookie": "_ga=GA1.2.1039490605.1450386216; _gat=1", 
                "Host": "httpbin.org", 
                "Origin": "chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo", 
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36", 
                "X-Mav-Foo": "flum"
            }        
    )
    .post('http://httpbin.org/post', requestXml, {json: true})
        .expectStatus(200)
        .inspectJSON()
        .toss();
```

I looked at the example [here](https://github.com/vlucas/frisby/blob/master/examples/httpbin_binary_post_put_spec.js), but if I use that form of the request, not even the headers go across.  I suspect I've got something wrong here, but it is not obvious.

P.S. --
Doesn't seem to matter what json is set to, and content-length doesn't seem to affect the response, either.

P.P.S --
Tried this version of the request (per #62), and still no data sent:
   ... .post('http://httpbin.org/post', false, {body: requestXml})...

**Comment by sharadJay** [comment]
were you able to post xml using frisby ?

**Comment by JeffML** [comment]
No.

**Comment by vlucas** [comment]
Did you try sending it with a different `Content-Type` header?

You sent it with `{json: true}`, and it's not JSON.
```js
.post('http://httpbin.org/post', requestXml, {json: true})
```

**Comment by JeffML** [comment]
> If you want to send a raw
request body or actual JSON, use { json: true } as the third argument (object
literal of options).

I'm not sending the XML as form-encoded, so I consider it 'raw'.  Am I misreading the docs?

I will get back to you on whether content-type=xml works.  Thanks for the response.

**Comment by JeffML** [comment]
One of our developers was able to figure out the magic formula:
var url = 'http://httpbin.org/post';
```

var requestXml = '<?xml version="1.0" encoding="UTF-8"?>';
requestXml += '<body><foo>bar</foo></body>';

var headers = {'content-type': 'application/xml','content-length': requestXml.length};

var myFrisby = frisby.create('Simple xml submit')
	.post(url,{},{headers: headers, body: requestXml})
	.expectStatus(200)
	.toss();
```
Perhaps this only works if the XML is passed in as the value of the body property in third argument to post, not as the second argument.
