### ISSUE TITLE
cannot add header from afterJSON with globalSetup

### ISSUE THREAD

**Issue by tique** [vlucas/frisby#293]
Hi, 
Im new to frisby so maybe im missing something.
i am trying to add a header to a request with the response from a previous request. 

i have tried: 

```
.afterJSON(function (res) {frisby.globalSetup({ request: { headers: { 'X-Client-Id': res.id } } })})
```

but X-Client-Id is not added as a header. 

can i have res.id available to other requests?

thanks

**Comment by vlucas** [comment]
Please try this in v2, and re-open if it is still an issue.
