### ISSUE TITLE
How to verify multiple arrays obj in json response 

### ISSUE THREAD

**Issue by jadhavamit** [vlucas/frisby#300]
Hi,
I want to verify the json response in frisby given below:
 {
  "status": {
    "status": "SUCCESS",
    "description": "Detokenise response successful"
  },
  "detokenObject": {
    "client": {
      "CUSTOMERS.client.FORENAMES": "1142601727150010616",
      "CUSTOMERS.client.SURNAME": "1142601727150010616",
      "CUSTOMERS.client.COUNTRY": "England"
    },
    "transactions": [
      {
        "CUSTOMERS.TX.TYPE": "buy",
        "CUSTOMERS.TX.ASSET": "NYSE:APPL",
        "CUSTOMERS.TX.AMT": "100"
      },
      {
        "CUSTOMERS.TX.TYPE": "sell",
        "CUSTOMERS.TX.ASSET": "NYSE:APPL",
        "CUSTOMERS.TX.AMT": "1000"
      },
      {
        "CUSTOMERS.TX.TYPE": "hold",
        "CUSTOMERS.TX.ASSET": "NYSE:ACN",
        "CUSTOMERS.TX.AMT": "1000000000000000001"
      }
    ]
  }
}

for that i have written frisby code like:
frisby.create('Check for Status code and Detoken Object for bulk request')
              .post(URL,obj,
              {json: true})
                  .expectStatus(200)
                  .expectJSONTypes("status",{
                    "statusCode":String,
                    "description":String
                  })
                  .expectJSON("detokenObject",{
                "client",
                  {
                    "CUSTOMERS.client.FORENAMES":'1142601727150010616',
                    "CUSTOMERS.client.SURNAME":"1142601727150010616",
                    "CUSTOMERS.COUNTRY":"England"
                  },
                  "transactions",
                [{
                    "CUSTOMERS.TX.TYPE":'buy',
                    "CUSTOMERS.TX.ASSET":'NYSE:APPL',
                    "CUSTOMERS.TX.AMT":'100'

```
              },
              {
                "CUSTOMERS.TX.TYPE":'sell',
                "CUSTOMERS.TX.ASSET":'NYSE:APPL',
                "CUSTOMERS.TX.AMT":'1000'
              },
              {
                "CUSTOMERS.TX.TYPE":'hold',
                "CUSTOMERS.TX.ASSET":'NYSE:ACN',
                "CUSTOMERS.TX.AMT":'1000000000000000001'            
              }]
              },
              "status",{
                "status":'SUCCESS',
                "description": 'Detokenise response successful'
              })
          .toss()
```

here 'obj' menas JSON request.

but whenever i am executing this frisby script is is showing error [SyntaxError: Unexpected token ,]
so please let me know how to handle this situation. Thanks in advance :)

**Comment by vlucas** [comment]
Frisby uses JSON.parse(), which requires valid JSON. This means your JSON is not valid, and thus Frisby cannot parse it.
