### ISSUE TITLE
Multipart upload using a json object instead of a file

### ISSUE THREAD

**Issue by rundmd** [vlucas/frisby#301]
I'm trying to test an api call that does a multipart upload using a json object instead of a file. Here is an example of the json that gets passed in a parameter named jsonpayload:

{ "videos": [{ "remote_url": "https://s3.amazonaws.com/testing/test_videos/video.mp4" }], "text": "groups", "author": { "alias": "testing", "token": "1456167795" }, "groups": ["custom"] ,"tags":["tagged"]}

**Comment by vlucas** [comment]
If this works with the `fetch()` API, you can do this in Frisby v2 with the `frisby.fetch()` method.
