### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by naveensrinivasan** [vlucas/frisby#302]
The frameworks looks cool. Can this also be used in any stress testing? Has anyone tried it. 

I am trying to see how we could extend the functional testing into also performance testing when needed.

Thank you!

**Comment by vlucas** [comment]
The short answer is no. Frisby is limited by the way Jasmine runs tests, which are one at a time. Load testing would require hundreds of parallel requests, and Frisby is not setup to do that.
