### ISSUE TITLE
gzip support .. please document it 

### ISSUE THREAD

**Issue by djangosdk** [vlucas/frisby#304]
Hi,
After going through solutions like ones suggested at https://github.com/vlucas/frisby/issues/270

I found that frisby already supports gzip by adding `{gzip: true}` in `get()` or `post()` methods.
This is a very key feature and should be documented as other solutions are very ugly which involve unzipping in  `.after()`

**Working Sample:**

``` js
//seems to work well in my tests
.get('http://SOMEURL', {gzip: true})
  .expectStatus(200)
```

**Usage:**

``` js
  frisby.create('GET JSON data from an endpoint')
  .get('http://SOMEURL', {gzip: true})
  .expectStatus(200)
  .expectHeader('content-encoding', 'gzip')
  .expectHeader('Content-Type', 'application/json')
  .expectJSON({ 'url': 'SomeValue' })
.toss();
```

**Comment by sasikanth** [comment]
Pull request for documentation added at https://github.com/vlucas/frisby-site/pull/8
