### ISSUE TITLE
Using Paths with expectJSONTypes

### ISSUE THREAD

**Issue by djangosdk** [vlucas/frisby#305]
Is such path allowed ``` 'data.user.?.settings'``` ?
I am trying to find any object of data.user array which will have settings ?
or more complex like ```data.user.?.settings.state.*``` to check for all objects in state array
``` js
 }).expectJSONTypes('data.user.?.settings', {
    'items': Array
  })
```

**Comment by muhNasrallah** [comment]
As far as I can tell, by [documentation](http://frisbyjs.com/docs/api/) and trying this is not possible:
> use expectJSON and expectJSONContains test all objects in an array, simply APPEND a path with an asterisk character (same with ?)

**Comment by djangosdk** [comment]
I switched to icedFrisby which uses Joi and i was able to create complex schemas for my test
