### ISSUE TITLE
Verbose log not showing tests in afterJSON

### ISSUE THREAD

**Issue by lschuermann** [vlucas/frisby#311]
Take this snippet for example:

    frisby.create('Get api-token for phrase-user')
      .post(url + 'auth/getToken', {
        username: username + '_phrase',
        password: password
      })
        .expectStatus(200)
        .expectJSONTypes({ token: String })
        .afterJSON(function (response) {
          var phraseUserToken = response.token;
          frisby.create('Verify phrase-user\'s default settings')
            .get(url + 'user/settings?token=' + encodeURIComponent(phraseUserToken))
              .expectStatus(400)
              .expectJSON({
                transactionLogging: false,
                smsNotificationNumber: null,
                recoveryMethod: "phrase",
              })
          .toss();
        })
        .toss();

When using `jasmine-node` in verbose-mode, the outer test (`Get api-token for phrase-user`) gets logged, while the inner (`Verify default settings`) doesn't. If the inner test fails however, an error-message still gets thrown.

Is this a bug or intended behavior?

Thanks,
lschuermann

**Comment by dejnon** [comment]
+1
I would also like to see those in `--verbose` mode.

**Comment by vlucas** [comment]
This is a known issue with nested Jasmine contexts, and will be fixed with Frisby v2 (see #316)
