### ISSUE TITLE
Destination URL may be down or URL is invalid, Error: Parse Error

### ISSUE THREAD

**Issue by bwhitty6** [vlucas/frisby#314]
I am trying to execute offline testing and am using the an http request to connect with the local server. I am having trouble trying to access the data on the server in a js file but can access in a html file. Using frisby and superagent as my frameworks I get the error:
{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
Destination URL may be down or URL is invalid, Error: Parse Error
I believe that the problem exists with my certificates bu am not sure. 
Any help would be great thanks!

**Comment by sharadJay** [comment]
You can pass strictSSL false, if there are certificate issues
```javascript
 frisby.create("Test without certificate checks")
            .post("url", {
            }, {strictSSL: false})
```

**Comment by bradleywhit** [comment]
@sharadJay This did not work, thanks for the idea though I will explore it more, do you have any other ideas?

**Comment by vlucas** [comment]
Please check this issue with v2 and the fetch API, and re-open if it is still an issue.
