### ISSUE TITLE
Custom matchers for jasmine in frisby

### ISSUE THREAD

**Issue by sharadJay** [vlucas/frisby#315]
Has anybody tries creating custom matchers for jasmine in frisby? e.g.

```
expect("").someCustomizedMatcher.(""); 
```

**Comment by JamieMason** [comment]
Have a look at [JamieMason/add-matchers](https://github.com/JamieMason/add-matchers) @sharadJay, maybe that can help. It will also make the matcher compatible with Jest should you  decide to switch to that.

**Comment by sharadJay** [comment]
@JamieMason I will get back after trying this. Will post an example for the community if successful

**Comment by sharadJay** [comment]
Works great for me. Thanks @JamieMason There are examples in the repo which any one can refer

**Comment by JamieMason** [comment]
Great! Thanks @sharadJay 🍾
