### ISSUE TITLE
frisby load testing

### ISSUE THREAD

**Issue by dayafigueroa** [vlucas/frisby#317]
Hi,

I am currently using frisby for my project's api test automation and am very pleased. So far everything is going smoothly. The only question i have is if there is going to be support for load testing. I ran into npm loadtest module...can frisby be integrated with it successfully? has anyone tried it?

**Comment by vlucas** [comment]
No, Frisby is not the tool for that job. The main blocker here is that Jasmine runs tests synchronously.

**Comment by dayafigueroa** [comment]
Thank you :)
