### ISSUE TITLE
How to post array of custom object

### ISSUE THREAD

**Issue by SanaKhawaja** [vlucas/frisby#318]
1- My post body needs to look like this
{
    "custom_arr": [
        {
            "Cust_id": "SM-G920TZKAXAR",
            "quantity": 5
        }
    ],
    "Client_id": {
    "id": "23dd6257-a6e9-47dc-8287-52af9585b81f",
    "type": "Person"
  }
}

My test looks like this

frisby.create('POST shopping cart')
  .post(URL,
  {
       "custom_arr": [
        {
            "Cust_id": "SM-G920TZKAXAR",
            "quantity": 5
        }
    ],
    "Client_id": {
    "id": "23dd6257-a6e9-47dc-8287-52af9585b81f",
    "type": "Person"
    }
  },
  {json: true},
  {
      headers: 
      { 
       'Content-Type': 'application/json',
      }
  })
  .inspectRequest()
  .inspectStatus()
  .timeout(10000000)
  .expectStatus(200)

I am getting a bad request error, how should I be passing the array 

2- How do I monitor the requests being issues through tests in Charles proxy for example?

**Comment by vlucas** [comment]
Frisby has a `inspectRequest` method you can add to the chain that will `console.log` all the data that is sent to the server.
