### ISSUE TITLE
How to wrap a frisby test on a function that returns a value

### ISSUE THREAD

**Issue by dayafigueroa** [vlucas/frisby#320]
Hi there! My situation is the following; all of my tests have a dependency on create PO, I have moved it out to its own file, I'm loading frisby first, then my function is structured as follows:
var createPO = {
  getPO: function(){
    var prodOrder;
    frisby.create('Create a new Production Order')
      .post('http://'+global.environment+'/api/orderRequest',poPayload, { json: true })
      .expectStatus(200)
      .inspectRequest()
      .afterJSON(function(json) {
         prodOrder = json.productionOrderID;
         //return prodOrder;
       })
      .toss()
//return prodOrder;
  }
};

notice that i'm trying to return prodOrder...I've tried before the .toss() and after (as shown here) with no luck....i'm getting 'undefined', any guidance would be much appreciated :). Thanks!

**Comment by vlucas** [comment]
You can only do this in v2, because of the way v1 controls and outputs the describe/it functions.
