### ISSUE TITLE
SyntaxError: Unexpected token 'const'   at c:/Users/BRANDO~1/AppData/Local/Temp/node_modules/frisby/src/frisby.js:3:0

### ISSUE THREAD

**Issue by BWBuchanan7** [vlucas/frisby#324]
So I know this is a bit of a stretch, but I was hoping I'd be able to get Frisby v2 to work using karma and karma-jasmine by browserifying and running my tests in phantomjs however I only get about 3 lines into frisby.js before I hit an error:

```
λ karma start
24 06 2016 13:29:13.799:INFO [framework.browserify]: bundle built
24 06 2016 13:29:13.820:INFO [karma]: Karma v1.0.0 server started at http://localhost:9876/
24 06 2016 13:29:13.822:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
24 06 2016 13:29:13.832:INFO [launcher]: Starting browser PhantomJS
24 06 2016 13:29:15.626:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#SX_b4YS4qWQ_fuMhAAAA with id 9845559
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at c:/Users/BRANDO~1/AppData/Local/Temp/node_modules/frisby/src/frisby.js:3:0 <- C:/Users/BRANDO~1/AppData/Local/Temp/0a30b7136e894b6e6aa3704954542ea4.browserify:39363
```

Any chance there's a solution to this?

**Comment by vlucas** [comment]
Frisby v2 uses some ES6 syntax, and thus requires Node v4.2 or higher to
run.

--
Vance Lucas
http://vancelucas.com
(405) 303-1021

**Comment by BWBuchanan7** [comment]
Thank you for the quick response.

I'll chalk this one up to one of my tools using an older version of Node. I'm not certain that I can get around this, knowing that though.

**Comment by vlucas** [comment]
I believe karma uses your system node version. Check your node version with:

```
node --version
```

**Comment by BWBuchanan7** [comment]
I believe you are correct about karma, and I am currently running node v4.4.5 but from here I am assuming the problem lies somewhere in the chain (descending from karma) of karma-jasmine, karma-browserify and karma-phantomjs-launcher which may be too much of a headache to try and troubleshoot.
