### ISSUE TITLE
How to call frisky from a callback function

### ISSUE THREAD

**Issue by SanaKhawaja** [vlucas/frisby#326]
I am trying to call frisky test from within the call back function:

util._getCookie(userId,password).then(function(result) {
                                     var newCookieCar = result + ';' + 'abc';
                                    {
                                        request: {
                                        headers:{
                                            'Content-Type':'application/json',
                                            'Cookie':newCookieCar
                                                }
                                            },
                                    timeout: (100 \* 1000)
                                    });

```
                               ////////////////////////////////////////////////////////////////////////
                                frisby.create('Make a post req)
                                .post(URL +'/abc',
                                {
                                "application": {
                                    "first_name": "Jill",
                                    "last_name": "Jack",
                                    "address": {
                                    "line1": "121",
                                    "line2": "Mickey Mouse Ave",
                                    "country": "US"
                                    },
                                {json: true})
                                .inspectRequest()
                                .inspectJSON()
                                .expectStatus(200)
                                .toss();

                            }, function(error) {
                                console.log(error);
                            });
```

but I don't see the frisky test getting executed,how can I call a frisky test from within a callback function

**Comment by vlucas** [comment]
Frisby v1 cannot be used in this way. Please have a look at v2.
