### ISSUE TITLE
Frisby v2.0 - How to return a promise from a frisby get

### ISSUE THREAD

**Issue by gmarti28** [vlucas/frisby#336]
I have a the following static method, using frisby v2

```
static getPathForCategory(categoryId){
        var sep=' > ';
        var frisby = require('frisby');

        return frisby.get('https://api.mercadolibre.com/categories/' + categoryId)
            .then(c=>{
                var bread="";
                var path=c['path_from_root']; //it's an array
                path.forEach( e=> {
                    if (bread.length>0) {
                         bread=bread+sep;
                    }
                    bread=bread+e.name;
                });
                console.log('BREAD: ' + bread);
                return bread;
        });
    }
```

My jasmine test calls the method this way: 

```
StaticUtils.getPathForCategory('MLA119279).then(bread=>{
           console.log(bread);
           (...)
```

I'm using frisby along with Selenium to perform some checks on the UI base on the results from REST api calls. In this particular case, the api call gets a list of "child" categories, and concatenate their names to form a breadcrum. 
However when I try to use that breadcrum, i get the JSON result from the api call rather than the breadcrumb calculated inside then (..) 

Is there a way to chain the results from a frisby get so I return the promise inside the then() ? 

Please advice. Thanks

**Comment by vlucas** [comment]
If you need access to the underlying Promise object, just make a `.promise()` call as the last method call in the chain to return the actual promise object.

**Comment by felipesousa** [comment]
@gmarti28 is easy, you can return the pipe to after step in promise, see the example:

```
 ...
 ...
 return frisby.get("YOUR API EXAMPLE")
    .expect('status', 200)
    .expect(...)
}) 
```

When you call your function, you will be receive the result of promise.

```
StaticUtils.getPathForCategory('MLA119279).then(bread=>{
    console.log(bread);
    (...)
}
```

👍

**Comment by vlucas** [comment]
Closing this as it appears to have been answered.
