### ISSUE TITLE
retry mechanism in "post" request

### ISSUE THREAD

**Issue by saurabh1gupta** [vlucas/frisby#338]
I'm trying to add "retry" mechanism in POST request which will automatically re-run my failed test cases after a specific wait time but it's "retry" is not triggering after failing the test cases WHILE it's working well with GET method. Can you please suggest?

Here is the code sample:

```
var frisby = require('../lib/frisby');

frisby.create('Dummy test')
  .post(URL, {
   object1: 'value1',
   object2: [{value2.a},{value2.b}]
  }, {json: true})
  .expectStatus(200)
  .retry(5, 1000) 
.toss();
```

Please suggest, if "retry" method doesn't work with POST request and what are the alternatives here?

Thanks

**Comment by vlucas** [comment]
This "retry" mechanism is in v1, and was not ported over to v2. The best way to do this might be to just put this in a function, and keep running it on failure. In v2, you can use a promise-style ".catch()" function.
