### ISSUE TITLE
ToBeType matcher always return true

### ISSUE THREAD

**Issue by alphatesla** [vlucas/frisby#34]
Example : testing a simple json like {title: 'my string'}

.expectJSON({title: function(val) { expect(val).toBeType(String); }}) => test pass
.expectJSON({title: function(val) { expect(val).toBeType(Number); }}) => test pass
.expectJSON({title: function(val) { expect(val).toBeType(Array); }}) => test pass

I

**Comment by andrecastelo** [comment]
Still happening, returning the expect function. Also happens with `toBeTypeOrNull`.

**Comment by sharadJay** [comment]
any updates on this ?

**Comment by vlucas** [comment]
I am working on the next version of Frisby, which will fix this issue. The main issue here is that Jasmine will not reliably run assertions in nested contexts.

**Comment by vlucas** [comment]
Fixed in v2. Please update.
