### ISSUE TITLE
Take Action upon Error/Failure

### ISSUE THREAD

**Issue by mthoreso** [vlucas/frisby#340]
@vlucas 
Is it possible to take an action only upon test failure?  For example, display the headers and JSON just when there is an error.

I am chaining tests:
223 tests, 447 assertions, 2 failures, 0 skipped

And would like to inspect as much as I can about the 2 failures, but not the successful tests.

Thanks.

**Comment by vlucas** [comment]
There is a setting for this in v1 called "inspectOnFailure".
