### ISSUE TITLE
frisby.js file presented on the site is not the same of installed

### ISSUE THREAD

**Issue by NadinFarbman** [vlucas/frisby#341]
Hello,
First of all I would like to thank you for your very useful project!

I have downloaded frisby and started using on jasmine-node2, but faced with a following issue:
In your github you published an frisby.js file with Matchers of jasmine2:
https://github.com/vlucas/frisby/blob/master/lib/frisby.js

but... in the installed dir of my env, I have Matchers of jasmine<2.0.0 version, for instance:

```
jasmine.Matchers.prototype.toContainJsonTypes = function(expected, isNot) {
  this.message = function() {
    return "Actual JSON types did not match expected";
  }

  // Way of allowing custom failure message - by throwing exceptions in utility function
  try {
    return _jsonContainsTypes(this.actual, expected);
  } catch(e) {
    // Fail test if there is a match failure and it is not an inverse test (for non-match)
    if(!this.isNot && !isNot) {
      this.spec.fail(e);
    }
  }
};
```

Is there reason for that?
Because, this is a cause of the "TypeError: Cannot read property 'prototype' of undefined" issue.

Of Course there is workaround the issue (copy-paste :))) ), but I was wondered to know if it is a bug or it should be so?

Thank you in advance,
Nadin

**Comment by vlucas** [comment]
Frisby v1 was not fully compatible with Jasmine v2. Please upgrade to Frisby v2.
