### ISSUE TITLE
Using expectJSON() with a regular expression

### ISSUE THREAD

**Issue by nodesocket** [vlucas/frisby#344]
How can I use `expectJSON()` with a regular expression? I'd like to do:

``` javascript
.expectJSON({
    id: /^[a-f0-9]{8}\-[a-f0-9]{4}\-[a-f0-9]{4}\-[a-f0-9]{4}\-[a-f0-9]{12}$/
})
```

**Comment by nodesocket** [comment]
Bumb. I'd be willing to work on a pr, if I get some ideas where to start.

**Comment by andreyunugro** [comment]
Another year passed by.. :)
How about something like this:
`
.expectJSON({
    id: function checkRegex(data) {
      const testRegex = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(data);
      expect(testRegex).toBe(true);
    },
  })
`

**Comment by vlucas** [comment]
In v2, you can use `.expect('bodyContains', /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/)` and it will work as expected.
