### ISSUE TITLE
how to integrate a custom cb call to db in order to set a payload field

### ISSUE THREAD

**Issue by dayafigueroa** [vlucas/frisby#349]
I have a test I need help with....it goes as follows:

frisby.create('Search Order')
  .get(global.apiRoot+'/odata/ProductionOrders/PO.GetProdOrdersSearch(jsonBody=@val)?@val=\'{"orderIds":['+db.queryDb(query, function(err, results){
if(err) {console.log(err); return cb(err); } 
console.log(results[0].OrderId);
return results[0].OrderId; 
expect(results[0].OrderId).not.toBeNull(); });+']}')

where db.query connects to the db and executes a query that returns a cb result. If i call the db.queryDb by itself i do get the value i need. But within the frisby call it doesn't. Any suggestions? ideas on how to approach this?

much thanks!

**Comment by vlucas** [comment]
Frisby is make for testing HTTP REST APIs, not database calls. You should already have a server running that Frisby hits - your tests should not need to know anything about your database.
