### ISSUE TITLE
issue in basic auth while passing it along with POST

### ISSUE THREAD

**Issue by vrushabh-shah** [vlucas/frisby#357]
I tried GET as follows which is working fine for me.

    var frisby = require('frisby')
    var url = 'https://localhost:8443';
    var api= '/api/v2/events/details'
    var endpoint = '?id=ccce2aef971f'
    var user= 'demo@demo.com'
    var pass= 'temp'

    frisby.create('GET event details based on eventid from an endpoint')
   .get(url+api+endpoint,{strictSSL: false})
   .auth(user,pass,false)
   .expectStatus(200)
   .expectHeader('Content-Type', 'application/json;charset=UTF-8')
   .toss();

============================================
**now I want to use POST method with same format but no luck in response.**

var frisby = require('frisby')
var user= 'demo@demo.com'
var pass= 'temp'
var jsonbody = {"group": "a10bbd20",
        "category":"Attack",
        "notes":"abcdddd",
        "criteria":[  {"attribute":"PATH" ,"operator": "EQUALS", "value":"/Account/demo.aspx" }]
        }

frisby.create('TEST POST')
.post('https://localhost:8443/api/v2/rule-settings/pointwise',jsonbody,{ json: true },{ headers: { 'Content-Type': 'application/json' }},{strictSSL: false})
.auth(user,pass,false)
### 
.expectStatus(201)
.toss(); 

==================================================

I tried to do POST request by **storing cookie from previous response** but still same error for time out

var frisby = require('frisby')
var url = 'https://localhost:8443';
var api= '/api/v2/events/details'
var endpoint = '?id=ccce2aef971f'
var user= 'demo@demo.com'
var pass= 'temp'

var loginState = {
};

    frisby.create('GET event details based on eventid from an endpoint')
    .get(url+api+endpoint,{strictSSL: false})
    .auth(user,pass,false)
        .after(function (body,res) {
            var cookie = res.headers['set-cookie'];
            console.log(cookie);
            loginState.user1 = {}; // build an object for user 1
            loginState.user1.cookie = cookie;                
            var jsonbody = {"group": "a10bbd20",
                            "category":"Attack",
                            "notes":"abcdddd",
                            "criteria":[  {"attribute":"PATH" ,"operator": "EQUALS", "value":"/Account/demo.aspx" }]
                            }

        frisby.create('TEST POST')
        .post('https://localhost:8443/api/v2/rule-settings/pointwise',jsonbody,{ json: true },{strictSSL: false})
        .addHeader('cookie', loginState.user1.cookie) 
        .addHeader('Content-Type', 'application/json')
        .inspectRequest()
        .expectStatus(201)
        .toss();
        })

        .toss();

output I am getting is

Message:
Expected 500 to equal 200.
Stacktrace:
Error: Expected 500 to equal 200.
at null.<anonymous> (C:\Users\Administrator\Documents\TestSuite\node_modules
\frisby\lib\frisby.js:493:42)
at null.<anonymous> (C:\Users\Administrator\Documents\TestSuite\node_modules
\frisby\lib\frisby.js:1074:43)
at Timer.listOnTimeout (timers.js:92:15)

**Comment by emre-yildirim** [comment]
did you tried adding headers to your post method like below

{ json: true,
  headers: {
      'Content-Type': 'application/json',
      'cookie', loginState.user1.cookie
}

**Comment by vrushabh-shah** [comment]
yup i tried that but still getting same error. only difference i found is passing cookie from loginState.user1.cookie to request.
I used inspectRequest to check it out both the time.
_Inspect request while header being added throuh addheader_


.{ json: true,
  uri: 'https:/localhost8443/api/v2/rule-settings/pointwise',
  body:
       {"group": "a10bbd20",
         "category":"Attack",
     notes: 'abcdddd',
     criteria: [ [Object] ] },
  method: 'POST',
  **headers:
   { cookie: [ 'JSESSIONID=BBD0C0B44BD3851235F307008CC78C67; Path=/; Secure; Htt
pOnly' ],  //seems like it is passing in array
     'content-type': 'application/json' },**
  inspectOnFailure: false,
  baseUri: '',
  timeout: 5000 }


_Inspect request while header being added in post method_


.{ json: true,
  uri: 'https:/localhost8443/api/v2/rule-settings/pointwise',
  body:
       {"group": "a10bbd20",
         "category":"Attack",
     notes: 'abcdddd',
     criteria: [ [Object] ] },
  method: 'POST',
 **headers:
  { 'content-type': 'application/json',
    cookie: 'JSESSIONID=BE4B623DEA3C95A4293ECB7D0E5C505C; Path=/; Secure; HttpO
nly' },** 
 inspectOnFailure: false,
  inspectOnFailure: false,
  baseUri: '',
  timeout: 5000 }

**Comment by emre-yildirim** [comment]
hmmm, I see. I beleive you already tried this way, just to make sure one more time, you tried the way below right?? 

frisby.create('TEST POST')
.post('https://localhost:8443/api/v2/rule-settings/pointwise',jsonbody,**{ json: true, headers: { 'Content-Type': 'application/json' }}**,{strictSSL: false})
.auth(user,pass,false)

.expectStatus(201)
.toss();


and also what about that strictSSL:false parameter, I've never seen it before? is it something related to https certificate when working on local env?? 
If so maybe you can try removing it and adding the environment variable below to your path, to bypass certificate,
NODE_TLS_REJECT_UNAUTHORIZED = "0".

**Comment by vrushabh-shah** [comment]
That works. 
I used strictSSL: false because mine is QA server which has non-trusted SSL certificate. I  My request works after i put strickSSL in the end initially.

for POST even if strictSSL is there, this environment variable works perfectly fine . Thanks for resolving it. Much Appreciated

**Comment by emre-yildirim** [comment]
Happy to help :)
