### ISSUE TITLE
Problem in the POST request

### ISSUE THREAD

**Issue by webant** [vlucas/frisby#358]
That request  returns success:
`.post(webUrlAccountApi + '/' + 'RefreshSession?UserName=' + username + '&AccessToken=' + AccessToken + '&DeviceType=' + DeviceType + '&DeviceToken=' + DeviceToken)`
All right!

But...
That request  returns "Error: Expected 400 to equal 200.":
```
.post(webUrlAccountApi + '/' + 'RefreshSession?', {
          UserName: username,
          AccessToken: AccessToken,          
          DeviceType: DeviceType,
          DeviceToken: DeviceToken
        })
```

What is the reason?

**Comment by emre-yildirim** [comment]
I believe its because your body is missing from the .post method.

Try the code below

.post(webUrlAccountApi + '/' + 'RefreshSession?',{} , {
    headers:{
          UserName: username,
          AccessToken: AccessToken,          
          DeviceType: DeviceType,
          DeviceToken: DeviceToken
        }
})

**Comment by webant** [comment]
Thanks for the answer. As it turned out, the problem was by the special conditions on the server with nginx.
