### ISSUE TITLE
expectBodyContains doesn't work with JSON

### ISSUE THREAD

**Issue by Fishbowler** [vlucas/frisby#362]
I'm trying to test if one particular object property contains a particular substring.
With no expectJSONContains, I went for expectBodyContains.
When this is used with a JSON body, it raises an error:
```
TypeError: haystack.indexOf is not a function
    at .<anonymous> (d:\git\testing\frisby\node_modules\frisby\lib\frisby.js:545:42)
```
Line in question is this:
```
expect(self.current.response.body).toContain(content);
```
which could be replaced with 
```
var responseBody = self.current.response.body
if(typeof responseBody === "Object"){
    responseBody = JSON.stringify(responseBody);
}
expect(responseBody).toContain(content);
```

**Comment by vlucas** [comment]
Try v2. Frisby v1 is no longer supported.
