### ISSUE TITLE
v2 - Cannot configure for proxy

### ISSUE THREAD

**Issue by Fishbowler** [vlucas/frisby#363]
In the v2 alpha (installed via `npm install frisby@next` ), I cannot configure my local tests to use a proxy. 

Here, I've tried both methods simultaneously, but I've tried them individually too.

```
var auth_header = 'Basic ' + bearer_creds_base64;

frisby.globalSetup({
    request: {
        proxy: 'http://127.0.0.1:8888'
    }
})

describe('Twitter', function(){
    it('Will auth me', function(done){
        frisby
            .setup({
                request: {
                    proxy: 'http://127.0.0.1:8888'
                }
            },true)
            .post('https://api.twitter.com/oauth2/token',{
                body: {grant_type: "client_credentials"},
                headers:{Authorization: auth_header}
            })
        .expect('status', 200)
        .done(done)
    });
});
```

**Comment by Fishbowler** [comment]
Nope. Solved it. Still trying to use `request` when it's been replaced with `node-fetch`

var HttpsProxyAgent = require('http-proxy-agent');

...
var auth_header = 'Basic ' + bearer_creds_base64;

frisby.globalSetup({
    request: {
        agent: new HttpsProxyAgent('http://127.0.0.1:8888')
    }
})

describe('Twitter', function(){
    it('Will auth me', function(done){
        frisby
            .post('https://api.twitter.com/oauth2/token',{
                body: 'grant_type: "client_credentials"',
                headers:{
                    'Authorization': auth_header,
                    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
                }
            })
        .expect('status', 200)
        .done(done)
    });
});

**Comment by vlucas** [comment]
Whoohoo! Awesome! :)
