### ISSUE TITLE
Nested tests in v2 not as flexible as afterJSON()?

### ISSUE THREAD

**Issue by bkimminich** [vlucas/frisby#366]
## v0
```
frisby.create('POST new complaint')
  .addHeaders(authHeader)
  .post(API_URL + '/Complaints', {
    message: 'My stuff never arrived! This is outrageous'
  }, { json: true })
  .expectStatus(200)
  .expectHeaderContains('content-type', 'application/json')
  .expectJSONTypes('data', {
    id: Number,
    createdAt: String,
    updatedAt: String
  })
  .afterJSON(function (complaint) {
    frisby.create('GET existing complaint by id is forbidden')
      .addHeaders(authHeader)
      .get(API_URL + '/Complaints/' + complaint.data.id)
      .expectStatus(401)
      .toss()
    frisby.create('PUT update existing feedback is forbidden')
      .addHeaders(authHeader)
      .put(API_URL + '/Complaints/' + complaint.data.id, {
        message: 'Should not work...'
      }, { json: true })
      .expectStatus(401)
      .toss()
    frisby.create('DELETE existing feedback is forbidden')
      .addHeaders(authHeader)
      .delete(API_URL + '/Complaints/' + +complaint.data.id)
      .expectStatus(401)
      .toss()
  }).toss()
```

## v2

How am I supposed to implement the same parallel execution of those three different `401`-tests after the outer request as been processed? In v2 I now need to return the inner `FrisbyResponse` - how about offering to return a `FrisbyResponse[]` alternatively?

**Comment by vlucas** [comment]
You can use a `Promise.all()` call with the 3 Frisby tests. You might have to call `.promise()` after them to ensure they return the proper `Promise` object to Promise.all.

**Comment by bkimminich** [comment]
I'll try to first make my tests less dependent on each other and for those where it doesn't work I'll go with your `Promise.all`. Thanks!

**Comment by bkimminich** [comment]
I was able to rather split my nested bunch of tests into two-step-pairs, and with the promise of the `Promise.all()` being the solution to similar problems, I'm closing this issue.
