### ISSUE TITLE
Override frisby2 encoding URL automatically

### ISSUE THREAD

**Issue by bkimminich** [vlucas/frisby#371]
In v0 you had to encode all URIs yourself which was sometimes inconvenient but sometimes also very useful for some crazy tests like the one below:
```
  it('GET a file whose name contains a "/" fails with a 403 error', function (done) {
    frisby.get(URL + '/ftp/%2fetc%2fos-release%2500.md')
      .expect('status', 403)
      .expect('bodyContains', 'Error: File names cannot contain forward slashes!')
      .done(done)
  })
```
In v2 all URIs are automatically encoded, which is convenient and perfectly fine for _most_ cases, but unfortunately breaks my test above, because the URL becomes ` /ftp/%252fetc%252fos-release%2500.md`.

In the above example I cannot simply send the URI unencoded and let frisby to the work, because `/ftp//etc/os-release%00.md` would be encoded into `/ftp//etc/os-release%2500.md` which is _not_ what I want to test.

As mentioned this is a pretty rare and crazy special case, but it would be really helpful to have an option for encoding which should be `true` by default:
```
frisby.get(URL + '/ftp/%2fetc%2fos-release%2500.md', { encodeURI: false })
```

**Comment by vlucas** [comment]
Yeah I see the issue. I don't want to add an object of options to the `get` method like that though, because then I would also have to add it to put, post, delete, etc. I think instead, I would prefer to make people use the `fetch` method directly with a 3rd parameter of options, or else do set some options with the `setup` method for that single test.

**Comment by vlucas** [comment]
Another option I just thought of that would at least solve your specific case right now is to check for unicode characters, and only auto url-encode if unicode characters are present, or if the string is not already url encoded.

**Comment by bkimminich** [comment]
Having to use `frisby.fetch()` in this case would be totally okay if that offers some config options for special cases. No need to pollute the convenience wrappers for this.

Your second option sound convenient for my case but I guess it will cause trouble to other people with other special cases... :bug:

**Comment by bkimminich** [comment]
```
  it('GET a file whose name contains a "/" fails with a 403 error', function (done) {
    frisby.fetch(URL + '/ftp/%2fetc%2fos-release%2500.md', {}, { encodeURI: false })
      .expect('status', 403)
      .expect('bodyContains', 'Error: File names cannot contain forward slashes!')
      .done(done)
  })
```
Having the empty `node-fetch` params in between looks a bit weird, but mixing frisby's own with theirs in probably asking for side-effect trouble... :grin:
