### ISSUE TITLE
multipart/form-data gives wrong header or empty body

### ISSUE THREAD

**Issue by bkimminich** [vlucas/frisby#372]
## `FormData`-body = wrong `content-type` header
I would expect the following test to work because under the hood `node-fetch` should determine that the `body` is a form and declare it as `multipart/form-data`:
```
  it('POST file valid for client and API', function (done) {
    file = path.resolve(__dirname, '../files/validSizeAndTypeForClient.pdf')
    form = new FormData()
    form.append('file', fs.createReadStream(file))

    frisby.post(URL + '/file-upload', { body: form })
      .expect('status', 204)
      .done(done)
  })
```
In reality is becomes a `application/json`-body which I suspect is rather frisby's than node-fetch's doing.

## Passing explicit headers = empty body
Passing in `{ headers: form.getHeaders(), body: form }` makes the request become a `multipart/form-data` as you would expect, but now all I get as a request body in my receiving application is `{ }`.

### Working example in frisby v0
see https://github.com/bkimminich/juice-shop/blob/master/test/api/fileUploadSpec.js

### Not working example in frisby v2
see https://github.com/bkimminich/juice-shop/blob/frisby2/test/api/fileUploadSpec.js

> Using `form-data` v2.2.0 instead of v1.1.0 did not solve the problem for me either. Currently `frisby2` branch uses v1.1.0 like it was originally.

**Comment by vlucas** [comment]
Thanks - I will take a look at this. I definitely want to get form uploads working.

**Comment by vlucas** [comment]
I think this is because if the body is not JSON, Frisby returns it as text. Looking into this now.

**Comment by bkimminich** [comment]
Works like a charm now! Thanks!
