### ISSUE TITLE
frisby.delete is not a function

### ISSUE THREAD

**Issue by Tomotomo-chan** [vlucas/frisby#387]
Hi,
I'm updating my unit test from frisby v.0.8.5 to v.2.0.2, and I encounter a problem with frisby.delete.
I'm doing this test:

```
describe("POST /users",
    function ()
    {
		it("should success with simple valid user",
		function (done)
		{
			var			user = get_user_object(user_nb++);
			frisby.post(basic_url + "/users", user) // POST a user
				.then(function (json)
				{
					var		_id = json.body._id;

					expect(json.status).toBe(200);
					expect(json.body.name).toEqual(user.name);
					expect(json.body.mail).toEqual(user.mail);
					expect(_id).toBeTruthy();

					if (!_id)
						return ;
					frisby.delete(basic_url + "/users/" + _id + "?token=" + admin_token) // trying to delete the user after the test
						.done(done);
				})
				.done(done);
		});
	});
```

And I get this error:

> Message:
> 
>      TypeError: frisby.delete is not a function
>    Stacktrace:
>      TypeError: frisby.delete is not a function
>     at jasmine.Spec.<anonymous> (/home/tomo-chan/Projets/pgb-app/back-end/tests/spec/api_user_spec.js:91:21)
>     at jasmine.Spec.<anonymous> (/usr/local/lib/node_modules/jasmine-node/lib/jasmine-node/async-callback.js:45:37)

I'm probably doing something wrong but I can't guess what :/ I'm a noob with frisby. Is it jasmine which doesn't support it anymore ? I have jasmine v2.7.0.
Thank you for all your work.

_(Sorry about my bad english)_

**Comment by H1Gdev** [comment]
Hi @Tomotomo-chan 
In 2.x delete method is changed to del method.

```javascript
frisby.del(basic_url + "/users/" + _id + "?token=" + admin_token) // trying to delete the user after the test
.done(done);
```

**Comment by Tomotomo-chan** [comment]
Hi!
Thank you so much. Do I miss the frisby's documentation ?

**Comment by H1Gdev** [comment]
@Tomotomo-chan 
I understood from source code.
As far as I know, 2.x document does not exist.

**Comment by Tomotomo-chan** [comment]
@H1Gdev 
I didn't think to look at the source code... my bad. Thank you again for your help. :)

**Comment by vlucas** [comment]
I am working on the docs. They will be updated an online within a few weeks.

**Comment by koooge** [comment]
hello :)
why `frisby.del`? I want to write `frisby.delete` instead of `frisby.del`
