### ISSUE TITLE
Documentation is incorrect in regards to test naming schema

### ISSUE THREAD

**Issue by SamAtAllegion** [vlucas/frisby#394]
Jest does not run any test files with a filename in the format of "test_spec.js", filenames plainly named "spec.js" or "test.spec.js" do work. As a first time Jasmine and javascript user this was very difficult to figure out from the error messages from Jest.

**Comment by vlucas** [comment]
Updated the README in 646e9c968491ce8ca07a4ced9522197f16571b0d
