### ISSUE TITLE
FrisbySpec should be exported to allow for monkey patching

### ISSUE THREAD

**Issue by snowe2010** [vlucas/frisby#398]
Is there any way FrisbySpec could be exported from `frisby` so that we can monkey patch our own methods on? I'd like to add a method `log()` that reads environment variables/config files to choose whether to log body, headers, request, response, etc (I don't think you should have to add and remove code to get logs). Currently FrisbySpec is not exported and therefore isn't extendable.

**Comment by vlucas** [comment]
I don't like inheritance. You should consider instead using a [Proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) so you can implement your own methods, and then just pass through the rest of the methods you don't override.

**Comment by snowe2010** [comment]
With a proxy I'd need to provide the proxy to every file that needed the functionality correct? 

```
let frisby = require('frisby');
const log = require('./myfunctions.js');
let proxyfrisby = new Proxy(frisby, log())
// use proxyfrisby from now on. 
```

**Comment by vlucas** [comment]
Yes, that is correct.

**Comment by snowe2010** [comment]
So ignoring the solution above, which I have to provide to every file, I can get around `FrisbySpec` not being exported by doing one of two things. 

1. Using `__proto__` to get around it. 
```js
let frisby = require('frisby');
const logger = require('./tools').logger;

await function addLogger() {
  let frisbySpec = frisby.setup();
  frisbySpec.__proto__.log = logger
}
// Customize Frisby.js for the StackExchange REST API
module.exports = {addLogger};
```

2. Loading the file directly and modifying the prototype there. 
```js
const FrisbySpec = require('../../node_modules/frisby/src/frisby/spec.js');
FrisbySpec.prototype.log = mylogfunctionhere;
```

both of these are global, the first I need to require that file, everywhere I want my log function, the second is just global by default. 
Seeing as how there are gross hacks around this, the reasoning behind not exporting `FrisbySpec` does not make sense to me, especially because this isn't inheritance in any sense of the word. It's monkey-patching, though I could see how it could be confused as prototypal inheritance and used by other devs as such.

**Comment by vlucas** [comment]
I still don't like inheritance as the solution, but it can be a convenient way to add a few methods when needed. Please check the accompanying test in the commit for recommended implementation.

**Comment by snowe2010** [comment]
Fantastic. Looks like a good way to implement without causing issues globally. Thanks!
