### ISSUE TITLE
[SyntaxError: Unexpected token =] for all tests after update to the last version

### ISSUE THREAD

**Issue by DmitryMyadzelets** [vlucas/frisby#399]
I have a bunch of tests for APIs using `frisby` (version 0.?). After updating to the version show below all the tests fail with the same message `[SyntaxError: Unexpected token =]`. Even with a test file with no code, e.g. `test.spec.js` which only includes the `frisby` module:
````javascript
const frisby = require('frisby');
````
````sh
jasmine-node ./test.spec.js
Exception loading: /..path-to-tests.../tests/test.spec.js
[SyntaxError: Unexpected token =]
````
My configuration:

````sh
npm ls -g | grep frisby
├─┬ frisby@2.0.5

npm ls -g | grep jasmine
├─┬ jasmine-node@1.14.5
│ ├─┬ jasmine-growl-reporter@0.0.3
│ ├── jasmine-reporters@1.0.2

node -v
v5.12.0
````

**Comment by DmitryMyadzelets** [comment]
This version of `jasmine` requires the `node verson >=6` as show in `package.json`. The correspondent warning doesn't appear when `frisby` is installed (may be due to the outdated `npm`). After updating the node to the required version the issue gone.

**Comment by vlucas** [comment]
Thanks for posting the answer here for others to find! 👍
