### ISSUE TITLE
Capture .inspectBody() response. 

### ISSUE THREAD

**Issue by barryviljoen** [vlucas/frisby#403]
I am trying to capture/pass a token that is generated in plain text. I cannot use afterJSON(). Using inspectBody() I see the token. However I need to pass that token onto another frisby request or store it as a variable. 

I am using:

frisby.create("creating a token")
  .get(‘some url’ )
  .expectStatus(200)
  .inspectBody()
  .toss()

the response is in plain text(non JSON)

How to I capture the response.

**Comment by vlucas** [comment]
You can use `after`, which works similar to `afterJSON`.
