### ISSUE TITLE
JSon Comparision

### ISSUE THREAD

**Issue by mistralol** [vlucas/frisby#419]
I cannot seem to get a simple response comparison to work on a response from the server.

In this case the server just returns the json { "Ping" : "Pong" }

I have the following test. which fails on ".expect('json', 'Ping' , 'Pong' )"
The following normal jasmine expect seems to work fine.

```javascript
        it('Ping - Data', function(done) {
                frisby.get(utils.URL('/ping'))
                        .expect('status', 200)
                        .expect('jsonTypes', {
                                Ping : frisby.Joi.string()
                        })
                        .expect('json', 'Ping' , 'Pong' )
                        .then(function(res) {
                                var json = JSON.parse(res._body);
                                expect(json["Ping"]).toEqual("Pong");
                        })
                        .catch(function(err) { done.fail(err); })
                        .done(done);

        });
```

**Comment by H1Gdev** [comment]
Hi @mistralol 
I think that response Content-Type does not have 'application/json'.
Because above 'normal jasmine expect' has passed.

**Comment by mistralol** [comment]
Server side express code however looks like this

app.get('/ping', function (req, res) {
        res.status(200);
        res.json('{ "Ping" : "Pong" }');
});


Content-Type definatly is set to application/json in the server response. In fact this is the endpoint of the request you can verify it yourself!

https://api.banhosts.com/ping

**Comment by H1Gdev** [comment]
Hi @mistralol 

Response is the following.
```
"{ \"Ping\" : \"Pong\" }"
```

Please fix server side code.
```js
app.get('/ping', function (req, res) {
res.status(200);
res.json({ "Ping" : "Pong" });  // Here
});
```

**Comment by mistralol** [comment]
So can you explain why the frisby test fails. Yet the normal json parse with expect passes? As well as the other 3-4 clients that also work with it?

**Comment by H1Gdev** [comment]
@mistralol 
response is following.
```
"{ \"Ping\" : \"Pong\" }"
```
convert.(use JSON.parse())
type is string.
```
"{ Ping: 'Pong' }"
```

You want to send JSON object.
response is following.
```
{ "Ping" : "Pong" }
```

if receive JSON object, frisby will produce results as expected.

**Comment by mistralol** [comment]
Yup both of which are correct json formats. All libraries I have come across have dealt with this except frisby. Its event an example case in the rfc and spec. 

Example: in node shell.

 > JSON.parse("{ \"Ping\" : \"Pong\" }");
{ Ping: 'Pong' }
>

> eval("var x = { \"Ping\" : \"Pong\" }");
undefined
> x
{ Ping: 'Pong' }

Either way I am not arguing abut it any more. I think it would improve frisby if you supported it. But that is your choice. I don't care either way ..... But I will make you aware some json writers do this will all outputs.

**Comment by H1Gdev** [comment]
@mistralol 
I think that you are a little misunderstanding!!

equivalent js code is following.
```js
var http_response = '"{\\"Ping\\":\\"Pong\\"}"';  // HTTP Response from server.
console.log(typeof http_response);  // string

var frisby_response = JSON.parse(http_response);  // Parse in frisby.
console.log(typeof frisby_response);  // string

var json = JSON.parse(frisby_response);  // then function in this issue sample code.
console.log(typeof json);  // object
```

**Comment by vlucas** [comment]
Frisby - like any other REST API client - expects you to return valid JSON from the server, not a string that then has to be run though `JSON.parse()` again. If you return valid JSON, this works in Frisby. There is no error here with Frisby. Please update your server response as @H1Gdev has instructed and it will work.

Please keep in mind that since your are sending this improperly from your server as your API response, **every client that consumes your API will have to implement a fix specifically for it**, when this can be fixed on your end by removing two characters. This will not be done in Frisby.
