### ISSUE TITLE
Invalid json response body - How to log the server response?

### ISSUE THREAD

**Issue by exetera** [vlucas/frisby#428]
Hi,
I probably have an error on my server, because I get this from frisby:

```
FetchError: invalid json response body at ...
```

The problem is that I'm not able to see the server response, so I cannot understand what's going wrong.

How can I log the server response using Frisby? I tried to do this in the _then_ function, without success:

```
frisby.use(spec => spec.setup({ request: { headers: { 'Token': token1 } } }))
    .post(BASE_URL + 'purchase', purchase)
    .expect('status', 409)  
    .then(res => {
      console.log(res);
    })
    .done(done);
```

Thanks

**Comment by exetera** [comment]
Searching online I found the _inspectBody()_ method, but it doesn't work to me.

Here my piece of code:

``

**Comment by vlucas** [comment]
Try `inspectResponse()` and see what that ouputs.

**Comment by H1Gdev** [comment]
@vlucas 

For example, this issue will occur in response to the following invalid json response.

**Response**
```json
{"aaa":}
```

**Error message**
```
    FetchError: invalid json response body at http://xxx/issue.428 reason: Unexpected token } in JSON at position 7

      at node_modules/node-fetch/lib/body.js:48:31
```

Error in node-fetch Response.json() method.(call JSON.parse() method.)

**Comment by exetera** [comment]
@vlucas 
I tried but nothing in output

here my code
```
it('User1 - Creating a new purchase with an user as productor - FAIL', function (done) {
  frisby.use(spec => spec.setup({ request: { headers: { 'Token': token1 } } }))
    .post(BASE_URL + 'purchase', fakePurchase)
    .inspectRequest()
    .inspectResponse()
    .expect('status', 409)
    .done(done);
});
```

here the output
```
 ● User1 - Creating a new purchase with an user as productor - FAIL

    FetchError: invalid json response body at http://localhost/app/purchase reason: Unexpected token < in JSON at position 0
      
      at node_modules/node-fetch/lib/body.js:48:31
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by vlucas** [comment]
From the error message, it seems like HTML is being returned from the API endpoint. This would cause the internal `res.json()` call to fail, which means any other methods in the chain after that would not execute. Seems like we need a better way to handle this case. Can you try attaching a custom `catch()` call to the chain and see what it gives you?

```
it('User1 - Creating a new purchase with an user as productor - FAIL', function (done) {
  frisby.use(spec => spec.setup({ request: { headers: { 'Token': token1 } } }))
    .post(BASE_URL + 'purchase', fakePurchase)
    .catch(err => {
      console.log('Error!', err);
    })
    .expect('status', 409)
    .done(done);
});
```

**Comment by exetera** [comment]
Hi,
attaching the custom `catch()` you suggested, the test successes and nothing interesting is printed in the console..

Piece of code:
```
it('User2 - Joining the purchase', function (done) {
  frisby.use(spec => spec.setup({ request: { headers: { 'Token': token2 } } }))
    .post(BASE_URL + 'userxacquisto', partecipazioneAcquisto)
    .catch(err => {
      console.log('Error!', err);
    })
    .expect('status', 200)
    .done(done);
});
```

Output:
```
Error! FetchError {
      name: 'FetchError',
      message: 'invalid json response body at http://localhost/server/userxacquisto reason: Unexpected token < in JSON at position 0',
      type: 'invalid-json' }
```

The error is printed but I need the server response to analyze the problem. 

I guess that the error is caused by some warnings that server sends to client (ie. index not found, etc) and this warning should be analized to solve.

Thanks
