### ISSUE TITLE
setup() not working for headers 

### ISSUE THREAD

**Issue by tony-gutierrez** [vlucas/frisby#430]
I'm trying to do a get call using setup() exactly as described here: https://www.frisbyjs.com/setup.html

globalSetup() works and sends headers. Setup() does not send the headers? 2.0.11

**Comment by tony-gutierrez** [comment]
It looks like the setup has to go before the get, and the docs have it the other way.

**Comment by vlucas** [comment]
Noted, and just updated the docs. Sorry for the confusion there.

**Comment by H1Gdev** [comment]
@vlucas 
https://www.frisbyjs.com/setup.html

There are unnecessary dots in example codes.
```js
// The 'setup' function only affects a single test
it ('runs setup only for a single test', function (done) {
  frisby.  // <-Here
    .setup({
      request: {
        headers: {
          'Authorization': 'Basic ' + Buffer.from("username:password").toString('base64')
        }
      }
    })
    .get('http://api.example.com')
    .expect('status', 200)
    .done(done);
});
```

**Comment by vlucas** [comment]
Updated again :).
