### ISSUE TITLE
TypeError: First argument must be a string or Buffer when using formData

### ISSUE THREAD

**Issue by neelay** [vlucas/frisby#437]
I have a put function which requires form data a mix of file uploads and some values. But when I send this Frisby request, I get the following error: 
"TypeError: First argument must be a string or Buffer when using formData"

How do I resolve this issue. 

`
        describe('Modify', function() {

    it('Modify', function (done) {

    let logoImage   =  __dirname + '/settings/logo.png';
    let mainBGImage = __dirname + '/settings/mainBG.png';
    let textInputBGImage = __dirname + '/settings/textInputBG.png';

    let form  =  frisby.formData();

    form.append('fontFamily', 'Roboto');
    form.append('isLight', true);
    form.append('organizationLogo', fs.createReadStream(logoImage));
    form.append('isBackgroundImage', true);
    form.append('backgroundImage', fs.createReadStream(mainBGImage));
    form.append('backgroundColor', '#e9e9e9');
  

    frisby.put(myEndpoint, {
              body: form
            })
            .expect('status', 200)
            .then(function (res) {
              console.log(res)
            })
            .done(done)
      }, 10000);
     });
`

**Comment by vlucas** [comment]
You cannot send boolean values to the server using form data - everything is sent over as either a string or multipart/form-data.

So this needs to be changed to a string instead:
```
form.append('isLight', true);
```

**Comment by neelay** [comment]
awesome thanks for your quick response. Works now.
