### ISSUE TITLE
2.0 Types Release

### ISSUE THREAD

**Issue by christopherwoodland** [vlucas/frisby#444]
When will the typings for 2.0 be released?

**Comment by vlucas** [comment]
I am not sure what you mean. Can you expand on that a bit?

**Comment by cwoodland** [comment]
Hi,

Thanks for getting back.
We are using typescript to write our tests.  The typings for version 0.8.0 are available, but the typings for version 2.0.0 + do not appear to be.  I didn’t know if you may have information about when those typings definition files might be released??

**Comment by vlucas** [comment]
Ah, right. The typings were user-contributed. I do not use TypeScript, and Frisby is not written in it either. If you want to contribute the typings yourself though, I would be happy to merge them in.

**Comment by simonua** [comment]
Adding link to [@types/frisby](https://www.npmjs.com/package/@types/frisby) for the record.

**Comment by cwoodland** [comment]
Thanks.
I am going to take a stab at creating these files and will get back with you.

**Comment by cwoodland** [comment]
Hi,
I created a PR for the typings for 2.0
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23937
In hindsight I feel like I should have waited a little while longer before submitting the PR, BUT,  oh well it is out there and being assessed.
If you have time do you mind giving the PR a once over??

**Comment by roydekleijn** [comment]
can you provide an example on how to use this with typescript

**Comment by simonua** [comment]
@roydekleijn, run `npm i @types/frisby`. By default, TypeScript includes all types in `node_modules\@types\*`, so they are available in your TS source files without having to be explicitly declared in _tsconfig.json_ (unless you purposely define your own `types` array there).

**Comment by roydekleijn** [comment]
ok super, but how do the import statements look like ?

**Comment by simonua** [comment]
@roydekleijn, my apologies, but are you asking for how to using the types for frisby or frisby itself?

**Comment by simonua** [comment]
Also, I think this issue can be closed, @cwoodland, as @types/frisby was released. [2.0.1 is latest](https://www.npmjs.com/package/@types/frisby).

**Comment by cwoodland** [comment]
Agree this can be closed
