### ISSUE TITLE
Do multipart forms work with version 1 of Frisby?

### ISSUE THREAD

**Issue by robbsherwin** [vlucas/frisby#445]
I have two projects that I use Frisby for - the first is on the latest version and everything works great. We have one "legacy" project on version 1. We have been attempting to do document uploads with multipart forms. Does this work on this version? (If so and there's an example somewhere, I just haven't found it but would love to see it.) Thanks!

**Comment by vlucas** [comment]
Yes, there is a way to do it, but not the same way with FormData.

Check out the `[request](https://www.npmjs.com/package/request)` docs since that is what Frisby v0.8x uses.

**Comment by robbsherwin** [comment]
Thank you very much!
