### ISSUE TITLE
Can't get V2 to not follow redirects

### ISSUE THREAD

**Issue by JohnKallies** [vlucas/frisby#448]
We are trying to test the location of a redirected URL (the HTTP redirect in question being a 307). Our assumption is to not follow redirects. That said, we found this example here testing a 301 redirect in the old Frisby API: https://github.com/vlucas/frisby/issues/174

Based on the new API, we would expect this test to look something like:
```
const frisby = require('frisby');

// We also tried this approach , back in frisby 0.8-ish
frisby.globalSetup({
    request: {
        followRedirect: false,
    }
});

describe('tests', function () {
    it('301 test', function (doneFn) {
        frisby
            .setup({
                request: {
                    followRedirect: true
                }
            })
            .get('http://httpbin.org/status/301')
            // also tried  get('http://httpbin.org/status/301', request: { followRedirect: true })
            .inspectStatus()
            .expect('status', 301)
            .done(doneFn)
    })
})
```

But this returns a 200, which seems to be the status of the followed redirection.

Does Frisby still support this kind of test? We did it before in version 0.8-ish by looking at this.current.response.headers.location from within an after().

Thank you

**Comment by H1Gdev** [comment]
@JohnKallies 

In v2, please set the following.
```js
const frisby = require('frisby');

frisby.globalSetup({
    request: {
        redirect: 'manual'
    }
});

describe('tests', function () {
    it('301 test', function (doneFn) {
        frisby
            .setup({
                request: {
                    redirect: 'manual'
                }
            })
            .get('http://httpbin.org/status/301')
            .inspectStatus()
            .expect('status', 301)
            .done(doneFn)
    })
})
```

**Comment by JohnKallies** [comment]
Perfect! Thank you!

For others reading later, we did not need a globalSetup and a test-level setup, I was only trying to illustrate things we had tried. We succeeded with only using a globalSetup.

**Comment by H1Gdev** [comment]
If you always do not redirect, please set it with [globalSetup](https://www.frisbyjs.com/setup.html).
Otherwise, please set it with [setup](https://www.frisbyjs.com/setup.html) or [HTTP Request params](https://www.frisbyjs.com/http.html).
