### ISSUE TITLE
 Frisby : My API should download a file but I could not using Frisby 

### ISSUE THREAD

**Issue by VeeNaa** [vlucas/frisby#449]
URI: https://{{url}}/mysource/download/<ID> 
Method : Get 
Headers : Content-Disposition:attachment;filename=Activation_tenantId_qradarId.json
Authorization:{{bearerT}}
Accept:application/json
Content-Type:application/json

But from Postman I can do Saveand Download But not sure How to do with frisby 

I tried res.download but it shows the output on the console But I want the file to be downaloded in a location .Please Share the Code 

get(apadmin_url+mysource+'/download/'+oneSrc155)
   .addHeader('Authorization',header_auth)
   .addHeader('Content-Disposition','attachment;filename=/1.json')
   .expectStatus(200)
   .timeout(20 * 1000)
     .afterJSON(function (req, res, next) 
   {   
    var filePath = "/"; 
    var fileName = "salesReport.json"; 
    res.download(filePath, fileName);    
    next();
})
  .toss();
   })
  //End

**Comment by koooge** [comment]
Unfortunately, v0.8x would not be supported anymore honestly. Please use frisby 2.x instead. Thank you for the report.
