### ISSUE TITLE
Substitute of jasmine-node --config flag cli option when using jest as a test runner and did not get object response.request

### ISSUE THREAD

**Issue by avne31** [vlucas/frisby#464]
Hi,

I was using jasmine-node to run Frisby test in past and trying to update Frisby specs with latest Frisby package and jest as a test runner.

I am stuck on these two problems -
First: I used --config flag to assign the value to the environment variable and used these variables in my Frisby specs.

I used this command to run specs in past:
`jasmine-node mytest_spec.js --config arg1 value1 --config arg2 value2`

I did not get the substitute of --config flag cli option when using jest as a test runner.

Second:
`.after(function(err, res, body) {
    if(err) {
       log(err);
   }else {
        log(res.request, res.request.body, res);
  }
})`

I did not get the substitute  to log objects "res.request",  "res.request.body".

Thanks.

**Comment by H1Gdev** [comment]
A solution to **First**.

Use [globals](https://facebook.github.io/jest/docs/en/configuration.html#globals-object) and [--config](https://facebook.github.io/jest/docs/en/cli.html#config-path).

config.jcon
```json
{
  "globals": {
    "arg1": "value1",
    "arg2": "value2"
  }
}
```

issue.464.spec.js
```js
it('issue 464', () => {
  console.log('arg1', arg1);
  console.log('arg2', arg2);
});
```

```
$ npm test -- --config config.jcon __tests__/issue.464.spec.js
```

console
```
  console.log __tests__/issue.464.spec.js:4
    arg1 value1

  console.log __tests__/issue.464.spec.js:5
    arg2 value2
```
