### ISSUE TITLE
I'm done with done()

### ISSUE THREAD

**Issue by tsongas** [vlucas/frisby#466]
Thought I would share an example of writing tests without using a `done()` callback, including returning a resolved promise from `beforeEach()` https://gist.github.com/tsongas/15d4659bc376c06b8b31b448695ef2c9. Feedback welcome. Not sure if Frisby's documentation and examples will be moving in this direction now that it supports promises.

**Comment by vlucas** [comment]
Yes, most people using it actively are just using `return` instead - myself included. I will get the docs updated with the approach.

**Comment by vlucas** [comment]
Closing, as all docs have been updated.
