### ISSUE TITLE
Test still passing, when endpoint is incorrect

### ISSUE THREAD

**Issue by JHAL981** [vlucas/frisby#467]
Hi,
Just start to playing around with Frisby. I might be doing something wrong, but here's my issue.

When I pass an incorrect endpoint, it still passes the test instead of failing it... 

See example (This screenshot shows valid endpoint)
![screen shot 2018-04-23 at 17 02 24](https://user-images.githubusercontent.com/37070916/39138587-3171d9ee-4718-11e8-8793-2c1e9967c7ab.png)

See example to break test (Screenshot below shows invalid endpoint)
![screen shot 2018-04-23 at 17 02 36](https://user-images.githubusercontent.com/37070916/39138658-61d56c5e-4718-11e8-8ab5-301233e646d6.png)

See Example (Screenshot of test passing with 200, but JSON undefined)
![screen shot 2018-04-23 at 17 02 49](https://user-images.githubusercontent.com/37070916/39138670-657cfb74-4718-11e8-9cc1-09d682e272fd.png)

Might be doing something wrong..

**Comment by JEHAL981** [comment]
Ok, thanks. So, in a previous version 0.8.7, I believe it had functions to run assertions against the schema/JSON i.e. expectedSCHEMA & expectedJSON. How would I do this in the curret version?

**Comment by vlucas** [comment]
Unfortunately, v2.x does not currently have any built-in JSON schema support. I am not opposed to adding it in though, if you have any suggestions or code to use.
