### ISSUE TITLE
authorization issue in nested case

### ISSUE THREAD

**Issue by avne31** [vlucas/frisby#473]
Hi,

currently, I have multiple tests in a single script and by nested it will be associated with each other but I facing the problem in authorization because some require JWT and some wants username: password.
so is there any way that I will give authorization in their particular test rather than give in Frisby.globalsetup, or any other way of doing so.

thanks

**Comment by vlucas** [comment]
You can use `.setup(...)` for a single test.

**Comment by avne31** [comment]
thank you...
