### ISSUE TITLE
unable to get POST with x-www-form-urlencoded body working in 2.x

### ISSUE THREAD

**Issue by spatchamatla** [vlucas/frisby#486]
Hi, i got the below post that needs a body with x-www-form-urlencoded
`return frisby
            .setup({
                request: {
                    timeout: 60000,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }
            })
            .post(url,{
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                body:{
                    grant_type: '<****>'
                }
            })
            .inspectRequest()
            .expect('status', 200)
            .catch(function (err) {
                console.log('error', err.message);
            });`
and its getting
FAILURE Status: 400 
JSON: {
    "error": "invalid_request",
    "error_description": "Missing form parameter: grant_type"
}
its says the parameter grant_type is missing even though its provided

**Comment by H1Gdev** [comment]
@spatchamatla 

Please refer to #404.

**Comment by spatchamatla** [comment]
@H1Gdev Thank you!!
