### ISSUE TITLE
Support for expect multiple possible status code values

### ISSUE THREAD

**Issue by e-bar** [vlucas/frisby#490]
Hi @vlucas,

When testing REST APIs, it's common to expect for multiple status codes as valid responses.

Would it be possible to support something like this? 🙏 ⬇️ 
````js
.expect( 'status',  200 || 409 )
````

**Comment by vlucas** [comment]
A single test scenario should always yield the same result. When creating a test scenario, you should aim to re-create all the conditions that lead to the result you want. So in this case, there should be two different requests - one that produces a `200` response, and one that produces a `409` response.
