### ISSUE TITLE
How i can add cert, key files and host link to frisby ?

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#491]
`var frisby = require('frisby');
var jest = require('jest');
 request = require('request');
var fs = require('fs');

path = require('path');
certFile = path.resolve('../api/certificate/stage.cer');
keyFile = path.resolve('../api/certificate/iotidentitystg.key');

    fit('6- api test', function(done) {
        return frisby
            .post('URL', {
                name: "MC_Profile_user",
                toolID: 4,
                publish: 1,
                companyID: 34,
                attributes: [
                    {
                        descrName: "Entitlement_Permission",
                        descrValue: "MC_Devices_RO, MC_Devices_RW",
                        attribID: 218
                    }
                ]
            },
                {
                cert: fs.readFileSync(certFile),
                key: fs.readFileSync(keyFile)
               

            })
        .expect('status', 200)
            .expect('bodyContains','ApplicationException Failed')
    .done(done);
    });

    });

`

**Comment by H1Gdev** [comment]
@Amrkamel1

How about this code ?

```js
var frisby = require('frisby');
var jest = require('jest');
var fs = require('fs');

var path = require('path');
certFile = path.resolve('../api/certificate/stage.cer');
keyFile = path.resolve('../api/certificate/iotidentitystg.key');

fit('6- api test', function(done) {
    return frisby
        .fetch('URL', {
            method: 'post',
            name: "MC_Profile_user",
            toolID: 4,
            publish: 1,
            companyID: 34,
            attributes: [
                {
                    descrName: "Entitlement_Permission",
                    descrValue: "MC_Devices_RO, MC_Devices_RW",
                    attribID: 218
                }
            ]
        },
        {
            cert: fs.readFileSync(certFile),
            key: fs.readFileSync(keyFile)
        })
        .expect('status', 200)
        .expect('bodyContains','ApplicationException Failed')
        .done(done);
});
```

**Comment by Amrkamel1** [comment]
> @Amrkamel1
> 
> How about this code ?
> 
> ```js
> var frisby = require('frisby');
> var jest = require('jest');
> var fs = require('fs');
> 
> var path = require('path');
> certFile = path.resolve('../api/certificate/stage.cer');
> keyFile = path.resolve('../api/certificate/iotidentitystg.key');
> 
> fit('6- api test', function(done) {
>     return frisby
>         .fetch('URL', {
>             method: 'post',
>             name: "MC_Profile_user",
>             toolID: 4,
>             publish: 1,
>             companyID: 34,
>             attributes: [
>                 {
>                     descrName: "Entitlement_Permission",
>                     descrValue: "MC_Devices_RO, MC_Devices_RW",
>                     attribID: 218
>                 }
>             ]
>         },
>         {
>             cert: fs.readFileSync(certFile),
>             key: fs.readFileSync(keyFile)
>         })
>         .expect('status', 200)
>         .expect('bodyContains','ApplicationException Failed')
>         .done(done);
> });
> ```

i have tried that but still doesnt work, i think it doesn't recognize the cert files
![2018-09-27_14h03_29](https://user-images.githubusercontent.com/32042806/46144785-44b18880-c25e-11e8-80e3-2964435cde2a.png)


however it works fine on postman with same cert

**Comment by H1Gdev** [comment]
@Amrkamel1 

How about this code ?

```js
var frisby = require('frisby');
var jest = require('jest');
var fs = require('fs');
var https = require('https'); // or http

var path = require('path');
certFile = path.resolve('../api/certificate/stage.cer');
keyFile = path.resolve('../api/certificate/iotidentitystg.key');

fit('6- api test', function(done) {
    return frisby
        .setup({
            request: {
                agent: new https.Agent({
                    cert: fs.readFileSync(certFile),
                    key: fs.readFileSync(keyFile)
                })
            }
        })
        .post('URL', {
            name: "MC_Profile_user",
            toolID: 4,
            publish: 1,
            companyID: 34,
            attributes: [
                {
                    descrName: "Entitlement_Permission",
                    descrValue: "MC_Devices_RO, MC_Devices_RW",
                    attribID: 218
                }
            ]
        })
        .expect('status', 200)
        .expect('bodyContains','ApplicationException Failed')
        .done(done);
});
```

**Comment by Amrkamel1** [comment]
> @Amrkamel1
> 
> How about this code ?
> 
> ```js
> var frisby = require('frisby');
> var jest = require('jest');
> var fs = require('fs');
> var https = require('https'); // or http
> 
> var path = require('path');
> certFile = path.resolve('../api/certificate/stage.cer');
> keyFile = path.resolve('../api/certificate/iotidentitystg.key');
> 
> fit('6- api test', function(done) {
>     return frisby
>         .setup({
>             request: {
>                 agent: new https.Agent({ // or http.Agent
>                     cert: fs.readFileSync(certFile),
>                     key: fs.readFileSync(keyFile)
>                 })
>             }
>         })
>         .post('URL', {
>             name: "MC_Profile_user",
>             toolID: 4,
>             publish: 1,
>             companyID: 34,
>             attributes: [
>                 {
>                     descrName: "Entitlement_Permission",
>                     descrValue: "MC_Devices_RO, MC_Devices_RW",
>                     attribID: 218
>                 }
>             ]
>         })
>         .expect('status', 200)
>         .expect('bodyContains','ApplicationException Failed')
>         .done(done);
> });
> ```

thats it, its working great now thx man
