### ISSUE TITLE
Override Content-Type, specifically when uploading file/posting FormData

### ISSUE THREAD

**Issue by imnmi** [vlucas/frisby#493]
The bit of code below to upload a file logs the following "Content-Type", which keeps the default value for `application/json` and merges the formData's content-type to it. This is unfortunately causing problems in testing, where a validator we're using in our code does not recognize the content-type provided and rejects the request outright. 

Note a) the application/json value, and b) the difference in delimiters used.
> Content-Type: application/json,multipart/form-data; boundary=--------------------------489978773764438461268674

Expecting this instead:
> Content-Type: multipart/form-data; boundary=--------------------------489978773764438461268674
It would make sense to override the default content-type completely when uploading FormData.

```
let formData = frisby.formData();
const csvPath = path.resolve(__dirname, './file.csv');
let content = fs.createReadStream(csvPath);
formData.append('file', content);
            
return frisby
  .post(api.importCsvUrl(), { body: formData })
  .inspectRequestHeaders()
  .expect('status', 200)
```

**Comment by imnmi** [comment]
NOTE, this was broken out of the original message. Realized I was providing "content-type" in my header as opposed to "Content-Type". This is no longer an issue.: 
> Secondly, I can't seem to find a way to override the content-type manually in this case, either by providing a header as part of the post or as setup. Completely replacing the content-type seems to me like the easiest solution to getting around my particular error. If that's feasible, how would I go about doing that?

**Comment by bkimminich** [comment]
I was able to fix similar issues by replacing

```
frisby.post(URL + '/file-upload', { headers: form.getHeaders(), body: form })
```

with

```
frisby.post(URL + '/file-upload', { headers: { 'Content-Type': form.getHeaders()['content-type'] }, body: form })
```

**Comment by H1Gdev** [comment]
@vlucas 

Please release in npm.

**Comment by vlucas** [comment]
This has been released in the latest version :)
