### ISSUE TITLE
Why i cant inspect JSON using frisby

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#499]
i got the error below when i'm trying to inspect simple api using inspectJSON however i can inspect it using postman knowing that there is not any credential or authorization  : 
    JSON: {
        "hasErrors": true,
        "resultList": [
            {
                "message": "\"additionalParams%5BdataLimit%5D\" is not allowed",
                "key": [
                    "additionalParams%5BdataLimit%5D"
                ]
            },

this is my code 
`    fit('get method should return response code of 200',function(done) {
       return frisby
           .get('api url')
              .inspectJSON()
           .done(done);
![2018-10-24_14h23_31](https://user-images.githubusercontent.com/32042806/47431738-eadca980-d79c-11e8-9f97-61a61da9eb44.png)
![2018-10-24_14h23_44](https://user-images.githubusercontent.com/32042806/47431739-eadca980-d79c-11e8-86cf-b7ed1f639f69.png)

    });`

**Comment by H1Gdev** [comment]
@Amrkamel1 

I do not know specification of this Web API.
According to response, is "additionalParams%5BdataLimit%5D" query invalid ?

**Comment by H1Gdev** [comment]
@Amrkamel1 

If `api url` is the same for postman and frisby, the same response will be received from server unless it is a stateful API.

So, I think that there is something issue with query string(encoding, length, order, etc.).
