### ISSUE TITLE
Can I generate summary test report for frisby result 

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#500]

**Comment by H1Gdev** [comment]
@Amrkamel1 

FYI

frisby uses jest for test execution environment.
One of jest's reporters is [jest-html-reporter](https://www.npmjs.com/package/jest-html-reporter).

How about trying it?

**Comment by Amrkamel1** [comment]
@H1Gdev 
that was really helpful thanks man, its working fine now

**Comment by rafaelribon** [comment]
@Amrkamel1 How did you set it up?

**Comment by Amrkamel1** [comment]
> @Amrkamel1 How did you set it up?

thin this command on your terminal : npm install jest-html-reporter --save-dev
then add this part to you json package ; 
`  "jest" : {
    "reporters": [
  "default",
  ["./node_modules/jest-html-reporter", {
    "pageTitle": "Test Report"
  }]
]}`

**Comment by rafaelribon** [comment]
> > @Amrkamel1 How did you set it up?
> 
> use this command on your terminal : npm install jest-html-reporter --save-dev
> then add this part to you json package ;
> ` "jest" : { "reporters": [ "default", ["./node_modules/jest-html-reporter", { "pageTitle": "Test Report" }] ]}`

Thanks
