### ISSUE TITLE
Protractor Frisby Returning 500 error

### ISSUE THREAD

**Issue by vijaychowthri** [vlucas/frisby#507]
Protractor Frisby Returning 500 error

Why frisby sending body as string ? 

**My Reusable Function:** 

 this.postResponse = function (endPoint,bdy,AuthCookies ) {
        // bdy =JSON.stringify(bdy);
        console.log("------------PostResponse Function ------------");
        console.log("Endpoint  :" + endPoint);
        console.log("Body      :" + bdy);
        console.log("ipCookie  :" + AuthCookies );
        console.log("----------------------------------------------");        
        return browser.controlFlow().execute(function () {
            try {
                var hed = {
                    request: {
                      //  followRedirect: true,
                        headers: {
                            'Content-Type' :'application/json;charset=UTF-8',
                            'Cookie'            :  AuthCookies 
                        },
                     strictSSL: false,
                 //    Body: bdy,
                    },
                };
                return frisby.setup(hed).post(endPoint, bdy).timeout(1000).then(function (res, err) {
                            if (res.status == "200") {
                        return res;
                    } else {
                        return err
                    }
                }, 1000);
            } catch (err) {
                console.log("Error in Catch :: " + err);
              //  message = message || 'Not able to get resposne';
                logger.info('ERROR', "Failed postResponse Function response : " + err);
                return false;
            }
        });
    };

------------------------------------------------------------------------------------------------------

Main function :: 

creatUser =  function() {
   this.execute= async function(){
    
var frisby = require('frisby');
var faker= require('faker');
var appFirstName = faker.name.firstName();
var appLastName = faker.name.lastName();
var  instId="123";
var  AuthCookies = "adskfjadsjkf4524839579kdjfd"; 

   var strBody = '{"instId":"'+instId+'","firstName":"'+appFirstName+'","lastName":"'+appLastName+'","emailAddress" :"'+appEmail+'", "graduationDateExpected" : "2020-11-11" ,"studentPhase":"CLINICAL","mphIndicator":"MPH","internationalMobilityIndicator":"Y" " }';

var strBodyJson =JSON.stringify(strBody);
var myEndPoint= "https://env.org/vervice/ins/"+instId+"/pendStd/";

var Response= await browserActions.postResponse(myEndPoint,strBodyJson,AuthCookies );

console.log("pendingStudentResponse   :  "+Response.body);
 
}
  }
-----------------------------------------------------------
my Response  status code: 500

Splunk Error

![image](https://user-images.githubusercontent.com/33633657/49471749-aa307100-f7db-11e8-99bf-84ccb677d40c.png)

**Comment by H1Gdev** [comment]
@vijaychowthri 

If you want to send as JSON object, please call post method with params argument as JavaScript Object.

```js
createUser = function() {
  this.execute= async function(){

    var frisby = require('frisby');
    var faker= require('faker');
    var appFirstName = faker.name.firstName();
    var appLastName = faker.name.lastName();
    var instId="123";
    var AuthCookies = "adskfjadsjkf4524839579kdjfd";

    var strBodyJson = {
      instId: instId,
      firstName: appFirstName,
      lastName: appLastName,
      emailAddress: appEmail,
      graduationDateExpected: "2020-11-11",
      studentPhase: "CLINICAL",
      mphIndicator: "MPH",
      internationalMobilityIndicator: "Y"
    };

    var myEndPoint= "https://env.org/vervice/ins/"+instId+"/pendStd/";

    var Response= await browserActions.postResponse(myEndPoint, strBodyJson, AuthCookies);

    console.log("pendingStudentResponse : "+Response.body);
  }
}
```

**Comment by vijaychowthri** [comment]
Still having issue :)

(node:16748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: onRejected is not a function
(node:16748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
.

**Comment by H1Gdev** [comment]
@vijaychowthri 

As error message, argument type of **then** method is different.
[Promise.prototype.then()](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)

e.g.
```js
return frisby.setup(hed).post(endPoint, bdy).timeout(1000).expect('status', 200).then(function (res) {
  return res;
}, function (err) {
  return err;
});
```

**Comment by vlucas** [comment]
If you are having unhandled promise rejections in console while doing test runs, it probably means that you are not returning the promise or Frisby chain your test. If that is intentional, then you also have to handle your own promise failures since the test framework will not handle them for you (as it does when you return a Promise object), so you have to implement your own `.catch()` handler function.
