### ISSUE TITLE
Questions about structuring tests

### ISSUE THREAD

**Issue by cu** [vlucas/frisby#513]
Hi,

I followed the docs and have two files with tests in them inside the `__tests__` directory:

```
__tests__/
  categories.js
  transactions.js
```

This works but now I want a file with one test (a kind of sanity check) that runs before any of the tests in the directory and (if possible) to halt everything if that one test fails. Is this possible?

My other question is whether or not there is an easy way to import a set of common variables into both `categories.js` and `transactions.js`. These would be for things like URLs and mock objects shared between tests.

I understand frisbyjs is based upon jest but I wasn't able to find what I'm looking for. Any pointers towards what I'm missing would be much appreciated.

Thanks!

**Comment by H1Gdev** [comment]
@cu 

> This works but now I want a file with one test (a kind of sanity check) that runs before any of the tests in the directory and (if possible) to halt everything if that one test fails. Is this possible?

How about using `process.exit()` and [--runInBand](https://jestjs.io/docs/en/cli#runinband) in [beforeAll](https://jestjs.io/docs/en/api#beforeallfn-timeout) ?
Or [--bail](https://jestjs.io/docs/en/cli#bail) ?

> These would be for things like URLs and mock objects shared between tests.

If constant value, use [globals](https://jestjs.io/docs/en/configuration.html#globals-object) ?

**Comment by vlucas** [comment]
Since all Jest tests are really just Jasmine tests wrapped in a different test runner, you might be able to do something like:

```
jasmine runBeforeTests.js && jest
```

**Comment by cu** [comment]
Thanks for the responses, I'll check those out.
