### ISSUE TITLE
intermittent issue related to Fetch Error  network timeout 

### ISSUE THREAD

**Issue by shahidv3** [vlucas/frisby#515]
Hello All,
I have recently migrated to 2.x and noticed that the test runs are inconsistent with the following stack trace.Did anyone faced this . I tried increasing the timeout and .catch handling as mentioned in the following links  
https://github.com/vlucas/frisby/issues/393 
https://github.com/vlucas/frisby/issues/483

However it didn't helped. Appreciate the response @H1Gdev @vlucas 

   **FetchError: network timeout at: https://<api_url>/someroute

      at node_modules/node-fetch/lib/index.js:1437:13
      at Timeout.callback (node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)**

Thanks , Sahid

**Comment by H1Gdev** [comment]
@shahidv3 

From stack trace, It seems that frisby timeout is not enough.(default is 5000[ms])

First, please try increasing each timeouts like following sample code.
```js
const frisby = require('frisby');

let timeout = 10000; // wait 10000[ms].

it('issue 515.', () => {
  return frisby.timeout(timeout)
    .get('https://<api_url>/someroute')
    .expect('status', 503);
}, timeout);
```

**Comment by shahidv3** [comment]
thanks @H1Gdev , its working fine now.
appreciate your quick response.

**Comment by vlucas** [comment]
Thanks @H1Gdev !
