### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by tannerjt** [vlucas/frisby#516]
I'm running tests against multiple machines.  When a machine is down due to a failure, my test is obviously going to error our (network timeout).  

When this happens, my entire test suite fails.

Is there a way to just have the specific test fail and not the entire test suite?

**Comment by vlucas** [comment]
Also if you make sure to `return frisby.get()...` in your test, Jest will handle the error reporting and test failure for you automatically.

**Comment by tannerjt** [comment]
Thanks for the help @H1Gdev and @vlucas.  I was able to successfully get the desired result with Promise catch.  I was trying to wrap in a try catch statement before which didn't work, and now I understand why.  Thank You!
