### ISSUE TITLE
How i can upload file using frisby

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#517]
i was searching for some options to allow me uploading a file using frisby, i have tried this script show below but i didn't get the expected response dont know if there is something wrong with the script also i have attached a screenshot of the request payload

`
var frisby = require('frisby');
const fs = require('fs');
const path = require('path');

const URL = 'api url';

describe('uploading file ', () => {

    it('POST CSV FIL', () => {
        const file = path.resolve('test/ACTIVATION.csv');
        const form = frisby.formData();
        form.append('file', fs.createReadStream(file));

        return frisby
            .post(URL +[{
                fileName: "ACTIVATION_02-05-2019_08-34-31.csv",
                fileType: ".csv",
                m2mAccountId: "88888",
                m2mPlatform: "ACC",
                scheduledDate: "2019-02-05",
            } ], {headers: {'Content-Type': form.getHeaders()['content-type']}, body: form})
            .expect('status', 200)
    })
});
`

![image](https://user-images.githubusercontent.com/32042806/52261080-79c69980-2928-11e9-8da7-45ad3647fbdd.png)

![image](https://user-images.githubusercontent.com/32042806/52260994-294f3c00-2928-11e9-9444-0a55b31600ec.png)

**Comment by H1Gdev** [comment]
@Amrkamel1 

Please try the following code.
```js
const frisby = require('frisby');
const fs = require('fs');
const path = require('path');

const URL = 'api url';

describe('uploading file ', () => {

  it('POST CSV FIL', () => {
    const file = path.resolve('test/ACTIVATION.csv');
    const form = frisby.formData();
    form.append('file', fs.createReadStream(file));

    form.append('fileName', "ACTIVATION_02-05-2019_08-34-31.csv");
    form.append('fileType', ".csv");
    form.append('m2mAccountId', "88888");
    form.append('m2mPlatform', "ACC");
    form.append('scheduledDate', "2019-02-05");

    return frisby.post(URL, {
        body: form
      })
      .expect('status', 200);
  });
});
```

**Comment by Amrkamel1** [comment]
is there anything i can do regarding content-Type
![image](https://user-images.githubusercontent.com/32042806/52326837-3e8c9f00-29ea-11e9-93ae-ef0e3de82347.png)

![image](https://user-images.githubusercontent.com/32042806/52327022-dc806980-29ea-11e9-8f05-ffe51ef33ee3.png)

**Comment by H1Gdev** [comment]
@Amrkamel1 

Try to set `Content-Type`.

https://github.com/vlucas/frisby/issues/494#issuecomment-433002641
