### ISSUE TITLE
How to set cookies for current frisby version

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#520]
i have tried some script but so far non of them works with me and this script below is the last trial.

   
 fit('6- 6th example log in using correct credential to staging expect status to be 304', function(){
       return frisby
        headers: {
            cookie: res.headers.get('set-cookie')
        }
           .post('api url',{
               redirect: 'https://mc.stage.att.com/',
               reprompt: 'url',
               username: 'userName',
               password: 'PassWord',
           })
           .expect('status',302)
    });

});
![image](https://user-images.githubusercontent.com/32042806/52964042-a73c2a00-33a1-11e9-9ee5-e178ad83fee5.png)

![image](https://user-images.githubusercontent.com/32042806/52963824-1c5b2f80-33a1-11e9-835e-730247a5fd0f.png)

![image](https://user-images.githubusercontent.com/32042806/52963975-7c51d600-33a1-11e9-9048-57362ce16943.png)

**Comment by H1Gdev** [comment]
@Amrkamel1 

You need to convert `set-cookie` to `cookie`.

I used [cookie-client](https://www.npmjs.com/package/cookie-client) in the past.

**Comment by Amrkamel1** [comment]
@H1Gdev @vlucas 

**Could you please provide a sample** 

`describe ('Backend Validation',()=> {

    beforeAll(()=>{
        return frisby
            .setup({
                request: {
                    redirect: 'manual',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                    }
                }
            })
            .post('https://login.com/EAI/Login', {
                body: qs.stringify({
                    redirect: 'https://redirect.com',
                    reprompt: 'https://reopromt.com/',
                    username: 'user@user.com',
                    password: '1123,
                })
            })
            .expect('status', 302)
            .inspectBody()
    });
	
	it('1- verify status code 200', ()=>{
	      return frisby
            .setup({
                request: {
                    redirect: 'manual',
                    headers: {
                        'Content-Type': 'application/json',
                        'company-service': 'default'
                    }
                }
            })

            .get('https://dashboard.com/users/current')
                    .expect('status', 200)
                    .inspectBody()
                .done(done);
            });
});

`

**Comment by Amrkamel1** [comment]
solved thx
