### ISSUE TITLE
How to set headers and rawBody into Post request

### ISSUE THREAD

**Issue by Viterzgir666** [vlucas/frisby#523]
Hi! 

Trying to write a simple test for endpoint that accepts only rawBody + headers needed. 
How can I do this?
Things I tried: 

1) `{
  request: {
    headers: {
      'Content-Type': 'application/json'
    },
    body: {
      email: 'a@b',
      slug: 'test'
    },
    rawBody: true,
  }
}`

2) `{
  request: {
    headers: {
      'Content-Type': 'application/json'
    },
    body: {
      email: 'a@b',
      slug: 'test'
    },
    json: true,
  }
}`

3) tried to separate body and headers as 2 objects;
4) without headers
5) only object with parameters;
6) only object with parameters + {json: true} or {rawBody: true};
7) with `.setup()`;

But in return I got whether 
"FetchError: request to http://some_url/api/v2/endpoint failed, reason: Parse Error" or 
"400 Error"

Please, help :)

**Comment by H1Gdev** [comment]
@Viterzgir666 

Does following code work as you expected ?
``js
const frisby = require('frisby');

it('test', function () {
  return frisby.setup({
    request: {
      headers: {
        'Content-Type': 'application/json'
      }
    }
  }, true)
    .post(URL, {
      body: { email: 'a@b', slug: 'test' }
    })
    .expect('status', 200);
});
``

**Comment by Viterzgir666** [comment]
@H1Gdev 

Thanks for help, 
but, unfortunately, no :(

Got this error: 
` FetchError: request to http://kalkomey-ams.dev.digicode.ua/api/v2/forgot_password failed, reason: Parse Error

      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1444:11)`

Can it be some kind of bug on the server? 
I have a very similar test, where only endpoint is different and there's 1 additional parameter, but that's it - and it works well.

**Comment by H1Gdev** [comment]
@Viterzgir666 

Can you paste request header and body for Postman ?

**Comment by Viterzgir666** [comment]
@H1Gdev 
Sure, here it is:

Headers: 
`Content-Type: application/json`
Body: 
`raw` is checked, `JSON(application/json)` is selected in dropdown for body
`{
      "email": "test@test.com",
      "slug": "nevada"
}`

**Comment by H1Gdev** [comment]
@Viterzgir666 

The request header sent by frisby is as follows.
```
POST / HTTP/1.1
Content-Type: application/json
Accept: */*
Content-Length: 29
User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
Accept-Encoding: gzip,deflate
Connection: close
```

Please try to setup User-Agent on frisby.

```js
const frisby = require('frisby');

it('test', () => {
  return frisby.setup({
    request: {
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': USER_AGENT // What is User-Agent ?
      }
    }
  }, true)
    .post(URL, {
      body: { email: 'a@b', slug: 'test' }
    })
    .expect('status', 200);
});
```

**Comment by H1Gdev** [comment]
@Viterzgir666 

From [error reason](https://github.com/vlucas/frisby/issues/523#issuecomment-478215850) `Parse Error at ClientRequest.<anonymous>`, there may be a mistake in Request JavaScript object.

**Comment by Viterzgir666** [comment]
@H1Gdev 
Tried with User-Agent - the same error appears. Tried with Chrome browser, Android+Chrome, Android Application - Billboard. 

Tried to stringify body, then response is changed to a huge html site response with logs. Title is this: 
`ActionDispatch::ParamsParser::ParseError
822: unexpected token at 'email=test%40test.com&slug=nevada'`

It just doesn't work. 
There's simple body JSON object, header requires only 'Content-Type'. 

I already wrote tests with Frisby. There's nothing special with this request. It just doesn't work and I don't understand why.

**Comment by H1Gdev** [comment]
@Viterzgir666 

Has your `FetchError` issue been solved ?

**Comment by Viterzgir666** [comment]
@H1Gdev 

no :(

**Comment by H1Gdev** [comment]
@Viterzgir666 

Execute following code.
```js
const frisby = require('frisby');

it('test', () => {
  return frisby.setup({
    request: {
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'frisby/2.1.1 (+https://github.com/vlucas/frisby)'
      },
      timeout: 10000
    }
  }, true)
    .post(URL, {
      body: { email: 'test@test.com', slug: 'nevada' }
    });
}, 10000);
```

And send following HTTP request.
```
POST / HTTP/1.1
Content-Type: application/json
User-Agent: frisby/2.1.1 (+https://github.com/vlucas/frisby)
Accept: */*
Content-Length: 41
Accept-Encoding: gzip,deflate
Connection: close

{"email":"test@test.com","slug":"nevada"}
```

How are you execute frisby ?
Please paste code that becomes `FetchError` error.

**Comment by Viterzgir666** [comment]
@H1Gdev 

```
it('test', () => {
  return frisby.setup({
    request: {
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'frisby/2.1.1 (+https://github.com/vlucas/frisby)'
      },
      timeout: 10000
    }
  }, true)
    .post(URL, {
      body: { email: 'test@test.com', slug: 'nevada' }
    })
    .expect('status', 200);
}, 10000);
```
this code returns me 
``` FetchError: request to http://base_url/api/v2/forgot_password failed, reason: Parse Error at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1444:11)
```

If I change `email` in body into invalid one - I'll got correct 400 error with description that email is incorrect. But valid request returns FetchError.

**Comment by Viterzgir666** [comment]
@H1Gdev 

```
it('test', () => {
  return frisby.setup({
    request: {
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'frisby/2.1.1 (+https://github.com/vlucas/frisby)'
      },
      timeout: 10000
    }
  }, true)
    .post(URL, {
      body: { email: 'test@test.com', slug: 'nevada' }
    })
    .expect('status', 200);
}, 10000);
```
this code returns me 
``` FetchError: request to http://base_url/api/v2/forgot_password failed, reason: Parse Error at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1444:11)
```

If I change `email` in body into invalid one - I'll got correct 400 error with description that email is incorrect. But valid request returns FetchError.

**Comment by Viterzgir666** [comment]
Sorry, missclick :/

**Comment by H1Gdev** [comment]
```
  ● test

    FetchError: request to http://base_url/api/v2/forgot_password failed, reason: getaddrinfo ENOTFOUND base_url base_url:80

      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1444:11)
```

**Comment by H1Gdev** [comment]
@Viterzgir666 

Don't worry.
It is just a note.

**Comment by H1Gdev** [comment]
@Viterzgir666 

This HTTP request sent by frisby is generally fine.
However it's not what this server expected.

It is successful in Postman.
So send the same request as Postman.
Please tell me actual exact HTTP request header and body in Postman.

**Comment by Viterzgir666** [comment]
@H1Gdev 
https://www.getpostman.com/collections/099f9b279bfe43ffef6f

**Comment by H1Gdev** [comment]
@Viterzgir666 

Postman sends following HTTP request.
```
POST /api/v2/forgot_password HTTP/1.1
Connection: keep-alive
Content-Length: 65
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: 0451f717-fe0b-e151-1aab-bcd3ec97ff17
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: ja,en-US;q=0.9,en;q=0.8

{
      "email": "test@test.com",
      "slug": "nevada"
    }
```

**Comment by Viterzgir666** [comment]
@H1Gdev 

I know :) 
Do you recommend me to add all those header parameters? 
I already tried with User-Agent and Content-Type, though

**Comment by H1Gdev** [comment]
@Viterzgir666 

> Do you recommend me to add all those header parameters?

Yes.
I do not know specifications of your server.

**Comment by vlucas** [comment]
Instead of having to use `setup` to send those headers, another alternative is to use `fetch` directly:

```javascript
it('test', () => {
  return frisby.fetch(URL, {
      method: 'post',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ email: 'a@b', slug: 'test' }),
    })
    .expect('status', 200);
});
```

Does it work when you do this?

**Comment by Viterzgir666** [comment]
API is broken for now - can't test. 
But thanks for the reply.

**Comment by Viterzgir666** [comment]
Closing because it is not irrelevant anymore. 
Don't have this error in other projects so it is fine, I guess :)
