### ISSUE TITLE
Upgrade to Joi  v16

### ISSUE THREAD

**Issue by terradek** [vlucas/frisby#534]
Seems Joi maintainers in version 16 have made breaking changes in .validate() method  
according to [this:](https://github.com/hapijs/joi/issues/2107#issuecomment-530920836)
And according to [Split validate() to sync and async versions](https://github.com/hapijs/joi/issues/1998) it was splitted to async/sync versions
Could someone please change Frisby to allow Joi v16 use?
Thank you in advance
... and seems recently they deleted joi@13 from npm
`npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).`

**Comment by vlucas** [comment]
From the notes on the Joi project, this looks like it would also require a major version bump for Frisby.js: https://github.com/hapijs/joi/issues/2037

**Comment by terradek** [comment]
I am agree with you. a major Frisby version is a must

**Comment by vlucas** [comment]
We should probably at least upgrade to v15, to whatever the latest stable release before v16 is to avoid those warnings, so thank you for letting us know.
