### ISSUE TITLE
How to use post method for http call 301

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#541]
im unable to perform post method for an API that will return 301 once you successfully logged in 

here is what i did 

`describe ('Backend Validation', function () {

    frisby.globalSetup({
        request: {
            followRedirect: 'follow', // also try it with redirect: false and without anything as well
            headers: {
                origin: 'example.com',
                referer: 'https://example.com/login?redirect=https%3A//exa.com/',
            }
        }
    });

    it('1- Verify backend and API will return 301', function () {
        return frisby
            .post('https://example.com/EAI/Login', {
                    username: 'my user',
                    password: 'my pass'
                })
                    .expect('status', 302)
            })
});
`
here is also all api details 

![image](https://user-images.githubusercontent.com/32042806/71617686-7a10f880-2bbc-11ea-9236-dd10b9f85d11.png)

![image](https://user-images.githubusercontent.com/32042806/71617695-81380680-2bbc-11ea-9772-bec44d7449f5.png)

**Comment by Amrkamel1** [comment]
@vlucas

**Comment by vlucas** [comment]
Sounds like you need `{redirect: 'manual'}`: https://stackoverflow.com/questions/42716082/fetch-api-whats-the-use-of-redirect-manual

**Comment by Amrkamel1** [comment]
> Sounds like you need `{redirect: 'manual'}`: https://stackoverflow.com/questions/42716082/fetch-api-whats-the-use-of-redirect-manual

same still returning 200 postman returning the expect value 302


describe ('Backend Validation', function () {


    frisby.globalSetup({
        request: {
            redirect: 'manual',
            headers: {
                origin: 'https://sss.com',
                referer: 'https://aaa.com',
            }
        }
    });


    it('1- API will retrun 302', function () {
        return frisby
            .post('https://example.com/EAI/Login', {
                    username: 'user',
                    password: 'pass'
                })
                    .expect('status', 302)
            })
});

**Comment by vlucas** [comment]
Try using `fetch()` instead of `post()` and see if that makes a difference. It's a direct pass through to the fetch API.

**Comment by Amrkamel1** [comment]
u mean just replace post with fetch

**Comment by vlucas** [comment]
Yes
