### ISSUE TITLE
how i can generate code challenge and code verifer (oidc-client)

### ISSUE THREAD

**Issue by Amrkamel1** [vlucas/frisby#554]
im trying to run API test using frisby, 

in order to obtain the access token, i should submit post request using the following params :

       'client_id': '2ff43eff-ac23-4f8e-90cf-75fa234ef7b1ba',
                                                           code: D.challenge,
                                                           'redirect_uri': 'https://example.test.com/signin-callback',
                                                           'code_verifier': D.verifier,
                                                           'grant_type': 'authorization_code'

issue is that i have these two parameters code and code verifier which are generated from front end using oidc-client package 

so i have created this method to generate the challenge code with the same pattern, and i manage to get the required cookies, but in last step i have to add the relative verifier code for that challenge code and so far nothing works for me 

i have used cyrpto method but no use 

   ```
 function base64URLEncode(str) {
    return str.toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '');
       }

     // exports.verifier = base64URLEncode(crypto.randomBytes(32));
    const verifierHash = base64URLEncode(crypto.randomBytes(64));
    const verifier =  Buffer.from(verifierHash,'base64').toString('hex');


    function sha256(buffer) {
        return crypto.createHash('sha256').update(buffer).digest();
    }
    const challenge = base64URLEncode(sha256(verifier));
```
```
return frisby
                                               .post('https://ci-example.test.com/token',{
                                                   headers: {
                                                       'Content-Type': 'application/x-www-form-urlencoded',
                                                       Host: 'ci-mock.test.com',
                                                       Origin: 'https://example.test.com',
                                                       Referer: `https://example.test.com/signin-callback?code=${D.challenge}&state=${D.state}`
                                                   },
                                                       body:qs.stringify({
                                                           'client_id': '2ff43eff-acc2-4f8e-90cf-75fae647b1ba',
                                                           code: D.challenge,
                                                           'redirect_uri': 'https://example.test.com/signin-callback',
                                                           // 'code_verifier': D.verifier,
                                                           'grant_type': 'authorization_code'
                                                       })
                                               })
                                               .expect('status',200)
                                               .inspectBody()
                                               .inspectHeaders()
                                       },60000)
```

my method is working fine as i have compared the output with some code generator tool and the results are matched 

![image](https://user-images.githubusercontent.com/32042806/77327377-71dbdb80-6d1b-11ea-8fec-bd76ac071f8c.png)

**Comment by Amrkamel1** [comment]
@H1Gdev @vlucas

**Comment by H1Gdev** [comment]
Sample codes are fragmentary and I don't know what to expect from frisby...

**Comment by Amrkamel1** [comment]
@H1Gdev 
Sorry for confusion, i was just wondering if there is way to use frisby to test API that interacting  with oidc client

there are some tokens are generated from the frontend (browser) as shown , these tokens later on used to generate the required cookies for that user, so im not sure if there is such approach so frisby can simulate these tokens or info so later i can obtain the required cookies 

![image](https://user-images.githubusercontent.com/32042806/79735037-f3616200-82f7-11ea-9d60-4fd7c7698982.png)

**Comment by H1Gdev** [comment]
What do you expect from frisby ?

I wrote about cookies [before](https://github.com/vlucas/frisby/issues/505#issuecomment-575095197). For example, use [cookie-client](https://www.npmjs.com/package/cookie-client).

**Comment by Amrkamel1** [comment]
yes obtaining cookies wont be a problem, but with particular app im unable to do this 

what actually is happening that when u navigate to that web app, a redirect will happen to another api url with some certain query string as shown below, problem is that im unable to get the state and the code challenge value

![image](https://user-images.githubusercontent.com/32042806/83327013-fea19900-a278-11ea-9267-a01ba2f7231b.png)

**Comment by H1Gdev** [comment]
Which request are you trying to make ?
https://medium.com/@darutk/diagrams-and-movies-of-all-the-oauth-2-0-flows-194f3c3ade85

**Comment by Amrkamel1** [comment]
> Which request are you trying to make ?
> https://medium.com/@darutk/diagrams-and-movies-of-all-the-oauth-2-0-flows-194f3c3ade85
> 
> Please write `Request` and `Response` that are expected.
> 
> Maybe you're missing request parameters.

the link you have attached was really useful 

now im stuck with this state id, how i can extract it from the response body in html format 

![image](https://user-images.githubusercontent.com/32042806/83423789-c5f5f100-a42b-11ea-9fe7-cad3846a19a9.png)


```
 it('1- API will return 200 and shows company service after successful login ', ()=> {
        const url = new URL('https://example.test.com/authsvc/sds/sps/authsvc');
        url.searchParams.append("PolicyId", 'stication:asf:basicldapusfder');
        url.searchParams.append('Target', 'https://example.test.att.com/default/authorize/qsId:3D1fgfg-974e-411a-b171-8acebe21cb');

        return frisby

            .fetch(url.href, {
                method: 'Get',
            }, {
                urlEncode: false,
            })
            .inspectBody()
            .inspectHeaders()
            .inspectStatus()
            .then(res=>{
                let setCookie = res.headers.get('set-cookie');
                console.log('setCookie', setCookie);
                let stateId= ?
            })
    });
```

**Comment by H1Gdev** [comment]
Are you getting `StateId` from HTML in [this image](https://user-images.githubusercontent.com/32042806/83423789-c5f5f100-a42b-11ea-9fe7-cad3846a19a9.png) ?

If so, you need to parse HTML recieved from server.

For example, with [node-html-parser](https://www.npmjs.com/package/node-html-parser).

**Comment by Amrkamel1** [comment]
great thank you just used this line 

                let stateId = res.body.match(/(?<=StateId=)[^"]+/)[0];

**Comment by H1Gdev** [comment]
If `StateId` is guaranteed to be unique in the HTML, that's fine.

**Comment by H1Gdev** [comment]
What is `Response From Authorization Endpoint` ?

**Comment by Amrkamel1** [comment]
@H1Gdev 

problem that there are alot of cookies and params that i kept trying to track or find way to get but i couldnt find start point 

form data below i tried to find our how i can get this code verifier and code but didn't find 

![image](https://user-images.githubusercontent.com/32042806/83642789-9243d400-a5af-11ea-885c-cf1f29e1e713.png)

if you could have some spare time ,i can share you my screen

**Comment by H1Gdev** [comment]
Looks like you're successful ?
Is there `access_token` in response body ?

**Comment by Amrkamel1** [comment]
No unfortunately

**Comment by H1Gdev** [comment]
What kind of response did you receive ?

**Comment by Amrkamel1** [comment]
> What kind of response did you receive ?

![image](https://user-images.githubusercontent.com/32042806/83730683-b653f380-a649-11ea-8d6d-582906fd9a23.png)

i just copied these parameters from the browser but it seems expired,
and actually this is my issue i dont know how i can obtain these parameters through api

**Comment by H1Gdev** [comment]
It's fragmentary and I don't understand...

> i just copied these parameters from the browser but it seems expired,

Is it enough until the expiration time ?

**Comment by Amrkamel1** [comment]
@H1Gdev 

i do tried to perform the sequence of API's  but i stopped in middle as i saw some parameter required for the next api and i dont know how to obtain it 

if you got any spare time i can show it to you live .

**Comment by Amrkamel1** [comment]
@H1Gdev 
thats how im making it with postman,

![2020-06-05_14h53_25](https://user-images.githubusercontent.com/32042806/83879203-9140ad00-a73d-11ea-8736-f1c6739f84a0.png)
![2020-06-05_14h57_48](https://user-images.githubusercontent.com/32042806/83879223-969df780-a73d-11ea-8561-bd7717995ea9.png)
![2020-06-05_14h58_44](https://user-images.githubusercontent.com/32042806/83879229-9867bb00-a73d-11ea-9116-21067318772c.png)

in frisby im unable to automate this part related to login
