### ISSUE TITLE
jsonTypes false positive with array path and extra keys

### ISSUE THREAD

**Issue by prabhash-c** [vlucas/frisby#555]
`frisby.fromJSON({"data": [{"user": "tom"},{"user": "jack"}]})
.expect('jsonTypes', 'data.*', {user: Joi.string(), hack: Joi.number()})`

This should fail, but it doesn't.

**Comment by H1Gdev** [comment]
If `hack` is required, do the following:

```js
frisby.fromJSON({
  "data": [
    {"user": "tom"},
    {"user": "jack"}
  ]
})
  .expect('jsonTypes', 'data.*', {
    user: Joi.string(),
    hack: Joi.number().required(),
  })
```

https://hapi.dev/module/joi/api/?v=17.1.1#anyrequired---aliases-exist
