### ISSUE TITLE
Is there a function similar to bodyContains but for headers?

### ISSUE THREAD

**Issue by Cenric** [vlucas/frisby#578]
I am trying to expect a value in the header to contain certain text, something like

.expect('header', 'key', startsWith('value'))

but nothing seems to work. I see that there is a built in bodyContains function, was wondering how I could do this for running an expect on a header key/value as well?

**Comment by H1Gdev** [comment]
`value` parameter is `regular expression`.

```js
.expect('header', 'key', /^value/))
```

I think [this test](https://github.com/vlucas/frisby/blob/master/__tests__/expects_spec.js) will be helpful.

**Comment by Cenric** [comment]
Thank you so much, this helped a lot!
