### ISSUE TITLE
condition for expectJSONTypes

### ISSUE THREAD

**Issue by bcokca** [vlucas/frisby#58]
Hi,

Is it possible to write tests with conditions. I would like to be able to write something like: the enpdoint can response me with this one
expectJSONTypes([{
        district_id: Number.POSITIVE_INFINITY,
        district_name: String
    }]) 

or it may response me with an empty array
expectJSONTypes([]) 

how can I handle such situations?

**Comment by Shplorf** [comment]
Passing [] to expectJSON always passes for me as long as it's an array. I'm trying to figure out how to encode into the JSON that I'm specifically expecting ONLY an empty array.

**Comment by jatinst** [comment]
I am having the same issue as @Shplorf . How do I specifically check for an empty array response?
