### ISSUE TITLE
Using query parameters in API calls

### ISSUE THREAD

**Issue by Cenric** [vlucas/frisby#580]
What is the correct way to use query parameters in frisby.js api calls? I have been adding them to the URL manually such as 

`.get('main URL here' + '?param=' + paramVariable)`

but wasn't sure if there are better ways to do this, I didn't see any frisby.js documentation on the official website for this

**Comment by H1Gdev** [comment]
FYI

https://github.com/vlucas/frisby/issues/552#issuecomment-587070845
