### ISSUE TITLE
PUT Call Double Encoding URL

### ISSUE THREAD

**Issue by Cenric** [vlucas/frisby#581]
How do I stop my PUT call from double encoding my URL? I am retrieving a URL with a bunch of %2F's in it, and when I call my PUT with that URl being passed as a parameter, the request is using the URL with a bunch of %252F's in it instead which is messing everything up.

**Comment by Cenric** [comment]
I am currently trying 
```
return frisby
      .fetch(url, {
          method: 'PUT',
          urlEncode: false,
          body: JSON.stringify({
              "somerandom": "json",
              "text": "here"
          })
      })
```
but am still getting the same error, and in the inspectRequest it is still sending the URL with %252F's

**Comment by H1Gdev** [comment]
FYI

https://github.com/vlucas/frisby/issues/552#issuecomment-588484776

```js
return frisby
      .fetch(url, {
          method: 'PUT',
          body: JSON.stringify({
              "somerandom": "json",
              "text": "here"
          })
      }, {
          urlEncode: false,
      })
```

**Comment by Cenric** [comment]
Works perfectly, thank you
