### ISSUE TITLE
POST request frisby

### ISSUE THREAD

**Issue by moses-gangipogu** [vlucas/frisby#60]
/**
    \* Tests -> POST add a new user
    */
    frisby.create('testAddUser')
    .post('http://localhost/payCard/Api/User', JSON.stringify({
        userName : 'newApi',
    Password : '123456',
    installationId : 1,
    cityId : 2,
    }),{ json: true },{METHOD: 'POST'})
    .inspectJSON()
    .inspectBody()  
    .expectStatus(200)
    .expectHeaderContains('content-type', 'application/json')
    .expectJSON('status',{
    StatusMSG: "SUCCESS",
    Code: '1'
  })  
.toss();

console.log(frisby.create('testAddUser'));
console.log(JSON.stringify({
        userName : 'newApi',
    Password : '123456',
    installationId : 1,
    cityId : 2,
    }));
//
is this code right
and how can i check what and how the json data is going to the api

//api code

//output is INVALID JSON

**Comment by mrded** [comment]
Why `{ json: true }` argument hasn't been mentioned in documentation?

**Comment by maneeshrao66** [comment]
Hello I am facing 500 error during delete request into frisby. The code is below please correct me if I have done any wrong..!

var frisby = require('frisby');

//get the current UTC time from this URL: (https://currentmillis.com/)
var now = new Date(); 
var now_utc = new Date(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(),  now.getUTCHours(), now.getUTCMinutes(), now.getUTCSeconds())
var currentUTCTime = now_utc.getTime() - (now_utc.getTimezoneOffset() * 60000);

    frisby.create('Authentication for Delete Request Valid User Name and Password')
      
         .delete('http://example.com',
          {
           headers:
            {
                  'Accept':'application/json',
                  'Auth-Username':'abcd',
                  'X-Application-Key':'xyzzzz',
                  'Content-Type':'application/json',
                  'x-locale':'en_US',
                  'x-microtime':currentUTCTime, //get the current UTC time
                  'auth-signature': 'example', // Added new auth-signature for new responses
                  }
               }   
            )
	  .expectStatus(200)
	  .toss()
