### ISSUE TITLE
Running a single test

### ISSUE THREAD

**Issue by dsawardekar** [vlucas/frisby#65]
Is there a way to make Frisby run only a single test. I would like to run an isolated test when debugging a specific error. Something like, 

```javascript
frisby.create.only('foo') // followed by the chain and toss.
```

I'm not terribly familiar with the jasmine layer underneath. Would this be possible with Frisby/Jasmine?

Thanks for this project. The json matchers in particular are well thought out and very handy!

**Comment by katerberg** [comment]
Thanks @vlucas!
