### ISSUE TITLE
https connections to servers with self-signed certificates

### ISSUE THREAD

**Issue by DATA-HORIZON** [vlucas/frisby#69]
Hello,

I am facing the problem that secure https connections to servers with domains that have self-signed certificates always end up in code 500 errors:

Message:
     Expected 500 to equal 200

TCPDump shows up an reset flag in the connection.

If I connect to https servers with domains that have certificates signed from CA's everything wents fine.

I already installed my own CA certificate on my Debian server into the local certificate store. So wget and other programs do not make any trouble.

Any hints on that?

Best wishes
Michael

**Comment by doug-nara** [comment]
This doesn't seem like a resolution to me. Frisby should be able to handle this.

**Comment by vlucas** [comment]
Frisby v0.x uses the [request library](https://github.com/request/request), and passes all the options down to it. So Frisby supports this via request options.

Request SSL options are here:
https://github.com/request/request#tlsssl-protocol

e.g.
```javascript
frisby.post('http://example.com', {field: 'value'}, {
    cert: fs.readFileSync(certFile),
    key: fs.readFileSync(keyFile),
    passphrase: 'password',
    ca: fs.readFileSync(caFile)
});
```

**Comment by fletchgqc** [comment]
@vlucas your example works for me, thanks, but is there a way to include this in the globalSetup? I tried the obvious things and they didn't work for me.
