### ISSUE TITLE
FrisbyJS - Basic HTTP authentication

### ISSUE THREAD

**Issue by thesailored** [vlucas/frisby#71]
FrisbyJS help: I need syntax for a Basic HTTP authentication to a server using an id and password.  Simple?

**Comment by RomanManz** [comment]
Hi thesailored,

if you are still interested, if you just call the auth function after the post/put/get, then it works, e.g.
frisby.create('authorization test')
.get('http://testservice.com')
.auth('username', 'secret', false)
...

Although i am not sure what the third argument (sendImmediate) would be used for.

Regards
Roman
