### ISSUE TITLE
Tests failed for reason of timeout.

### ISSUE THREAD

**Issue by AlyonaGavrylei** [vlucas/frisby#80]
Hello, help please to resolve problem. While my tests are running one by one in script some of them are failed for reason of timeout 5000ms. How can I fix this problem?
Thanks.

**Comment by clmathuriya** [comment]
I am also getting random 5000 timeouts even though I'm setting a global timeout in every file to 30000

**Comment by ravirkkm** [comment]
@vlucas 
For me sometimes all the assertions are successful  i.e., 0 failures, 0 skipped 
and very next time a few assertions are failures.
```javascript
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Finished in 8.695 seconds
3 tests, 10 assertions, 2 failure, 0 skipped
```
I've set the globalSetup timeout to 30000 and if you notice, frisby tests got finished in 8.695 
Is this timeout issue ?

Earlier I did not have this issue in my other laptop (may be that was old version of frisby/nodejs)
After I installed latest version of nodejs / frisby , I face this issue.
Any one got the solution for this ?

**Comment by Gerst20051** [comment]
:+1:

**Comment by dguerrier** [comment]
Any movement on this?

**Comment by clmathuriya** [comment]
frisby.globalSetup({
  timeout: 50000
});

worked for me.

**Comment by Haisenberh** [comment]
frisby.create("Export statements valid test")
        .post(base_url, {
            token: token
        })
        .expectStatus(200)
        .expectJSON({
            fileUrl: String
        })
        .timeout(60000) //waits 60sec for response, worked for me
        .toss();
});
