### ISSUE TITLE
expectJSONTypes: Can't use custom functions in nested objects

### ISSUE THREAD

**Issue by juliogarciag** [vlucas/frisby#93]
When i use expectJSONTypes to make tests using json test objects like this:

```
var StringOrNull = function(val) { expect(val).toBeTypeOrNull(String) } 

person = {
  phone: StringOrNull
}
```

It works. It executes the `toBeTypeOrNull` matcher and everything is ok. But when i try to use a function like this:

```
var StringOrNull = function(val) { expect(val).toBeTypeOrNull(String) } 

stuff = {
  person: {
    phone: StringOrNull
  }
}
```

The jasmine matcher is never reached. It's not being executed. Instead, it will throw an error when executed against another object:

```
Expected 'null' to be type 'object' on key 'phone'
```

**Comment by marclitchfield** [comment]
I believe I have a fix for this issue and https://github.com/vlucas/frisby/issues/94 at https://github.com/marclitchfield/frisby/tree/release-fix-nested-objects. I would be interested in learning if this resolves the issue you described. I have branches in my fork off of release-fix and master, and can create a PR for either or both.

**Comment by Ciki** [comment]
@vlucas Is this (or has this) being addressed?

**Comment by drippsj** [comment]
I am running into this issue. Has anyone tested https://github.com/vlucas/frisby/pull/180 to see if it fixes the issue?

**Comment by jkwohlfahrt** [comment]
I am still running into this issue as well.

**Comment by ramsey** [comment]
Bump. Me, too.

**Comment by joeyjake** [comment]
Has this issue been resolved? I'm running into it if someone can redirect me that would be great

**Comment by vlucas** [comment]
This will never work in 0.x due to the reasons outlined in #316. Please update to v2.
