### ISSUE TITLE
Nesting custom matcher functions not working

### ISSUE THREAD

**Issue by FrigoEU** [vlucas/frisby#94]
Hey, very nice project, but I had some trouble getting nested customer matcher functions to work. EG:

```
 .expectJSON({
      aUserInfo: {
        Attributes: function(val){
          expect(val[1]).toEqual("Frisby");
          expect(val[2]).toEqual("Simon");
        }
  })
```

I looked around a bit and found this line to be the culprit:

(in function declaration of _jsonContains)

```
if(_toType(keyType) === "object" && arguments.callee.caller.name === "") {
```

I removed the check on arguments.callee.caller.name === "", and it works, however I am wondering why this line is in there. I don't immediately see the reasoning behind it.

Simon

**Comment by duendex** [comment]
Same issue here.

**Comment by vlucas** [comment]
This will never work in 0.x due to the reasons outlined in #316. Please update to v2.
