### ISSUE TITLE
Frisby in the browser

### ISSUE THREAD

**Issue by gnarlyfactory** [vlucas/frisby#95]
Hi Vance,
First let me say thank you for writing frisby, it's been great to use and has given me great test coverage for legacy code which would require a lot of refactoring to be otherwise (unit) testable.

I'm trying to see if it's feasible to run frisby within the browser.  Basically, I'd like to use Jasmine's specrunner to execute a test suite (set of specs).  It seems possible, albeit will require some more tinkering.  For example, https://github.com/iriscouch/browser-request can be stubbed in place of node.js/request.

If I go about doing this, how would you propose I affiliate (or would you rather I not) the browser-frisby module I am proposing to your module.  Also, what do you think the best way of making sure future changes to frisby get incorporated to browser-frisby?  Perhaps having browser be an option?

Cheers,
Charles

**Comment by vlucas** [comment]
If you still want to do this for v2 (should be easier now that it uses the fetch() API), I will put it on the website. :)
