### ISSUE TITLE
Running tests in multiple files sequentially

### ISSUE THREAD

**Issue by pigulla** [vlucas/frisby#98]
Assuming the following test files and their corresponding requests:

```
TestA.spec.js -> Request1->after(Request2)
TestB.spec.js -> Request3
TestC.spec.js -> Request4
```

When I run `jasmine-node` in this directory, they are executed in the following order:

```
Request1
Request3
Request4
Request2
```

which obviously is not what I want. Since each "top level request" loads a fixture into the database, it is impossible to do any first-this-then-that kind of tests.

I believe I ran into a similar issue with Jasmine before, so I'm assuming the problem isn't necessarily with Frisby, but maybe you can give some advice as to how this can be solved?

Issue #13 references a similar problem, but as I understand it the proposed solution with `after` doesn't work for tests spread across multiple files.

Any ideas?

**Comment by JeffML** [comment]
I resorted to something like this to chain tests together:
```javascript
var frisby = require('frisby');

var url = 'http://...';
var testIndex = 0;

function next(state) {
    if (tests.length > ++testIndex) {
        tests[testIndex](state);
    } else {
        console.log("KTHXBYE");
    }
}

function testWrapper(testName, state, transition, expect, doInspect) {
    state.transition = transition

    var theFriz = frisby.create(testName);

    theFriz
        .post(url, state, {json: true})
        .expectStatus(200)
        .afterJSON(next)
        .expectJSON(expect);
    
    if (doInspect) {
        theFriz.inspectJSON();
    } 
    
    theFriz.toss();
}
console.log("HAI!\n")

var tests = [
    function(state) {
        testWrapper("Primal State", state, {"name":"_PRIMAL_"}, {transition: "..."}, {...})
   },
   function(state) {  //next test...
  }, ...
]

// fire it off:
tests[0]({"state":{}}); 
```

**Comment by ruttencutter** [comment]
Has any progress been made down this path?  Running a pretty comprehensive set of API tests and while running each unit in separate .js test files works fine, would be nice to just have jasmine run the entire folder without having to maintain separate scripts to wall off things like authentication system tests breaking authentication for other root level tests....  are test groups supported yet? (Or could it be logically inferred by being in separate test files?)

**Comment by igordeoliveirasa** [comment]
+1
I'm facing with problems when I just call: jasmine-node specs/api (where contains multiple .spec.js files)

It would be nice if I didn't have to call jasmine-node for each one.

**Comment by igordeoliveirasa** [comment]
By the way, I created a shell script like that:

`#!/usr/bin/env bash

for file in ./specs/api/*spec.js
do
  echo $file
  jasmine-node $file
done`

**Comment by fatmatto** [comment]
I also had to write a shell script to fire tests one by one. Is there a configuration step to avoid this?

Or are test supposed to be launched as separate files with jasmine and frisby?

**Comment by emre-yildirim** [comment]
I also created a bat script which executes tests under spec/api folder and all its subdirectories.

```
@echo off

for /D %%i in (spec/api/*) do for /R %%f in (%%i/*spec.js) do echo INFO: Executing %%i/%%~nxf  & CALL jasmine-node spec/api/%%i/%%~nxf

pause
```

**Comment by andreyunugro** [comment]
How about using gulp-jasmine-node?
```
// Define source js.
const source = ['**/*spec.js', '!node_modules/**'];
// Define gulp task: test using jasmineNode.
gulp.task('test', () => {
  gulp.src(source)
  .pipe(jasmineNode({ timeout: 10000 }));
});
```

**Comment by JeffML** [comment]
How about mocha + superagent?  This does everything I needed from frisby, with easy sequential execution of tests. I made the switch and not looking back.

**Comment by vlucas** [comment]
Frisby.js uses Jasmine syntax, so as of v2, you will now be able to use [Jest.js](https://facebook.github.io/jest/) to run tests sequentially and fully asynchronously.

**Comment by java333** [comment]
Yeah, I really don't understand why JavaScript/NodeJS is like this. Every other language has a decent automation testing framework that allows for sequential test execution.

It's no wonder that post secondary institutions rarely teach JavaScript and much prefer object oriented languages such as Java.

**Comment by vlucas** [comment]
@java333 your comment doesn't add anything to the discussion by simply complaining. I already provided a solution. Jest is an excellent tool that does exactly this, and runs Jasmine based tests with no issue or changes.

**Comment by M-Steve1** [comment]
Naming your files sequentially by prefixing a number should help jasmine run your test files in the sequence you want.
